Repository goatcorp/DalamudPluginsD17, pull requests merged in 2022-12, with the labels that each got.

#738 [Testing] DutyTracker 0.0.0.1
  testing/live/DutyTracker/images/icon.png
  testing/live/DutyTracker/manifest.toml
Labels: new plugin, code reviewed

#785 [Testing] OofPlugin 1.0.4
  testing/live/OofPlugin/images/icon.png
  testing/live/OofPlugin/manifest.toml
Labels: new plugin, code reviewed

#817 [Testing] DeepDungeonDex 2.0.0
  testing/live/DeepDungeonDex/images/icon.png
  testing/live/DeepDungeonDex/manifest.toml
Labels: big

#793 XIVInstantMessenger 1.2.0.9
  stable/Messenger/manifest.toml
Labels: big

#808 [Testing] New Plugin: Mappy
  testing/live/Mappy/images/icon.png
  testing/live/Mappy/manifest.toml
Labels: new plugin

#806 [Testing] PartyPlanner 1.4.1.0
  testing/live/PartyPlanner/images/icon.png
  testing/live/PartyPlanner/manifest.toml
Labels: new plugin

#788 [Testing] DeepDungeonTracker 0.0.0.1
  testing/live/DeepDungeonTracker/images/icon.png
  testing/live/DeepDungeonTracker/manifest.toml
Labels: new plugin, code reviewed

#862 [Testing] Add Wholist
  testing/live/Wholist/images/icon.png
  testing/live/Wholist/manifest.toml
Labels: new plugin, code reviewed

#873 [Testing] MonsterLootHunter 1.0.3
  testing/live/MonsterLootHunter/images/icon.png
  testing/live/MonsterLootHunter/manifest.toml
Labels: new plugin
