Repository goatcorp/DalamudPluginsD17, pull requests merged in 2022-08, with the labels that each got.

#60 [Testing] Tilted Plugin v0.0.0.1
  testing/live/Tilted/manifest.toml
Labels: new plugin

#82 [Testing] UsedName v0.7.5.0
  testing/live/UsedName/manifest.toml
Labels: new plugin, needs testing

#50 [Testing] Add GoodFriend
  testing/live/GoodFriend/images/icon.png
  testing/live/GoodFriend/manifest.toml
Labels: new plugin

#95 [Testing] Add Price insight
  testing/live/PriceInsight/images/icon.png
  testing/live/PriceInsight/images/image1.png
  testing/live/PriceInsight/manifest.toml
  testing/net6/PriceInsight/images/icon.png
  testing/net6/PriceInsight/images/image1.png
  testing/net6/PriceInsight/manifest.toml
Labels: new plugin

#58 [Testing] Collector's Anxiety DevPreview 1
  testing/live/CollectorsAnxiety/images/icon.png
  testing/live/CollectorsAnxiety/manifest.toml
Labels: new plugin, code reviewed

#177 [Testing] ReSanctuary 1.1.0.0
  testing/live/ReSanctuary/images/icon.png
  testing/live/ReSanctuary/manifest.toml
Labels: new plugin, code reviewed

#79 [Testing] Add HuntHelper
  testing/live/HuntHelper/images/icon.png
  testing/live/HuntHelper/images/image1.png
  testing/live/HuntHelper/images/image2.png
  testing/live/HuntHelper/images/image3.png
  testing/live/HuntHelper/images/image4.png
  testing/live/HuntHelper/manifest.toml
Labels: new plugin, code reviewed

#282 [Testing] Add WhichPatchWasThat 1.0
  testing/live/WhichPatchWasThat/images/icon.png
  testing/live/WhichPatchWasThat/images/image1.png
  testing/live/WhichPatchWasThat/manifest.toml
Labels: new plugin
