Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-02, with the labels that each got.

#1186 JobBars v1.2.3.4
  stable/JobBars/manifest.toml
Labels: blocked

#1206 [Testing] DaCoblyn 1.0.0.0
  testing/live/DaCoblyn/images/icon.png
  testing/live/DaCoblyn/manifest.toml
Labels: new plugin, code reviewed

#1209 [Testing] Hunty
  testing/live/Hunty/images/icon.png
  testing/live/Hunty/manifest.toml
Labels: new plugin, code reviewed

#1077 [Testing] PositionalGuide
  testing/live/PositionalGuide/manifest.toml
Labels: new plugin, code reviewed

#1076 [Testing] MarketUploader
  testing/live/MarketUploader/images/icon.png
  testing/live/MarketUploader/manifest.toml
Labels: new plugin, code reviewed

#1183 [Testing] TargetLines plugin
  testing/live/TargetLines/manifest.toml
Labels: new plugin, code reviewed

#1030 [Testing] Hybrid Camera
  testing/live/HybridCamera/manifest.toml
Labels: new plugin, code reviewed

#1202 [Testing] rtyping 0.0.1.4
  testing/live/rtyping/images/icon.png
  testing/live/rtyping/manifest.toml
Labels: new plugin, code reviewed

#1219 [Testing] Better Targeting System
  testing/live/BetterTargetingSystem/manifest.toml
Labels: new plugin, code reviewed

#1151 [Testing] borderless-fix v0.0.0.1
  testing/live/borderless-fix/images/icon.png
  testing/live/borderless-fix/manifest.toml
Labels: new plugin, code reviewed

#1237 [Testing] Congratulations 1.0.0.0
  testing/live/Congratulations/images/icon.png
  testing/live/Congratulations/manifest.toml
Labels: new plugin

#1343 [Testing] NoTankYou v5.1.3.0
  testing/live/NoTankYou/manifest.toml
Labels: big
