Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-05, with the labels that each got.

#1338 [Testing] CameraLoader
  testing/live/CameraLoader/images/icon.png
  testing/live/CameraLoader/manifest.toml
Labels: new plugin

#1761 Honorific 1.0.0.0
  stable/Honorific/images/icon.png
  stable/Honorific/manifest.toml
Labels: move channel

#1775 DiscordBridge 14.2.1
  stable/Dalamud.DiscordBridge/manifest.toml
Labels: size-small

#1776 [Testing] CrossUp 0.4.3.2
  testing/live/CrossUp/manifest.toml
Labels: size-mid

#1777 VFXEditor v1.7.4.8
  stable/VFXEditor/manifest.toml
Labels: size-mid

#1779 Allagan Tools v1.5.0.1
  stable/InventoryTools/manifest.toml
Labels: size-mid

#1778 [Testing] Bozja Buddy 0.3.1.0
  testing/live/BozjaBuddy/manifest.toml
Labels: size-small

#1782 Honorific 1.0.1.0
  stable/Honorific/manifest.toml
Labels: size-small

#1781 CharacterPanelRefined 1.7.1.4
  stable/CharacterPanelRefined/manifest.toml
Labels: size-mid

#1783 Move PushyFinder to live
  stable/PushyFinder/images/icon.png
  stable/PushyFinder/manifest.toml
  testing/live/PushyFinder/manifest.toml
Labels: move channel, size-small

#1785 DailyDuty v4.0.1.3
  stable/DailyDuty/manifest.toml
Labels: size-small

#1786 [Testing] Orchestrion 1.9.1.0 -> 1.9.1.1
  testing/live/orchestrion/manifest.toml
Labels: size-small

#1787 EurekaHelper 1.5.0.0
  stable/EurekaHelper/manifest.toml
Labels: size-mid

#1788 Update repo locations
  stable/TitleRoulette/manifest.toml
  testing/live/CollectableCalculator/manifest.toml
Labels: size-mid

#1789 DailyDuty v4.0.1.4
  stable/DailyDuty/manifest.toml
Labels: size-small

#1792 Eureka Linker 1.4.0.1
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#1795 Player Tags v1.9.1
  stable/PlayerTags/manifest.toml
Labels: size-small

#1796 EurekaHelper 1.5.0.2
  stable/EurekaHelper/manifest.toml
Labels: size-small

#1794 [Testing] Bozja Buddy 0.3.2.2
  testing/live/BozjaBuddy/manifest.toml
Labels: size-small

#1798 Hunty 1.0.0.7
  stable/Hunty/manifest.toml
Labels: size-small

#1799 Eureka Linker 1.4.0.2
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#1803 Hunty 1.1.0.0
  stable/Hunty/manifest.toml
Labels: size-small

#1802 EurekaHelper 1.5.0.3
  stable/EurekaHelper/manifest.toml
Labels: size-small

#1801 Submarine Tracker 1.3.0.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1800 [Testing] Bozja Budddy 0.3.2.3
  testing/live/BozjaBuddy/manifest.toml
Labels: size-small

#1806 Eureka Linker 1.4.0.3
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#1805 SubmarineTracker 1.3.0.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1804 [Testing] RPBlurb 1.0.1.0 - Overlay hidden in combat
  testing/live/RPBlurb/manifest.toml
Labels: size-mid

#1812 [Stable] UsedName v0.8.2.3
  stable/UsedName/manifest.toml
Labels: size-small

#1811 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-small

#1810 EurekaHelper 1.5.1.4
  stable/EurekaHelper/manifest.toml
Labels: size-small

#1797 VFXEditor 1.7.5.0
  stable/VFXEditor/manifest.toml
Labels: size-mid

#1808 ChatBubbles 2.1.3.1
  stable/ChatBubbles/manifest.toml
Labels: size-small

#1809 Submarine Tracker 1.4.0.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1753 [Testing] Fantasy Player 2.0.0.0
  testing/live/FantasyPlayer/images/icon.png
  testing/live/FantasyPlayer/manifest.toml
Labels: new plugin

#1818 ItemSearchPlugin 1.9.3.1
  stable/ItemSearchPlugin/manifest.toml
Labels: size-small

#1819 Adventurer in Need 1.3.0.2
  stable/AdventurerInNeed/manifest.toml
Labels: size-small

#1817 XIVDeck 0.3.13
  stable/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-mid

#1821 Simple Tweaks 1.8.7.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#1820 Honorific 1.0.1.1
  stable/Honorific/manifest.toml
Labels: size-small

#1823 ActionTimeline release 1.2.0.0
  stable/ActionTimeline/manifest.toml
Labels: size-small

#1824 Allagan Tools 1.5.0.2
  stable/InventoryTools/manifest.toml
Labels: size-small

#1825 Player Tags 1.9.2
  stable/PlayerTags/manifest.toml
Labels: size-small

#1832 [Testing] HighFpsPhysicsPlugin 7.1.1
  testing/live/HighFpsPhysicsPlugin/manifest.toml
Labels: size-small

#1833 InventorySearchBar release 1.3.0.0
  stable/InventorySearchBar/manifest.toml
Labels: size-small

#1834 Himbeertoni Raid Tool 1.3.0.0
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#1829 DamageInfoPlugin 2.3.0.1 -> 2.3.0.2
  stable/DamageInfoPlugin/manifest.toml
Labels: size-small

#1830 Housemate 1.0.2.9 -> 1.0.2.10
  stable/Housemate/manifest.toml
Labels: size-small

#1835 LogogramHelper 0.0.2.0
  stable/LogogramHelper/manifest.toml
Labels: size-small

#1838 PriceCheck 2.5.1.0
  stable/PriceCheck/manifest.toml
Labels: size-small

#1814 Eureka Linker 1.4.0.4
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#1840 [Testing] rtyping 0.0.1.6
  testing/live/rtyping/manifest.toml
Labels: size-small

#1816 PartyPlanner 1.5.2
  stable/PartyPlanner/manifest.toml
  testing/live/PartyPlanner/manifest.toml
Labels: size-small

#1843 [Testing] Redirect 1.2.1.5
  testing/live/Redirect/manifest.toml
Labels: size-small

#1841 DeathRecap 1.10.2.0
  stable/DeathRecap/manifest.toml
Labels: size-small

#1847 ffxiv2mqtt 1.0.4.4
  stable/Ffxiv2Mqtt/manifest.toml
Labels: size-small

#1846 Update PushyFinder for Patch 6.4
  stable/PushyFinder/manifest.toml
Labels: size-small

#1848 DutyTracker 1.0.1.2
  stable/DutyTracker/manifest.toml
  testing/live/DutyTracker/images/icon.png
  testing/live/DutyTracker/manifest.toml
Labels: size-mid

#1851 Accountant 1.3.5.1
  stable/Accountant/manifest.toml
Labels: size-small

#1850 GatherBuddy 3.2.4.0
  stable/GatherBuddy/manifest.toml
Labels: size-small

#1849 MonsterLootHunter 1.0.17.4
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#1852 DailyDuty v4.0.1.5
  stable/DailyDuty/manifest.toml
Labels: size-small

#1854 [Testing] A Realm Recorded v0.6.0.3
  testing/live/ARealmRecorded/manifest.toml
Labels: size-small

#1856 Honorific 1.0.1.2
  stable/Honorific/manifest.toml
Labels: size-small

#1858 Better Shadows update for 6.4
  stable/BetterShadows/manifest.toml
Labels: size-small

#1860 Simple Tweaks 1.8.7.2
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#1859 [Testing] CameraLoader v0.1.4.1
  testing/live/CameraLoader/manifest.toml
Labels: size-mid

#1862 FlyTextFilter 4.1.3.6
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#1864 MacroRecorded 1.0.0.1
  stable/MacroRecorded/images/icon.png
  stable/MacroRecorded/manifest.toml
Labels: move channel, size-small

#1863 EurekaHelper 1.5.1.6
  stable/EurekaHelper/manifest.toml
Labels: size-small

#1867 MacroRecorded 1.0.0.2
  stable/MacroRecorded/manifest.toml
Labels: move channel, size-small

#1868 Submarine Tracker 1.4.1.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1869 Update Anna plogons
  stable/ChatTwo/manifest.toml
  stable/Glamaholic/manifest.toml
  stable/XIVChat/manifest.toml
Labels: size-small

#1861 Orchestrion 2.0.0.0 -> 2.0.0.1
  stable/orchestrion/manifest.toml
Labels: size-small

#1872 SubmarineTracker 1.4.2.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1871 Update XIVChat and ChatTwo
  stable/ChatTwo/manifest.toml
  stable/XIVChat/manifest.toml
Labels: size-small

#1870 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small

#1873 TooltipNotes 1.1.2.0
  stable/TooltipNotes/manifest.toml
Labels: size-small

#1874 [Testing] HighFpsPhysicsPlugin 7.2.0.0
  testing/live/HighFpsPhysicsPlugin/manifest.toml
Labels: size-small

#1878 SubmarineTracker 1.4.2.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1877 Player Tags 1.9.3
  stable/PlayerTags/manifest.toml
Labels: size-small

#1876 [Testing] rtyping 0.0.1.7
  testing/live/rtyping/manifest.toml
Labels: size-small

#1879 DailyDuty v4.0.1.6
  stable/DailyDuty/manifest.toml
Labels: size-small

#1881 JobBars v1.2.3.6
  stable/JobBars/manifest.toml
Labels: size-small

#1882 VFXEditor v1.7.5.1
  stable/VFXEditor/manifest.toml
Labels: size-small

#1883 NoTankYou v5.1.3.3
  stable/NoTankYou/manifest.toml
Labels: size-small

#1884 DelvUI release 1.7.1.0
  stable/DelvUI/manifest.toml
Labels: size-small

#1886 PingPlugin v2.5.2
  stable/PingPlugin/manifest.toml
Labels: size-small

#1885 SoundSetter v1.7.2
  stable/SoundSetter/images/icon.png
  stable/SoundSetter/manifest.toml
Labels: size-small

#1887 Wholist v1.2.1.0
  stable/Wholist/manifest.toml
Labels: size-small

#1888 [Testing] A Realm Recorded v0.7.0.0
  testing/live/ARealmRecorded/manifest.toml
Labels: size-mid

#1890 SubmarineTracker 1.4.2.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1891 [Testing] OofPlugin v1.2.0.0
  testing/live/OofPlugin/manifest.toml
Labels: size-mid

#1893 GatherBuddy 3.2.4.1
  stable/GatherBuddy/manifest.toml
Labels: size-mid

#1894 [Testing] NoKillPlugin 1.0.8.0
  testing/live/NoKillPlugin/images/icon.png
  testing/live/NoKillPlugin/manifest.toml
Labels: size-small

#1897 DelvUI release 1.7.1.1
  stable/DelvUI/manifest.toml
Labels: size-small

#1895 Player Tags v1.9.4
  stable/PlayerTags/manifest.toml
Labels: size-small

#1896 CharacterPanelRefined 1.7.1.5
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small

#1898 moaction 6.4
  stable/MOAction/manifest.toml
Labels: size-small

#1899 [Testing] Collector's Anxiety 0.0.5
  testing/live/CollectorsAnxiety/manifest.toml
Labels: size-small

#1900 WaymarkPresetPlugin v1.4.6.0
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-mid

#1901 Update Peeping Tom to 1.7.14
  stable/PeepingTom/manifest.toml
Labels: size-small

#1902 Wholist v1.2.2.0
  stable/Wholist/manifest.toml
Labels: size-small

#1903 NamePlateDebuffs v1.0.2.0
  stable/NamePlateDebuffs/manifest.toml
Labels: size-small

#1904 [Testing] Bozja Buddy 0.3.4.2
  testing/live/BozjaBuddy/manifest.toml
Labels: size-mid

#1910 [Testing] Hit it, Joe! (Formerly TF2-ish Critical Hits Plugin) 3.4.0.0
  testing/live/Tf2CriticalHitsPlugin/manifest.toml
Labels: size-small

#1905 GoodFriend v1.4.7.0
  stable/GoodFriend/manifest.toml
Labels: size-mid

#1909 Update Minimappingway for 6.4 (fixed bugs)
  stable/MiniMappingway/manifest.toml
Labels: size-small

#1906 PartyIcons v1.1.4.0
  stable/PartyIcons/manifest.toml
Labels: size-small

#1908 Himbeertoni Raid Tool 1.3.0.1
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#1907 Update ChatBubbles to v2.1.4.0
  stable/ChatBubbles/manifest.toml
Labels: size-small

#1911 [Testing] TextToTalk v1.26.0
  testing/live/TextToTalk/manifest.toml
Labels: size-mid

#1912 Update ExtraChat to 1.3.2
  stable/ExtraChat/manifest.toml
Labels: size-small

#1924 ItemVendorLocation v2.2.0.2
  stable/ItemVendorLocation/manifest.toml
Labels: size-small

#1923 Update The Great Separator to 1.2.6
  stable/TheGreatSeparator/manifest.toml
Labels: size-small

#1913 [Testing] Bozja Buddy 0.3.4.3
  testing/live/BozjaBuddy/manifest.toml
Labels: size-small

#1914 [Testing] Fantasy Player v2.1.1.1
  testing/live/FantasyPlayer/manifest.toml
Labels: size-small

#1915 Allagan Tools v1.5.0.3
  stable/InventoryTools/manifest.toml
Labels: size-small

#1916 Add GentleTouch 1.10.4
  stable/GentleTouch/manifest.toml
Labels: size-small

#1917 Hit it, Joe! (Formerly TF2-ish Critical Hits Plugin) 3.4.0.0
  stable/Tf2CriticalHitsPlugin/manifest.toml
Labels: size-small

#1918 DeathRecap v1.10.2.1
  stable/DeathRecap/manifest.toml
Labels: size-small

#1919 Himbeertoni Raid Tool 1.3.0.2
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#1920 [Testing] BetterMountRoulette 1.2.0.12
  testing/live/BetterMountRoulette/images/icon.png
  testing/live/BetterMountRoulette/manifest.toml
Labels: move channel, size-small

#1921 Submarine Tracker 1.5.0.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#1922 Echoglossian 3.x era has begun
  stable/Echoglossian/manifest.toml
Labels: size-mid

#1925 [Testing] Bozja Buddy 0.3.4.4
  testing/live/BozjaBuddy/manifest.toml
Labels: size-small

#1926 CrossUp v1.0.0.1
  stable/CrossUp/manifest.toml
Labels: size-small

#1934 Update Glamaholic to 1.9.12
  stable/Glamaholic/manifest.toml
Labels: size-small

#1927 [Release] BetterMountRoulette 1.2.0.12
  stable/BetterMountRoulette/manifest.toml
  testing/live/BetterMountRoulette/images/icon.png
  testing/live/BetterMountRoulette/manifest.toml
Labels: size-small

#1928 Allagan Tools v1.5.0.4
  stable/InventoryTools/manifest.toml
Labels: size-small

#1929 SubmarineTracker 1.5.1.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1931 EnemyListDebuffs v0.3.8.0
  stable/EnemyListDebuffs/manifest.toml
Labels: size-small

#1933 Wholist v1.3.0.0
  stable/Wholist/manifest.toml
Labels: size-small

#1932 [Testing] HudManager 2.5.13-b1
  testing/live/HUDManager/manifest.toml
Labels: size-small

#1935 Update AutoMammet for 6.4
  stable/AutoMammet/manifest.toml
Labels: size-small

#1937 AutoMammet 1.4.1.0 - Fix issues in AutoMammet offsets/rendering.
  stable/AutoMammet/manifest.toml
Labels: size-small

#1875 Update StackSellPrice (stable)
  stable/StackSellPrice/manifest.toml
Labels: size-mid

#1939 VFXEditor 1.7.5.2
  stable/VFXEditor/manifest.toml
Labels: size-small

#1938 MemoryMarker v1.0.0.4
  stable/MemoryMarker/manifest.toml
Labels: size-small

#1943 Orchestrion 2.0.0.1 -> 2.0.0.2
  stable/orchestrion/manifest.toml
Labels: size-mid

#1942 Fancy Loading Screens 1.0.0.11
  stable/Dalamud.LoadingImage/manifest.toml
Labels: size-small

#1941 [Testing] Bozja Buddy 0.3.5.1
  testing/live/BozjaBuddy/manifest.toml
Labels: size-mid

#1940 Himbeertoni Raid Tool 1.3.0.4
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#1944 PriceInsight v2.5.0.0
  stable/PriceInsight/manifest.toml
Labels: size-small

#1945 xivcombo 1.7.24
  stable/XIVCombo/manifest.toml
Labels: size-small

#1946 [Testing] Better Housing v1.1.2
  testing/live/ProperHousing/manifest.toml
Labels: size-small
