Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-11, with the labels that each got.

#2816 XIVLogger 1.0.5.2
  stable/XIVLogger/manifest.toml
Labels: size-small

#2806 HuntHelper V1.0.0.11
  stable/HuntHelper/manifest.toml
Labels: size-small

#2815 Pet nicknames v1.4.3.2
  stable/PetRenamer/manifest.toml
  testing/live/PetRenamer/manifest.toml
Labels: size-large

#2805 [Release] Better Mount Roulette 1.3.0.15
  stable/BetterMountRoulette/manifest.toml
  testing/live/BetterMountRoulette/images/icon.png
  testing/live/BetterMountRoulette/manifest.toml
Labels: size-mid

#2825 Tracky Track 1.3.0.9
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2824 [Testing] PlayerTrack
  testing/live/PlayerTrack/manifest.toml
Labels: size-small

#2820 Wordsmith v.1.10.1
  stable/Wordsmith/manifest.toml
Labels: size-small

#2818 NoTankYou v6.0.1.4
  stable/NoTankYou/manifest.toml
Labels: size-small

#2817 Mappy v1.0.6.0
  testing/live/Mappy/manifest.toml
Labels: size-small

#2832 Wordsmith v1.11.0
  stable/Wordsmith/manifest.toml
Labels: size-small

#2826 NoTankYou v6.0.1.6
  stable/NoTankYou/manifest.toml
Labels: size-small

#2827 [Testing] Pet Nicknames v1.4.3.3
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2830 Tick Tracker 1.1.0.0
  stable/TickTracker/manifest.toml
Labels: size-small

#2831 CopyTranslated v1.1.0
  stable/CopyTranslated/manifest.toml
Labels: size-small

#2819 Snooper 1.2.1.1
  stable/Snooper/manifest.toml
Labels: size-mid

#2821 [Testing] PartyListExtras 0.0.2.0
  testing/live/PartyListExtras/images/icon.png
  testing/live/PartyListExtras/manifest.toml
Labels: size-mid

#2822 [stable] WorklshopOptimizerPlugin 0.2.8.2
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-mid

#2829 SubmarineTracker 1.8.1.4
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2794 Simple Tweaks 1.9.2.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-large

#2771 VFXEditor v1.8.0.6
  stable/VFXEditor/manifest.toml
Labels: size-large

#2835 [Testing] PlayerTrack
  testing/live/PlayerTrack/manifest.toml
Labels: size-small

#2833 Plx-0021
  testing/live/PartyListExtras/manifest.toml
Labels: size-small

#2837 XIVLogger 1.0.5.3
  stable/XIVLogger/manifest.toml
Labels: size-small

#2834 Chatter -- Updated to support v6.51
  testing/live/Chatter/manifest.toml
Labels: size-small

#2808 Currency Tracker 1.3.1.1
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#2840 [Testing] Pet Nicknames v1.4.3.4
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2839 TrackyTrack 1.3.1.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2836 Eureka Linker 1.5.0.4
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-mid

#2778 [Testing] rtyping 0.1.0.0
  testing/live/rtyping/manifest.toml
Labels: size-mid

#2841 Update FCNameColor to 4.0.0.3
  stable/FCNameColor/manifest.toml
Labels: size-small

#2842 DiademCalculator Stable
  stable/DiademCalculator/images/icon.png
  stable/DiademCalculator/manifest.toml
Labels: move channel, size-small

#2843 Diadem Calculator 1.0.0.0
  stable/DiademCalculator/manifest.toml
Labels: size-small

#2844 DutyTracker 1.0.1.7
  stable/DutyTracker/manifest.toml
Labels: size-small

#2846 Wordsmith v1.11.1
  stable/Wordsmith/manifest.toml
Labels: size-small

#2847 Currency Tracker 1.3.1.2
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#2848 TrackyTrack 1.3.1.1
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2849 Audible Character Status 1.0.1.4
  stable/AudibleCharacterStatus/manifest.toml
Labels: size-small

#2850 KingdomHeartsPlugin 1.0.7.0
  stable/KingdomHeartsPlugin/manifest.toml
Labels: size-small

#2851 TextToTalk v1.24.2.6
  stable/TextToTalk/manifest.toml
Labels: size-small

#2853 Simple Tweaks 1.9.2.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#2859 NoTankYou v6.0.1.7
  stable/NoTankYou/manifest.toml
Labels: size-small

#2857 CopyTranslated v1.1.1
  stable/CopyTranslated/manifest.toml
Labels: size-small

#2856 Currency Tracker 1.3.1.3
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#2855 HuntHelper V1.0.0.12
  stable/HuntHelper/manifest.toml
Labels: size-small

#2860 Tick Tracker 1.1.1.0
  stable/TickTracker/manifest.toml
Labels: size-small

#2873 HuntHelper v1.0.0.13
  stable/HuntHelper/manifest.toml
Labels: size-small

#2872 SonarPlugin v0.6.0.1
  stable/SonarPlugin/manifest.toml
Labels: size-small

#2866 Item Search 1.9.5.0
  stable/ItemSearchPlugin/manifest.toml
Labels: size-small

#2864 [Testing] Pet Nicknames v1.4.3.5
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2863 Tracky 1.3.2.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2862 DeepDungeonTracker 1.0.0.6
  stable/DeepDungeonTracker/manifest.toml
Labels: size-small

#2861 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-small

#2865 Mappy v1.0.6.3
  stable/Mappy/manifest.toml
Labels: size-small

#2868 DelvCD release 0.5.2.0
  testing/live/DelvCD/manifest.toml
Labels: size-small

#2867 Currency Tracker 1.3.1.4
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#2874 PlayerTrack v3.2.7.0
  stable/PlayerTrack/manifest.toml
Labels: size-large

#2878 GatherBuddy 3.3.0.2
  stable/GatherBuddy/manifest.toml
Labels: size-small

#2881 Tracky 1.3.3.0
  stable/TrackyTrack/manifest.toml
Labels: size-large

#2880 NotificationMaster 2.1.1.1
  stable/NotificationMaster/manifest.toml
Labels: size-small

#2875 HotbarUnlimited
  stable/HotbarUnlimited/images/icon.png
  stable/HotbarUnlimited/manifest.toml
Labels: move channel, size-small

#2876 Currency Tracker 1.3.1.5
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#2885 [Testing] Himbeertoni Raid Tool 1.4.0.0
  testing/live/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#2886 [Testing] rtyping 0.1.0.1
  testing/live/rtyping/manifest.toml
Labels: size-small

#2884 Honorific 1.3.1.0
  stable/Honorific/manifest.toml
Labels: size-small

#2883 Collections v1.0.0.4
  testing/live/Collections/manifest.toml
Labels: size-small

#2882 Tracky 1.3.3.1
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2889 Currency Tracker 1.3.1.6
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#2887 [Testing] Pet Nicknames v1.4.4.0
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#2898 Update ExtraChat to 1.3.5
  stable/ExtraChat/manifest.toml
Labels: size-small

#2891 [Testing] Pet Nicknames v1.4.4.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2894 Update MidoriKamiPlugins
  stable/DailyDuty/manifest.toml
  stable/Mappy/manifest.toml
  stable/NoTankYou/manifest.toml
Labels: size-small

#2897 Honorific 1.4.0.0
  stable/Honorific/manifest.toml
Labels: size-small

#2896 DeepDungeonTracker 1.0.0.7
  stable/DeepDungeonTracker/manifest.toml
Labels: size-small

#2895 Currency Tracker 1.3.1.8
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#2893 Tracky 1.3.4.0
  stable/TrackyTrack/manifest.toml
Labels: size-large

#2877 DeepDungeonDex 2.8.2
  stable/DeepDungeonDex/manifest.toml
Labels: size-mid

#2858 VFXEditor v1.8.1.0
  stable/VFXEditor/manifest.toml
Labels: size-large

#2811 [Testing] Distance 1.1.0.0
  testing/live/Distance/images/icon.png
  testing/live/Distance/images/image1.png
  testing/live/Distance/images/image2.png
  testing/live/Distance/manifest.toml
Labels: move channel, size-large

#2899 HotbarUnlimited v1.0.1.0
  stable/HotbarUnlimited/manifest.toml
Labels: size-small

#2904 TextToTalk v1.28.3
  stable/TextToTalk/manifest.toml
Labels: size-large

#2903 [Testing] Linkpearl 2.0.0.0
  testing/live/Linkpearl/manifest.toml
Labels: size-mid

#2902 Better in Blue 1.2.0.0
  stable/BetterInBlue/manifest.toml
Labels: size-small

#2901 ReSanctuary 1.3.0.1
  stable/ReSanctuary/manifest.toml
Labels: size-small

#2900 VFXEditor v1.8.1.5
  stable/VFXEditor/manifest.toml
Labels: size-large

#2909 DeepDungeonDex 2.8.3
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#2907 [Testing] Pet Nicknames v1.4.4.2
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2911 TickTracker 1.1.2.0
  stable/TickTracker/manifest.toml
Labels: size-small

#2910 TextToTalk v1.28.4
  stable/TextToTalk/manifest.toml
Labels: size-small

#2906 Pet Nicknames v1.4.4.1
  stable/PetRenamer/manifest.toml
Labels: size-large

#2913 TextToTalk v1.28.5
  stable/TextToTalk/manifest.toml
Labels: size-small

#2914 [testing] Tilted v3.4.0.0
  testing/live/Tilted/manifest.toml
Labels: size-small

#2917 Currency Tracker 1.3.1.9
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#2916 Simple Tweaks 1.9.2.2
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#2908 Coordinate Importer v1.1.0.0
  testing/live/CoordImporter/manifest.toml
Labels: size-large

#2790 [Testing] Seated Sidekick Spectator 0.1.0.0
  testing/live/SeatedSidekickSpectator/images/icon.png
  testing/live/SeatedSidekickSpectator/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#2845 [Testing] IslandWorkshopSearch v0.0.0.1
  testing/live/IslandWorkshopSearch/images/icon.png
  testing/live/IslandWorkshopSearch/images/image1.png
  testing/live/IslandWorkshopSearch/images/image2.png
  testing/live/IslandWorkshopSearch/images/image3.png
  testing/live/IslandWorkshopSearch/images/image4.png
  testing/live/IslandWorkshopSearch/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#2869 [Testing] MapGilTracker v0.1.0.0
  testing/live/MapGilTracker/images/icon.png
  testing/live/MapGilTracker/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#2871 [Testing] OpenerCreator 0.0.1
  testing/live/OpenerCreator/images/icon.png
  testing/live/OpenerCreator/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#2918 PartyListExtras v0.1.1.0
  stable/PartyListExtras/manifest.toml
Labels: size-small

#2920 PlayerTrack v3.2.8.0
  testing/live/PlayerTrack/manifest.toml
Labels: size-large

#2919 Tracky 1.3.4.2
  stable/TrackyTrack/manifest.toml
Labels: size-large

#2921 Mappy v1.0.7.1
  stable/Mappy/manifest.toml
Labels: size-mid

#2923 Pet Nicknames v1.4.4.3
  stable/PetRenamer/manifest.toml
Labels: size-small

#2924 Simple Tweaks 1.9.3.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#2926 Tracky 1.3.4.3
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2930 DailyDuty v4.0.6.1
  stable/DailyDuty/manifest.toml
Labels: size-small

#2928 [Testing] Pet Nicknames v1.4.4.4
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2925 [Testing] Collections v1.0.1.0
  testing/live/Collections/manifest.toml
Labels: size-large

#2929 Tracky 1.3.4.4
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2931 Honoriric 1.4.1.0
  stable/Honorific/manifest.toml
Labels: size-small

#2912 [Testing] Talk Copy
  testing/live/TalkCopy/images/icon.png
  testing/live/TalkCopy/manifest.toml
Labels: new plugin, completed-code-review, size-mid, completed-rules-compliance, completed-testing

#2915 [Testing] AutoTimer v1.0.0.0
  testing/live/AutoTimer/images/icon.png
  testing/live/AutoTimer/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#2658 [Testing] Map Party Assist
  testing/live/MapPartyAssist/images/icon.png
  testing/live/MapPartyAssist/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#2753 [Testing] MacroMate v1.0.5.6
  testing/live/MacroMate/images/icon.png
  testing/live/MacroMate/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#2888 Add Eorzea Votes 1.0.6
  testing/live/EorzeaVotes/images/icon.png
  testing/live/EorzeaVotes/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#2933 Pet Nicknames v1.4.4.5
  stable/PetRenamer/manifest.toml
Labels: size-small

#2935 Update Eorzea Votes to 1.1.0 and move to stable
  stable/EorzeaVotes/images/icon.png
  stable/EorzeaVotes/manifest.toml
  testing/live/EorzeaVotes/manifest.toml
Labels: move channel, size-small

#2936 DeathRoll 1.4.0.0
  stable/DeathRoll/manifest.toml
Labels: size-mid

#2937 TextToTalk v1.28.6
  stable/TextToTalk/manifest.toml
Labels: size-small

#2942 Tracky 1.3.4.5
  stable/TrackyTrack/manifest.toml
Labels: size-large

#2941 DeathRoll 1.4.1.0
  stable/DeathRoll/manifest.toml
Labels: size-mid

#2944 [Testing] scout helper patch release 0.2.1.0 for minor bugfix
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#2945 [Testing] MacroMate (v1.0.6.0)
  testing/live/MacroMate/manifest.toml
Labels: size-small

#2943 VFXEditor v1.8.1.6
  stable/VFXEditor/manifest.toml
Labels: size-small

#2948 TextToTalk v1.28.7
  stable/TextToTalk/manifest.toml
Labels: size-small

#2947 [Testing] MacroMate (v1.0.6.1)
  testing/live/MacroMate/manifest.toml
Labels: size-small

#2946 DeathRoll 1.4.1.1
  stable/DeathRoll/manifest.toml
Labels: size-small

#2949 HotbarUnlimited v1.0.1.2
  stable/HotbarUnlimited/manifest.toml
Labels: size-small

#2950 [Testing] Coordinate Importer v1.1.0.1
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#2953 [Testing] AutoTimer (v1.0.0.1)
  testing/live/AutoTimer/manifest.toml
Labels: size-small

#2955 DeathRoll 1.4.1.2
  stable/DeathRoll/manifest.toml
Labels: size-small

#2954 Hunty 1.3.0.1
  stable/Hunty/manifest.toml
Labels: size-mid

#2938 Currency Tracker 1.3.2.0
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#2956 [Testing] scout helper 0.2.2.0 minor bugfix
  testing/live/ScoutHelper/manifest.toml
Labels: size-small
