Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-12, with the labels that each got.

#2959 DeathRoll 1.4.2.0
  stable/DeathRoll/manifest.toml
Labels: size-mid

#2962 Talk Copy 0.0.0.1
  stable/TalkCopy/images/icon.png
  stable/TalkCopy/manifest.toml
Labels: move channel, size-small

#2960 Currency Tracker 1.3.2.1
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#2963 Copy Translated v1.1.2
  stable/CopyTranslated/manifest.toml
Labels: size-small

#2964 HotbarUnlimited v1.0.2.2
  stable/HotbarUnlimited/manifest.toml
Labels: size-small

#2967 Currency Tracker 1.3.2.2
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#2969 [Testing] Himbeertoni Raid Tool 1.4.1.0
  testing/live/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#2973 ChillFrames v2.1.1.0
  stable/ChillFrames/manifest.toml
Labels: size-small

#2972 Currency Tracker 1.3.2.3
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#2975 [Testing] Better Housing v1.1.4
  testing/live/ProperHousing/manifest.toml
Labels: size-small

#2976 [Testing] OpenerCreator 0.0.3
  testing/live/OpenerCreator/manifest.toml
Labels: size-small

#2974 DeathRoll 1.4.3.0
  stable/DeathRoll/manifest.toml
Labels: size-mid

#2979 [Testing] Avant-Garde v0.1.1.0
  testing/live/AvantGarde/manifest.toml
Labels: size-small

#2981 [Testing] Himbeertoni Raid Tool 1.4.1.1
  testing/live/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#2982 Partyplanner v1.6.0
  stable/PartyPlanner/manifest.toml
Labels: size-mid

#2989 [Testing] OpenerCreator v0.0.5
  testing/live/OpenerCreator/manifest.toml
Labels: size-small

#2987 JustBackup v1.1.0.5
  stable/JustBackup/manifest.toml
Labels: size-small

#2986 [Testing] Himbeertoni Raid Tool 1.4.1.2
  testing/live/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#2988 [Testing] Map Party Assist v1.0.1.0
  testing/live/MapPartyAssist/manifest.toml
Labels: size-mid

#2980 Currency Tracker 1.3.2.4
  stable/CurrencyTracker/manifest.toml
  testing/live/CurrencyTracker/images/icon.png
  testing/live/CurrencyTracker/manifest.toml
Labels: size-large

#2984 Tracky 1.3.4.6
  stable/TrackyTrack/manifest.toml
Labels: size-large

#2977 [Testing] Pet Nicknames v1.4.5.0
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#2995 MacroMate 1.0.6.1 stable release
  stable/MacroMate/images/icon.png
  stable/MacroMate/manifest.toml
Labels: move channel, size-small

#2994 [Testing] Map Party Assist v1.0.2.0
  testing/live/MapPartyAssist/manifest.toml
Labels: size-small

#2993 Currency Tracker 1.3.2.5
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#2991 Coordinate Importer v1.1.0.2
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#2997 SortaKinda v1.0.3.1
  stable/SortaKinda/manifest.toml
Labels: size-small

#2998 MacroMate 1.0.7.0
  stable/MacroMate/manifest.toml
Labels: size-small

#2999 Currency Tracker 1.3.2.6
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#2996 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-mid

#2990 PartyListExtras 1.0.0.0
  stable/PartyListExtras/manifest.toml
  testing/live/PartyListExtras/manifest.toml
Labels: size-large

#2983 Update Nameplate Debuffs to 1.0.3.0
  stable/NamePlateDebuffs/manifest.toml
Labels: size-large

#2966 [Testing] Collections v1.0.1.1
  testing/live/Collections/manifest.toml
Labels: size-large

#3000 SortaKinda v1.0.3.2
  stable/SortaKinda/manifest.toml
Labels: size-mid

#3001 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-small

#3002 CurrencyAlert v1.0.1.0
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#3003 MacroMate 1.0.7.1
  stable/MacroMate/manifest.toml
Labels: size-small

#3004 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-small

#3005 Currency Tracker 1.3.2.7
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3006 [testing] MagitekStratagem v0.2.0.0
  testing/live/MagitekStratagem/manifest.toml
Labels: size-small

#3007 SortaKinda v1.0.4.0
  testing/live/SortaKinda/manifest.toml
Labels: size-mid

#3010 Pet Nicknames v1.4.5.0
  stable/PetRenamer/manifest.toml
  testing/live/PetRenamer/images/icon.png
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#3009 [Testing] Collections v1.0.1.2
  testing/live/Collections/manifest.toml
Labels: size-large

#3008 Currency Tracker 1.3.3.0
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#3014 AdaptiveHud 1.0.8.1
  stable/AdaptiveHud/manifest.toml
Labels: size-small

#3015 Avant-Garde v0.1.1.0 (Stable)
  stable/AvantGarde/images/icon.png
  stable/AvantGarde/manifest.toml
Labels: move channel, size-small

#3016 Collections v1.0.1.2 - move to stable
  stable/Collections/images/icon.png
  stable/Collections/images/image1.png
  stable/Collections/images/image2.png
  stable/Collections/manifest.toml
Labels: move channel, size-small

#3017 [Testing] Nameplate Debuffs 1.1.0.0
  testing/live/NamePlateDebuffs/images/icon.png
  testing/live/NamePlateDebuffs/manifest.toml
Labels: move channel, size-small

#3018 [stable] Map Party Assist v1.0.2.0
  stable/MapPartyAssist/images/icon.png
  stable/MapPartyAssist/manifest.toml
Labels: move channel, size-small

#3020 Collections v1.0.1.3 (Bug fix)
  stable/Collections/manifest.toml
  testing/live/Collections/manifest.toml
Labels: size-small

#3019 Simple Tweaks 1.9.4.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#3023 Market Board 1.3.4
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#3022 Allagan Tools v1.6.2.1
  stable/InventoryTools/manifest.toml
Labels: size-small

#3012 SortaKinda v1.0.4.2
  testing/live/SortaKinda/manifest.toml
Labels: blocked, size-small

#3021 Collections v1.0.1.4
  stable/Collections/manifest.toml
  testing/live/Collections/manifest.toml
Labels: size-mid

#3011 Himbeertoni Raid Tool 1.4.2.0
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#3024 DutyTracker 1.0.1.8
  stable/DutyTracker/manifest.toml
Labels: size-small

#3025 Simple Tweaks 1.9.4.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#3028 SubmarineTracker 1.8.1.6
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3027 Himbeertoni Raid Tool 1.4.2.1
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#3026 SortaKinda v1.0.4.3
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#3032 TickTracker 1.2.0.0
  stable/TickTracker/manifest.toml
Labels: size-mid

#3031 Better in Blue 1.2.0.1
  stable/BetterInBlue/manifest.toml
Labels: size-small

#3030 Currency Tracker 1.3.3.1
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#3029 Tracky 1.3.4.7
  stable/TrackyTrack/manifest.toml
Labels: size-large

#3033 [Testing] Who's Talking 0.6.5.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#3034 SortaKinda 1.0.4.4
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#3035 Simple Tweaks 1.9.4.2
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#3036 SortaKinda v1.0.4.5
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#3037 IslandWorkshopSearch 0.0.0.1 move to stable
  stable/IslandWorkshopSearch/images/icon.png
  stable/IslandWorkshopSearch/images/image1.png
  stable/IslandWorkshopSearch/images/image2.png
  stable/IslandWorkshopSearch/images/image3.png
  stable/IslandWorkshopSearch/images/image4.png
  stable/IslandWorkshopSearch/manifest.toml
Labels: move channel, size-small

#3040 Currency Tracker 1.3.3.2
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#3046 CharacterPanelRefined 1.7.3.0
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small

#3045 DelvCD release 1.0.0.0
  stable/DelvCD/images/icon.png
  stable/DelvCD/manifest.toml
Labels: move channel, size-small

#3044 SortaKinda v1.0.4.5
  stable/SortaKinda/manifest.toml
Labels: size-small

#3042 Pet Nicknames v1.4.5.1
  stable/PetRenamer/manifest.toml
Labels: size-small

#3041 MonsterLootHunter 1.0.20.4
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#3039 ItemVendorLocation v2.5.0.0
  stable/ItemVendorLocation/manifest.toml
Labels: size-small

#3050 Pet Nicknames v1.4.5.2
  stable/PetRenamer/manifest.toml
Labels: size-small

#3049 CopyTranslated v1.1.3
  stable/CopyTranslated/manifest.toml
Labels: size-small

#3053 SortaKinda v1.0.4.6
  stable/SortaKinda/manifest.toml
Labels: size-small

#3052 Collections v1.0.1.5
  stable/Collections/manifest.toml
  testing/live/Collections/manifest.toml
Labels: size-small

#3051 Item Search 1.9.6.0
  stable/ItemSearchPlugin/manifest.toml
Labels: size-small

#3048 Currency Tracker 1.3.3.3
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#3056 Currency Tracker 1.3.3.4
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#3055 [Testing] Update Visibility (testing/live)
  testing/live/Visibility/manifest.toml
Labels: size-large

#3057 PriceInsight 2.7.0.0
  stable/PriceInsight/manifest.toml
Labels: size-small

#3043 VFXEditor v1.8.1.9
  stable/VFXEditor/manifest.toml
Labels: size-mid

#3038 Himbeertoni Raid Tool 1.5.0.0
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-mid

#3047 Simple Tweaks 1.9.5.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid, pending-rules-compliance

#3058 [Testing] OBSPlugin 1.0.3.1
  testing/live/OBSPlugin/images/icon.png
  testing/live/OBSPlugin/manifest.toml
Labels: move channel, size-small

#3059 Currency Tracker 1.3.1.5
  stable/CurrencyTracker/manifest.toml
Labels: size-small
