Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-09, with the labels that each got.

#2316 SortaKinda v0.0.2.0
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2319 [Testing] TrackyTrack 0.0.7.2
  testing/live/TrackyTrack/manifest.toml
Labels: size-small

#2318 [Testing] Lights, Camera, Action! v0.2.1.0
  testing/live/CameraLoader/manifest.toml
Labels: size-small

#2315 [Testing] Currency Tracker 1.1.2.1
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2251 [Testing] DelvCD Initial Release
  testing/live/DelvCD/images/icon.png
  testing/live/DelvCD/manifest.toml
Labels: new plugin, size-large

#2321 [Testing] Currency Tracker 1.1.2.2
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2320 Submarine Tracker 1.7.5.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2317 Pet Nicknames v1.2.1.1
  stable/PetRenamer/manifest.toml
  testing/live/PetRenamer/images/icon.png
  testing/live/PetRenamer/manifest.toml
Labels: size-large

#2314 VFXEditor v1.7.8.3
  stable/VFXEditor/manifest.toml
Labels: size-mid

#2322 Submarine Tracker 1.7.5.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2323 Update PositionalGuide (stable)
  stable/PositionalGuide/manifest.toml
Labels: size-small

#2324 [Testing] Tick Tracker 0.0.1.2
  testing/live/TickTracker/manifest.toml
Labels: size-small

#2325 [Testing] TrackyTrack 0.0.7.5
  testing/live/TrackyTrack/manifest.toml
Labels: size-small

#2326 DeepDungeonTracker 1.0.0.2
  stable/DeepDungeonTracker/manifest.toml
Labels: size-small

#2327 [Testing] Currency Tracker 1.1.2.3
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2328 [Testing] HUDManager 2.5.17.1
  testing/live/HUDManager/manifest.toml
Labels: size-small

#2329 [Testing] Who's Talking 0.6.2.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#2330 SubmarineTracker 1.7.5.3
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2332 DeepDungeonTracker 1.0.0.3
  stable/DeepDungeonTracker/manifest.toml
Labels: size-small

#2333 DeepDungeonDex 2.7.0
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#2334 [Testing] Tracky Track 0.0.7.6
  testing/live/TrackyTrack/manifest.toml
Labels: size-small

#2335 Allagan Tools v1.6.1.5
  stable/InventoryTools/manifest.toml
Labels: size-small

#2336 DeepDungeonDex 2.7.1
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#2337 SortaKinda v0.0.2.1
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2331 Update some more Anna plogons
  stable/NoSoliciting/manifest.toml
  stable/QuestMap/manifest.toml
Labels: size-large

#2338 [Testing] Tick Tracker 0.0.1.3
  testing/live/TickTracker/manifest.toml
Labels: size-small

#2339 [Testing] Lights, Camera, Action! v0.2.1.1
  testing/live/CameraLoader/manifest.toml
Labels: size-small

#2340 Submarine Tracker 1.7.6.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2272 [Testing] CopyTranslated 1.0.0
  testing/live/CopyTranslated/images/icon.png
  testing/live/CopyTranslated/manifest.toml
Labels: new plugin, size-mid

#2277 [Testing] XIVDupeFinder Initial Release 1.0.0.0
  stable/XIVDupeFinder/images/icon.png
  stable/XIVDupeFinder/images/image1.png
  stable/XIVDupeFinder/images/image2.png
  stable/XIVDupeFinder/manifest.toml
Labels: new plugin, size-large

#2348 PriceInsight 2.6.0.0
  stable/PriceInsight/manifest.toml
Labels: size-small

#2347 CopyTranslated v1.0.1 stable initial release
  stable/CopyTranslated/images/icon.png
  stable/CopyTranslated/manifest.toml
Labels: move channel, size-small

#2346 TrackyTrack 1.0.0.0 Stable Release
  stable/TrackyTrack/images/icon.png
  stable/TrackyTrack/manifest.toml
Labels: move channel, size-small

#2345 SortaKinda v1.0.0.0
  stable/SortaKinda/images/icon.png
  stable/SortaKinda/manifest.toml
Labels: move channel, size-small

#2343 WhichPatchWasThat 1.4.1.0
  stable/WhichPatchWasThat/manifest.toml
Labels: size-small

#2342 DeathRecap 1.10.3.0
  stable/DeathRecap/manifest.toml
Labels: size-small

#2349 XIVDupeFinder to 1.0.1.0 (stable)
  stable/XIVDupeFinder/manifest.toml
Labels: size-small

#2350 Submarine Tracker 1.7.6.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2351 GoodFriend v3.0.3.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#2352 PriceInsight 2.6.0.1
  stable/PriceInsight/manifest.toml
Labels: size-small

#2353 Combat Cursor Containment 1.0
  stable/CombatCursorContainment/images/icon.png
  stable/CombatCursorContainment/manifest.toml
  testing/live/CombatCursorContainment/images/icon.png
  testing/live/CombatCursorContainment/manifest.toml
Labels: move channel, size-small

#2354 [Testing] Pet Nicknames v1.2.2.0
  testing/live/PetRenamer/images/icon.png
  testing/live/PetRenamer/manifest.toml
Labels: move channel, size-mid

#2355 CopyTranslated v1.0.2
  stable/CopyTranslated/manifest.toml
  testing/live/CopyTranslated/images/icon.png
  testing/live/CopyTranslated/manifest.toml
Labels: size-small

#2356 WhoDidThat v1.3.0.0
  stable/WhoDidThat/manifest.toml
Labels: size-small

#2161 [Testing] Collections v1
  testing/live/Collections/images/icon.png
  testing/live/Collections/images/image1.png
  testing/live/Collections/images/image2.png
  testing/live/Collections/manifest.toml
Labels: new plugin, size-large

#2154 [Testing] Casexile 1.0.0.0
  testing/live/Casexile/images/icon.png
  testing/live/Casexile/manifest.toml
Labels: new plugin, code reviewed, size-mid

#2341 VFXEditor v1.7.8.4
  stable/VFXEditor/manifest.toml
Labels: size-mid

#2357 [Testing] Currency Tracker 1.2.0.0
  testing/live/CurrencyTracker/manifest.toml
Labels: size-large

#2358 [Testing] Pet Nicknames v1.2.2.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2359 DelvUI release 2.0.3.0
  stable/DelvUI/manifest.toml
Labels: size-small

#2360 [Testing] Pet Nicknames v1.2.2.2
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2361 [Testing] Currency Tracker 1.2.1.0
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2362 WhichPatchWasThat 1.5.0.0
  stable/WhichPatchWasThat/manifest.toml
Labels: size-mid

#2363 SortaKinda v1.0.0.1
  stable/SortaKinda/manifest.toml
Labels: size-small

#2364 [Testing] Pet Nicknames
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2369 [Testing] Currency Tracker 1.2.1.1
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2368 Allagan Tools v1.6.1.6
  stable/InventoryTools/manifest.toml
Labels: size-small

#2367 [Testing] Pet Nicknames v1.2.3.0
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#2366 DelvUI release 2.0.3.1
  stable/DelvUI/manifest.toml
Labels: size-small

#2365 DelvCD release 0.4.0.0
  testing/live/DelvCD/manifest.toml
Labels: size-large

#2378 [Testing] Distant Seas 1.0.0.1
  testing/live/DistantSeas/manifest.toml
Labels: size-large

#2377 Transfer CurrencyAlert
  stable/CurrencyAlert/manifest.toml
Labels: size-large

#2376 SonarPlugin v0.5.4.1
  stable/SonarPlugin/manifest.toml
Labels: size-small

#2374 SortaKinda v1.0.0.2
  stable/SortaKinda/manifest.toml
Labels: size-small

#2372 [Testing] Currency Tracker 1.2.1.2
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2371 Mappy v1.0.3.0
  stable/Mappy/manifest.toml
Labels: size-small

#2370 [Testing] Pet Nicknames v1.2.3.2
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2382 [Testing] Tick Tracker 0.0.2.0
  testing/live/TickTracker/manifest.toml
Labels: size-mid

#2384 [Testing] Tick Tracker 0.0.2.1
  testing/live/TickTracker/manifest.toml
Labels: size-small

#2387 Mappy v1.0.3.1
  stable/Mappy/manifest.toml
Labels: size-mid

#2386 [Testing] HUDManager 2.5.18.0
  testing/live/HUDManager/manifest.toml
Labels: size-small

#2388 BetterShadows 1.2.0
  stable/BetterShadows/manifest.toml
Labels: size-small

#2389 DelvCD release 0.4.0.1
  testing/live/DelvCD/manifest.toml
Labels: size-small

#2393 [Testing] Tick Tracker 0.0.2.2
  testing/live/TickTracker/manifest.toml
Labels: size-small

#2391 SubmarineTracker 1.6.4.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2394 [Testing] Currency Tracker 1.2.3.1
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2398 [stable] Currency Tracker 1.2.3.1
  stable/CurrencyTracker/images/icon.png
  stable/CurrencyTracker/manifest.toml
Labels: move channel, size-small

#2399 EurekaLinker 1.5.0.0
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-mid

#2380 [Testing] Pet Nicknames v1.3.0.0
  testing/live/PetRenamer/manifest.toml
Labels: size-large

#2395 SubmarineTracker 1.7.7.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2403 [Stable] UsedName 0.8.3.5
  stable/UsedName/manifest.toml
Labels: size-small

#2404 EurekaLinker 1.5.0.1
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#2405 SubmarineTracker 1.7.7.7
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2379 VFXEditor v1.7.9.0
  stable/VFXEditor/manifest.toml
Labels: size-large

#2407 TrackyTrack 1.0.0.2
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2409 Pet Nicknames v1.3.0.0
  stable/PetRenamer/manifest.toml
Labels: size-large

#2408 SubmarineTracker 1.8.0.0
  stable/SubmarineTracker/manifest.toml
Labels: size-large

#2406 [Testing] Currency Tracker 1.2.3.3
  testing/live/CurrencyTracker/manifest.toml
Labels: size-large
