Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-06, with the labels that each got.

#1950 [Testing] TextToTalk 1.26.1
  testing/live/TextToTalk/manifest.toml
Labels: size-small

#1953 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small

#1952 Team Fortress Fantasy 1.1.3.0
  stable/Tf2Hud/manifest.toml
Labels: size-small

#1951 [Testing] TextToTalk v1.26.2
  testing/live/TextToTalk/manifest.toml
Labels: size-small

#1949 [Release] Bozja Buddy 1.0.0.0
  stable/BozjaBuddy/images/icon.png
  stable/BozjaBuddy/manifest.toml
Labels: move channel, size-small

#1956 GatherBuddy 3.2.4.2
  stable/GatherBuddy/manifest.toml
Labels: size-small

#1955 SubmarineTracker 1.5.1.3
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1957 Himbeertoni Raid Tool 1.3.0.5
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#1959 SubmarineTracker 1.5.1.4
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1963 VFXEditor 1.7.5.3
  stable/VFXEditor/manifest.toml
Labels: size-small

#1962 JobBars v1.2.3.7
  stable/JobBars/manifest.toml
Labels: size-small

#1960 DutyTracker 1.0.1.4
  stable/DutyTracker/manifest.toml
Labels: size-small

#1964 MemoryMarker v1.0.0.5
  stable/MemoryMarker/manifest.toml
Labels: size-small

#1965 Himbeertoni Raid Tool 1.3.1.1
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#1966 [Testing] Collector's Anxiety 0.0.6
  testing/live/CollectorsAnxiety/manifest.toml
Labels: size-small

#1968 Allagan Tools v1.5.0.5
  stable/InventoryTools/manifest.toml
Labels: size-small

#1970 Allagan Tools v1.5.0.6
  stable/InventoryTools/manifest.toml
Labels: size-small

#1969 WorkshopOptimizerPlugin 0.2.7.0
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-small

#1971 [Testing] HUDManager v2.5.14
  testing/live/HUDManager/manifest.toml
Labels: size-mid

#1972 [Testing] GoodFriend v2.0.0.0
  testing/live/GoodFriend/manifest.toml
Labels: size-mid

#1973 AutoMammet 1.4.1.1
  stable/AutoMammet/manifest.toml
Labels: size-small

#1974 [Testing] Beachcomber v1.2.2.0
  testing/live/Beachcomber/manifest.toml
Labels: size-small

#1975 Hunty 1.1.0.1
  stable/Hunty/manifest.toml
Labels: size-small

#1976 PartyPlanner v1.5.3
  stable/PartyPlanner/manifest.toml
Labels: size-small

#1977 [Testing] Update FCNameColor to 3.0.2.2
  testing/live/FCNameColor/manifest.toml
Labels: size-small

#1981 Update FCNameColor to 3.0.2.2
  stable/FCNameColor/manifest.toml
Labels: size-small

#1980 Himbeertoni Raid Tool 1.3.1.2
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#1978 Bozja Buddy 1.0.0.2
  stable/BozjaBuddy/manifest.toml
Labels: size-small

#1958 [Testing] FFXIV RP Event Calendar (Initial Version)
  testing/live/FFXIVRPCalendarPlugin/images/icon.png
  testing/live/FFXIVRPCalendarPlugin/manifest.toml
Labels: new plugin, code reviewed, size-mid

#1982 AutoMammet 1.4.1.2
  stable/AutoMammet/manifest.toml
Labels: size-small

#1983 PingPlugin v2.5.3
  stable/PingPlugin/manifest.toml
Labels: size-small

#1984 EasyEyes v1.2.2.3
  stable/EasyEyes/manifest.toml
Labels: size-small

#1994 [Testing] Beachcomber v1.2.2.2
  testing/live/Beachcomber/manifest.toml
Labels: size-small

#1992 EurekaHelper 1.6.1.7
  stable/EurekaHelper/images/icon.png
  stable/EurekaHelper/manifest.toml
Labels: size-small

#1991 Team Fortress Fantasy 1.1.4.0
  stable/Tf2Hud/manifest.toml
Labels: size-small

#1988 TargetLines 1.2.5
  stable/TargetLines/manifest.toml
Labels: size-small

#1990 Simple Tweaks 1.8.7.3
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#1993 GoodFriend v2.0.1.0
  stable/GoodFriend/manifest.toml
Labels: size-mid

#1989 hunthelper-v1.0.0.6
  stable/HuntHelper/manifest.toml
Labels: size-small

#1999 A Realm Recorded v1.0.0.0
  stable/ARealmRecorded/images/icon.png
  stable/ARealmRecorded/manifest.toml
Labels: move channel, size-small

#1996 Wholist v1.3.1.0
  stable/Wholist/manifest.toml
Labels: size-small

#688 SonarPlugin v0.5.2.6
  stable/SonarPlugin/images/icon.png
  stable/SonarPlugin/images/image1.png
  stable/SonarPlugin/images/image2.png
  stable/SonarPlugin/images/image3.png
  stable/SonarPlugin/images/image4.png
  stable/SonarPlugin/images/image5.png
  stable/SonarPlugin/images/logo.png
  stable/SonarPlugin/manifest.toml
Labels: new plugin, size-mid

#1986 DiscordBridge 1.4.3
  stable/Dalamud.DiscordBridge/manifest.toml
Labels: size-small

#1987 [Testing] DailyDuty v4.0.2.0
  testing/live/DailyDuty/manifest.toml
Labels: size-mid

#1997 TargetLines 1.2.6
  stable/TargetLines/manifest.toml
Labels: size-small

#1998 GoodFriend v2.0.3.0
  stable/GoodFriend/manifest.toml
Labels: size-mid

#1995 XivInstantMessenger 1.3.0.3
  stable/Messenger/images/icon.png
  stable/Messenger/manifest.toml
Labels: size-mid

#2000 SubmarineTracker 1.6.0.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2005 SubmarineTracker 1.6.0.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2002 Allagan Tools v1.5.0.7
  stable/InventoryTools/manifest.toml
Labels: size-small

#2006 [Stable] Moving G4E Ukr Chat Support to stable
  stable/G4EUkrChatSupport/images/.gitkeep
  stable/G4EUkrChatSupport/images/icon.png
  stable/G4EUkrChatSupport/manifest.toml
Labels: move channel, size-small

#2011 GoodFriend v2.0.4.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#2010 DelvUI release 1.7.1.3
  stable/DelvUI/manifest.toml
Labels: size-small

#2009 [Testing] DailyDuty v4.0.2.1
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#2008 Orchestrion 2.0.0.2 -> 2.0.0.3
  stable/orchestrion/manifest.toml
Labels: size-small

#2007 SubmarineTracker 1.6.0.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#1961 Market Board 1.3.0
  stable/MarketBoardPlugin/images/icon.png
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#2012 Allagan Tools v1.5.0.8
  stable/InventoryTools/manifest.toml
Labels: size-small

#2013 [Testing] HUD Manager v2.5.15
  testing/live/HUDManager/manifest.toml
Labels: size-small

#2014 SubmarineTracker 1.6.0.3
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2015 DailyDuty v4.0.2.1
  stable/DailyDuty/manifest.toml
Labels: size-mid

#2016 EurekaLinker 1.4.0.5
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#2017 TargetLines 1.2.7
  stable/TargetLines/manifest.toml
Labels: size-small

#2018 Allagan Tools v1.5.0.9
  stable/InventoryTools/manifest.toml
Labels: size-small

#2019 GoodFriend v2.0.5.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#2020 SubmarineTracker 1.6.1.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2022 Update Text Box Styler to 1.1.6
  stable/TextBoxStyler/manifest.toml
Labels: size-small

#2021 Hunty 1.2.0.0
  stable/Hunty/manifest.toml
Labels: size-small

#2025 Bozja Buddy 1.0.0.3
  stable/BozjaBuddy/manifest.toml
Labels: size-small

#2032 LogogramHelper 0.0.2.1
  stable/LogogramHelper/manifest.toml
Labels: size-small

#2031 Eureka Linker 1.4.0.6
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#2029 DailyDuty v4.0.2.2
  stable/DailyDuty/manifest.toml
Labels: size-small

#2028 Allagan Tools v1.5.0.10
  stable/InventoryTools/manifest.toml
Labels: size-small

#2027 EurekaHelper 1.5.1.8
  stable/EurekaHelper/manifest.toml
Labels: size-small

#2030 SubmarineTracker 1.6.2.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2024 VFXEditor v1.7.6.0
  stable/VFXEditor/manifest.toml
Labels: size-large

#2034 [Testing] Who's Talking 0.2.0.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#1773 [Testing] Chatter
  testing/live/Chatter/images/icon.png
  testing/live/Chatter/manifest.toml
Labels: new plugin, code reviewed, size-large

#2036 Tilted v3.1.0
  testing/live/Tilted/manifest.toml
Labels: size-small

#2033 [Testing] Mappy v1.0.0.0
  testing/live/Mappy/manifest.toml
Labels: new plugin, size-large

#2038 [Testing] rtyping 0.0.2.0
  testing/live/rtyping/manifest.toml
Labels: size-small

#2026 [Testing] NoTankYou v6.0.0.0
  testing/live/NoTankYou/manifest.toml
Labels: size-large

#2040 [Testing] Mappy v1.0.0.1
  testing/live/Mappy/manifest.toml
Labels: size-mid

#2039 VFXEditor 1.7.7.0
  stable/VFXEditor/manifest.toml
Labels: size-large

#2041 DelvUI release 1.7.1.4
  stable/DelvUI/manifest.toml
Labels: size-small

#2042 [Testing] Mappy v1.0.0.2
  testing/live/Mappy/manifest.toml
Labels: size-small

#2035 WorkshopOptimizerPlugin 0.2.7.1
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-small

#2046 Neko Fans 1.3.0
  stable/Neko/manifest.toml
Labels: size-small

#2044 [Testing] Mappy v1.0.0.3
  testing/live/Mappy/manifest.toml
Labels: size-small

#2043 SubmarineTracker 1.7.0.0
  stable/SubmarineTracker/manifest.toml
Labels: size-large

#2047 DelvUI release 1.7.1.5
  stable/DelvUI/manifest.toml
Labels: size-small

#2050 Allagan Tools v1.5.0.11
  stable/InventoryTools/manifest.toml
Labels: size-small

#2048 [Testing] NoTankYou v6.0.0.1
  testing/live/NoTankYou/manifest.toml
Labels: size-mid

#2056 SubmarineTracker 1,7.0.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2054 PennyPincher v1.7.0.0
  stable/PennyPincher/images/icon.png
  stable/PennyPincher/manifest.toml
Labels: size-small

#2052 [Testing] RPBlurb v1.0.2.0 - Attempt to fix style bleeding issue
  testing/live/RPBlurb/manifest.toml
Labels: size-mid
