Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-07, with the labels that each got.

#2058 NoTankYou v6.0.0.1
  stable/NoTankYou/manifest.toml
Labels: size-large

#2049 [Testing] FantasyPlayer v2.1.1.2
  testing/live/FantasyPlayer/manifest.toml
Labels: size-large

#2053 ChillFrames v2.0.0.0
  stable/ChillFrames/manifest.toml
Labels: size-mid

#2055 [Testing] Mappy v1.0.0.4
  testing/live/Mappy/manifest.toml
Labels: size-mid

#2059 NoTankYou v6.0.0.2
  stable/NoTankYou/manifest.toml
Labels: size-small

#2057 [Testing] DailyDuty v4.0.3.0
  testing/live/DailyDuty/manifest.toml
Labels: size-large

#2060 ChillFrames 2.0.0.1
  stable/ChillFrames/manifest.toml
Labels: size-small

#2061 Simple Tweaks 1.8.8.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#2062 RoleplayProfiles 0.2.0.0
  stable/RoleplayProfiles/images/icon.png
  stable/RoleplayProfiles/manifest.toml
Labels: size-small

#2063 [Testing] Update Visibility (testing/live)
  testing/live/Visibility/manifest.toml
Labels: size-mid

#2064 [Testing] Mappy v1.0.0.5
  testing/live/Mappy/manifest.toml
Labels: size-small

#2065 Honorific 1.1.0.0
  stable/Honorific/manifest.toml
Labels: size-small

#2066 Simple Tweaks 1.8.8.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#2068 [Testing] Mappy v1.0.0.6
  testing/live/Mappy/manifest.toml
Labels: size-small

#2069 Simple Tweaks 1.8.8.2
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#2071 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-small

#2072 [Testing] DailyDuty v4.0.3.1
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#2070 Himbeertoni Raid Tool 1.3.2.0
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-mid

#2067 [Testing] Allagan Tools v1.6.0.0
  testing/live/InventoryTools/manifest.toml
Labels: size-large

#2074 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-mid

#2075 ItemVendorLocation v2.3.0.0
  stable/ItemVendorLocation/manifest.toml
Labels: size-mid

#2076 Hunty 1.2.1.0
  stable/Hunty/manifest.toml
Labels: size-small

#2078 [Testing] Allagan Tools v1.6.0.1
  testing/live/InventoryTools/manifest.toml
Labels: size-small

#2079 [Testing] Fantasy Player v2.1.1.3
  testing/live/FantasyPlayer/manifest.toml
Labels: size-small

#2080 [Testing] Mappy v1.0.0.7
  testing/live/Mappy/manifest.toml
Labels: size-small

#2086 NoTankYou v6.0.0.3
  stable/NoTankYou/manifest.toml
Labels: size-small

#2085 Submarine Tracker 1.7.1.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2081 Hunty 1.2.1.1
  stable/Hunty/manifest.toml
Labels: size-small

#2089 Submarine Tracker 1.7.1.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2090 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small

#2091 [Testing] Allagan Tools v1.6.0.2
  testing/live/InventoryTools/manifest.toml
Labels: size-small

#2092 [Testing] UsedName 0.8.3.0
  testing/live/UsedName/manifest.toml
Labels: size-small

#2094 VFXEditor v1.7.7.1
  stable/VFXEditor/manifest.toml
Labels: size-large

#2083 DailyDuty v4.0.3.2
  stable/DailyDuty/manifest.toml
Labels: size-large

#2096 VFXEditor 1.7.7.2
  stable/VFXEditor/manifest.toml
Labels: size-small

#2097 NoTankYou 6.0.0.4
  stable/NoTankYou/manifest.toml
Labels: size-small

#2093 [Testing] Mappy v1.0.0.8
  testing/live/Mappy/manifest.toml
Labels: size-large

#2098 [Testing] TextToTalk v1.26.3
  testing/live/TextToTalk/manifest.toml
Labels: size-small

#2103 BetterPlaytime 1.3.1.0
  stable/BetterPlaytime/manifest.toml
Labels: size-small

#2100 ChillFrames v2.0.0.2
  stable/ChillFrames/manifest.toml
Labels: size-small

#2099 [Testing] Bozja Buddy 1.1.0.1
  testing/live/BozjaBuddy/manifest.toml
Labels: size-large

#2102 SubmarineTracker 1.7.2.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2101 [Testing] Allagan Tools v1.6.0.3
  testing/live/InventoryTools/manifest.toml
Labels: size-large

#2107 LogogramHelper 0.0.2.2
  stable/LogogramHelper/manifest.toml
Labels: size-small

#2109 [Testing] Bozja Buddy 1.1.1.0
  testing/live/BozjaBuddy/manifest.toml
Labels: size-small

#2110 NoTankYou v6.0.0.5
  stable/NoTankYou/manifest.toml
Labels: size-small

#2112 Eureka Linker 1.4.1.0
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#2104 [Testing] Mappy v1.0.0.9
  testing/live/Mappy/manifest.toml
Labels: size-mid

#2105 Submarine Tracker 1.7.2.1
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2106 [Testing] Allagan Tools v1.6.0.4
  testing/live/InventoryTools/manifest.toml
Labels: size-mid

#2108 BlueMageHelper 2.0.7.0
  stable/BlueMageHelper/manifest.toml
Labels: size-mid

#2111 BetterPlaytime 1.4.0.0
  stable/BetterPlaytime/manifest.toml
Labels: size-mid

#2114 SubmarineTracker 1.7.2.3
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2113 [TESTING] XIVDeck 0.3.14
  testing/live/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-mid

#2117 [Testing] Who's Talking 0.2.1.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#2116 SonarPlugin v0.5.2.8
  stable/SonarPlugin/manifest.toml
Labels: size-mid

#2118 Allagan Tools v1.6.1.0
  stable/InventoryTools/manifest.toml
Labels: size-large

#2119 DeathRecap 1.10.2.2
  stable/DeathRecap/manifest.toml
Labels: size-small

#2125 Submarine Tracker 1.7.2.4
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2124 Wholist v1.3.1.1
  stable/Wholist/manifest.toml
Labels: size-small

#2121 DailyDuty v4.0.3.3
  stable/DailyDuty/manifest.toml
Labels: size-small

#2120 Mappy v1.0.1.0
  stable/Mappy/images/icon.png
  stable/Mappy/manifest.toml
Labels: move channel, size-small

#2122 Bozja Buddy 1.1.2.0
  testing/live/BozjaBuddy/manifest.toml
Labels: size-mid

#2123 GoodFriend v2.0.6.0
  stable/GoodFriend/manifest.toml
Labels: size-large

#2127 Allagan Tools v1.6.1.1
  stable/InventoryTools/manifest.toml
Labels: size-small

#2130 SubmarineTracker 1.7.2.5
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2128 TitleRoulette 1.3
  stable/TitleRoulette/manifest.toml
Labels: size-small

#2129 Move CollectableCalculator to stable
  stable/CollectableCalculator/images/icon.png
  stable/CollectableCalculator/manifest.toml
Labels: move channel, size-small

#2134 DeathRecap 1.10.2.3
  stable/DeathRecap/manifest.toml
Labels: size-small

#2133 CollectableCalculator 1.2
  stable/CollectableCalculator/manifest.toml
Labels: size-small

#2132 BlueMageHelper 3.0.0.0
  stable/BlueMageHelper/manifest.toml
Labels: size-mid

#2131 [Testing] Bozja Buddy 1.1.3.0
  testing/live/BozjaBuddy/manifest.toml
Labels: size-mid

#2135 Adopt WPP
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#2140 Update Namingway to 1.1.10
  stable/Namingway/manifest.toml
Labels: size-small

#2139 Update manifest repo urls for CollectableCalculator/TitleRoulette
  stable/CollectableCalculator/manifest.toml
  stable/TitleRoulette/manifest.toml
Labels: size-small

#2137 Allagan Tools v1.6.1.2
  stable/InventoryTools/manifest.toml
Labels: size-small

#2138 Player Tags v1.9.5
  stable/PlayerTags/manifest.toml
Labels: size-large

#2141 Allagan Tools v1.6.1.3
  stable/InventoryTools/manifest.toml
Labels: size-small

#2142 TextToTalk v1.24.2.1
  stable/TextToTalk/manifest.toml
Labels: size-small

#2143 GatherBuddy 3.2.5.0.
  stable/GatherBuddy/manifest.toml
Labels: size-small

#2144 Mappy v1.0.1.1
  stable/Mappy/manifest.toml
Labels: size-small

#2147 JobBars v1.2.3.8
  stable/JobBars/manifest.toml
Labels: size-small

#2146 HuntHelper 1.0.0.7
  stable/HuntHelper/manifest.toml
Labels: size-small

#2148 VFXEditor v1.7.7.3
  stable/VFXEditor/manifest.toml
Labels: size-mid

#2145 [Stable] UsedName 0.8.3.3
  stable/UsedName/manifest.toml
Labels: size-small

#2153 SubmarineTracker 1.7.2.6
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2152 GoodFriend v2.0.7.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#2150 Allagan Tools v1.6.1.4
  stable/InventoryTools/manifest.toml
Labels: size-small

#2160 Himbeertoni Raid Tool 1.3.3.1
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#2159 Simple Tweaks 1.8.9.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-large

#2158 NoTankYou v6.0.0.6
  stable/NoTankYou/manifest.toml
Labels: size-small

#2157 Mappy v1.0.1.2
  stable/Mappy/manifest.toml
Labels: size-small

#2156 [Testing] CameraLoader -> Lights, Camera, Action! v0.2.0.0
  testing/live/CameraLoader/images/icon.png
  testing/live/CameraLoader/manifest.toml
Labels: size-mid

#2149 [Testing] Bozja Buddy 1.1.4.1
  testing/live/BozjaBuddy/manifest.toml
Labels: size-large

#2023 Add NICEDamage plugin
  testing/live/NICEDamage/images/icon.png
  testing/live/NICEDamage/manifest.toml
Labels: new plugin, size-small

#1967 [Testing] Magitek Stratagem - Tobii Game Integration Plugin v0.1.0.0
  testing/live/MagitekStratagem/images/icon.png
  testing/live/MagitekStratagem/manifest.toml
Labels: new plugin, size-large

#2037 [Testing] "Who did that?"
  testing/live/WhoDidThat/images/icon.png
  testing/live/WhoDidThat/manifest.toml
Labels: new plugin, size-large

#2084 PetNicknames
  testing/live/PetRenamer/images/icon.png
  testing/live/PetRenamer/manifest.toml
Labels: new plugin, size-large

#2095 [Testing] Mount Collectioner 1.0.0.0
  testing/live/MountCollectioner/images/icon.png
  testing/live/MountCollectioner/manifest.toml
Labels: new plugin, size-large

#2073 Update StackSellPrice (stable)
  stable/StackSellPrice/manifest.toml
Labels: size-small

#2162 Simple Tweaks 1.8.9.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#2163 Mappy v1.0.1.3
  stable/Mappy/manifest.toml
Labels: size-small

#2164 PetRenamer 0.2.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2165 SubmarineTracker 1.7.3.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2166 Bozja Buddy 1.1.4.2
  stable/BozjaBuddy/manifest.toml
Labels: size-large

#2169 SubmarineTracker 1.0.7.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2170 [Testing] WhoDidThat 1.0.0
  testing/live/WhoDidThat/manifest.toml
Labels: size-small

#2171 [Testing] PetRenamer 0.2.2
  testing/live/PetRenamer/manifest.toml
Labels: size-small
