Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-03, with the labels that each got.

#1239 [Testing] EmoteLog 0.1.0.0
  testing/live/EmoteLog/images/icon.png
  testing/live/EmoteLog/manifest.toml
Labels: new plugin, code reviewed

#1254 [Testing] BozjaBuddy
  testing/live/BozjaBuddy/images/icon.png
  testing/live/BozjaBuddy/manifest.toml
Labels: new plugin, code reviewed

#1280 [Testing] ClarityInChaos v1.1.2.0
  testing/live/ClarityInChaos/images/icon.png
  testing/live/ClarityInChaos/manifest.toml
Labels: new plugin, code reviewed

#1285 [Testing] Fungah
  testing/live/Fungah/images/icon.png
  testing/live/Fungah/images/image1.png
  testing/live/Fungah/images/image2.png
  testing/live/Fungah/manifest.toml
Labels: new plugin

#1523 [Testing] DailyDuty v4.0.0.0
  testing/live/DailyDuty/manifest.toml
Labels: big
