Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-10, with the labels that each got.

#2392 [Testing] PlayerTrack
  testing/live/PlayerTrack/images/icon.png
  testing/live/PlayerTrack/manifest.toml
Labels: move channel, size-large

#2419 Update Wotsit to 1.0.4.0
  stable/Dalamud.FindAnything/manifest.toml
Labels: size-mid

#2411 [API9] SubmarineTracker 1.8.0.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2420 Browsingway 1.5.5.0
  stable/Browsingway/manifest.toml
Labels: size-small

#2445 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small

#2435 Combat Cursor Containment 1.0.2.0
  stable/CombatCursorContainment/manifest.toml
Labels: size-small

#2431 [Testing] rtyping 0.0.3.0
  testing/live/rtyping/manifest.toml
Labels: size-small

#2428 [API9] Hunty, BlueMageHelper, Fader ........
  stable/BetterPlaytime/manifest.toml
  stable/BlueMageHelper/manifest.toml
  stable/EurekaTrackerAutoPopper/manifest.toml
  stable/FaderPlugin/manifest.toml
  stable/Hunty/manifest.toml
  stable/MBHistory/manifest.toml
  stable/ReadyCheckHelper/manifest.toml
Labels: size-small

#2427 XIVLogger adopt and API9
  stable/XIVLogger/manifest.toml
Labels: size-small

#2426 FlyTextFilter 4.1.4.1
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#2425 Updating DeepDungeonDex
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#2465 ZodiacBuddy v0.2.0.0
  stable/ZodiacBuddy/manifest.toml
Labels: size-small

#2464 Wholist 1.3.1.2
  stable/Wholist/manifest.toml
Labels: size-small

#2462 EzWondrousTails v2.3.0.0
  stable/WondrousTailsSolver/images/icon.png
  stable/WondrousTailsSolver/manifest.toml
Labels: size-small

#2461 GoodFriend v3.0.3.1
  stable/GoodFriend/manifest.toml
Labels: size-small

#2459 Accountant 1.4.0.0
  stable/Accountant/manifest.toml
Labels: size-small

#2458 SubmarineTracker 1.8.0.4
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2457 EzFauxHollows v1.3.0.0
  stable/FauxHollowsSolver/images/icon.png
  stable/FauxHollowsSolver/manifest.toml
Labels: size-small

#2456 API 9 Updates for most Caraxi Plugins
  stable/AdventurerInNeed/manifest.toml
  stable/FPSPlugin/manifest.toml
  stable/Honorific/manifest.toml
  stable/ItemSearchPlugin/manifest.toml
  stable/MacroChain/manifest.toml
Labels: size-small

#2455 DelvUI release 2.1.0.0
  stable/DelvUI/manifest.toml
Labels: size-small

#2454 EzMiniCactpot v1.3.0.0
  stable/MiniCactpotSolver/images/icon.png
  stable/MiniCactpotSolver/manifest.toml
Labels: size-small

#2453 TPie release 1.8.0.0
  stable/TPie/manifest.toml
Labels: size-small

#2452 ActionTimeline release 1.3.0.0
  stable/ActionTimeline/manifest.toml
Labels: size-small

#2451 NOTED release 1.2.0.0
  stable/NOTED/manifest.toml
Labels: size-small

#2450 DelvCD release 0.5.0.0
  testing/live/DelvCD/manifest.toml
Labels: size-small

#2441 [API9] HarpHero v1.9
  stable/HarpHero/manifest.toml
Labels: size-small

#2433 Better in Blue 1.1.0.1
  stable/BetterInBlue/images/icon.png
  stable/BetterInBlue/manifest.toml
Labels: move channel, size-small

#2438 SelfCare v0.1.1
  testing/live/SelfCare/images/icon.png
  testing/live/SelfCare/manifest.toml
Labels: size-small

#2439 [API9] PatMe v1.9
  stable/PatMe/manifest.toml
Labels: size-small

#2448 Distant Seas 1.0.0.2
  stable/DistantSeas/images/icon.png
  stable/DistantSeas/manifest.toml
Labels: move channel, size-small

#2463 Pixel Perfect 3.0.4.0
  stable/PixelPerfect/images/icon.png
  stable/PixelPerfect/images/image1.png
  stable/PixelPerfect/images/image2.png
  stable/PixelPerfect/manifest.toml
Labels: size-small

#2470 Kapture 1.7.0.0
  stable/Kapture/manifest.toml
Labels: size-small

#2471 SillyChat 1.7.0.0
  stable/SillyChat/manifest.toml
Labels: size-small

#2473 PriceInsight 2.6.1.0
  stable/PriceInsight/manifest.toml
Labels: size-small

#2475 EnemyListDebuffs 0.3.9.0
  stable/EnemyListDebuffs/manifest.toml
Labels: size-small

#2424 XIVDeck 0.3.16
  stable/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-small

#2413 [API9] OBSPlugin 1.0.2.6
  stable/OBSPlugin/manifest.toml
Labels: size-small

#2414 Update of most of my plugins for 6.5
  stable/EnmityHp/manifest.toml
  stable/JustBackup/manifest.toml
  stable/Messenger/manifest.toml
  stable/Mini/manifest.toml
  stable/NotificationMaster/manifest.toml
  stable/Weatherman/manifest.toml
Labels: size-small

#2442 Where am I again? v1.0.0.0
  stable/WhereAmIAgain/manifest.toml
Labels: size-mid

#2443 Himbeertoni Raid Tool 1.3.4.0
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-mid

#2460 ChatAlerts 2.0.3.0
  stable/ChatAlerts/manifest.toml
Labels: size-mid

#2474 RezPls 1.2.6.0
  stable/RezPls/manifest.toml
Labels: size-mid

#2472 CharacterPanelRefined 1.7.2.0
  stable/CharacterPanelRefined/manifest.toml
Labels: size-mid

#2469 NeatNoter 2.5.0.0
  stable/NeatNoter/manifest.toml
Labels: size-mid

#2468 PriceCheck 2.6.0.0
  stable/PriceCheck/manifest.toml
Labels: size-large

#2466 Death Recap 1.11.0.0
  stable/DeathRecap/manifest.toml
Labels: size-mid

#2447 Update all Anna plogons
  stable/BetterPartyFinder/manifest.toml
  stable/BurntToast/manifest.toml
  stable/ChatTwo/manifest.toml
  stable/ExpandedSearchInfo/manifest.toml
  stable/ExtraChat/manifest.toml
  stable/Glamaholic/manifest.toml
  stable/Globetrotter/manifest.toml
  stable/Namingway/manifest.toml
  stable/NoSoliciting/manifest.toml
  stable/OrangeGuidanceTomestone/manifest.toml
  stable/PeepingTom/manifest.toml
  stable/QuestMap/manifest.toml
  stable/RemotePartyFinder/manifest.toml
  stable/SoundFilter/manifest.toml
  stable/TextBoxStyler/manifest.toml
  stable/TheGreatSeparator/manifest.toml
  stable/TheHeartOfTheParty/manifest.toml
  stable/Tourist/manifest.toml
  stable/XIVChat/manifest.toml
Labels: size-large

#2432 cl_showpos 1.1.0.0
  stable/cl_showpos/manifest.toml
Labels: size-mid

#2430 ReSanctuary 1.3.0.0
  stable/ReSanctuary/manifest.toml
  testing/live/ReSanctuary/images/icon.png
  testing/live/ReSanctuary/manifest.toml
Labels: size-large

#2416 WaymarkPresets API9
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-large

#2476 A Realm Recorded v1.0.0.1
  stable/ARealmRecorded/manifest.toml
Labels: size-small

#2477 [API9] MapLinker 1.1.7.4
  stable/MapLinker/manifest.toml
Labels: size-small

#2478 [API9] Bump OBSPlugin dll to 1.0.2.6
  stable/OBSPlugin/manifest.toml
Labels: size-small

#2483 [Testing] HUDManager 2.5.18.1
  testing/live/HUDManager/manifest.toml
Labels: size-small

#2479 GatherBuddy 3.3.0.0
  stable/GatherBuddy/manifest.toml
Labels: size-large

#2482 Hit it, Joe! (Formerly TF2-ish Critical Hits Plugin) 3.4.1.0
  stable/Tf2CriticalHitsPlugin/manifest.toml
Labels: size-small

#2484 Congratulations 1.2.3.0
  stable/Congratulations/manifest.toml
Labels: size-small

#2449 SortaKinda v1.0.1.0
  stable/SortaKinda/manifest.toml
Labels: size-small

#2423 NoTankYou v6.0.1.0
  stable/NoTankYou/manifest.toml
Labels: size-small

#2436 DailyDuty v4.0.5.0
  stable/DailyDuty/manifest.toml
Labels: size-small

#2421 CurrencyAlert v1.0.0.0
  stable/CurrencyAlert/manifest.toml
Labels: size-large

#2491 [Testing] VanillaHotbarExtender 1.1.0
  testing/live/VanillaHotbarExtender/manifest.toml
Labels: size-small

#2489 TargetFurniture 1.0.1.8
  stable/TargetFurniture/manifest.toml
Labels: size-small

#2488 WhichPatchWasThat 1.6.0.0
  stable/WhichPatchWasThat/manifest.toml
Labels: size-small

#2487 [Testing] Tick Tracker 0.0.2.3
  testing/live/TickTracker/manifest.toml
Labels: size-mid

#2486 QoL Bar v2.3.2.2
  stable/QoLBar/manifest.toml
Labels: size-small

#2485 CopyTranslated v1.0.3
  stable/CopyTranslated/manifest.toml
Labels: size-small

#2437 MemoryMarker v1.1.0.0
  stable/MemoryMarker/manifest.toml
Labels: size-mid

#2481 Simple Tweaks 1.9.0.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-large

#2495 TitleRoulette 2.0
  stable/TitleRoulette/manifest.toml
Labels: size-mid

#2493 WinTitle v1.0.6.0
  stable/WinTitle/manifest.toml
Labels: size-small

#2492 Pet Nicknames 1.3.1.0
  stable/PetRenamer/manifest.toml
Labels: size-mid

#2490 [Testing] Currency Tracker 1.2.3.4
  testing/live/CurrencyTracker/manifest.toml
Labels: blocked, size-small

#2418 [API9] SonarPlugin v0.6.0.0
  stable/SonarPlugin/manifest.toml
Labels: size-small

#2415 CollectableCalculator 2.0
  stable/CollectableCalculator/manifest.toml
Labels: size-small

#2496 6.5 Doorbell
  stable/Doorbell/manifest.toml
Labels: size-small

#2511 NekoFans 1.3.1
  stable/Neko/manifest.toml
Labels: size-small

#2510 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-small

#2507 PriceInsight 2.6.1.1
  stable/PriceInsight/manifest.toml
Labels: size-small

#2504 [Testing] BetterMountRoulette 1.3.0.14
  testing/live/BetterMountRoulette/manifest.toml
Labels: size-small

#2499 Market Board 1.3.1
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#2506 [API9] BetterShadows 1.2.2.0
  stable/BetterShadows/manifest.toml
Labels: size-small

#2498 Player Tags v1.10
  stable/PlayerTags/manifest.toml
Labels: size-small

#2512 TwitchXIV update for 6.5
  stable/TwitchXIV/images/icon.png
  stable/TwitchXIV/manifest.toml
  testing/live/TwitchXIV/manifest.toml
Labels: move channel, size-small

#2509 [API9] TrackyTrack 1.0.0.4
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2497 Allagan Tools v1.6.1.7
  stable/InventoryTools/manifest.toml
Labels: size-mid

#2503 PlayerTrack V3.1.0
  testing/live/PlayerTrack/manifest.toml
Labels: size-large

#2501 EngageTimer v2.2.6.0
  stable/EngageTimer/manifest.toml
Labels: size-large

#2502 [stable] Currency Tracker 1.2.3.4
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#2505 [API9] HybridCamera 1.2.0.0
  stable/HybridCamera/manifest.toml
Labels: size-large

#2515 CrossUp v1.0.1.0
  stable/CrossUp/manifest.toml
Labels: size-small

#2513 [Testing] Who's Talking 0.6.3.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#2514 Team Fortress Fantasy 1.1.7.0
  stable/Tf2Hud/manifest.toml
Labels: size-small

#2516 Teleporter 2.0.2.2
  stable/TeleporterPlugin/manifest.toml
Labels: size-small

#2517 SubmarineTracker 1.8.0.5
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2518 MPTickBar 1.4.1.6
  stable/MPTickBar/manifest.toml
Labels: size-small

#2520 [Testing] HighFpsPhysicsPlugin 7.3.0.0
  testing/live/HighFpsPhysicsPlugin/manifest.toml
Labels: size-small

#2521 MemoryMarker v1.1.0.1
  stable/MemoryMarker/manifest.toml
Labels: size-small

#2525 NoTankYou v6.0.1.1
  stable/NoTankYou/manifest.toml
Labels: size-small

#2526 ChillFrames v2.0.1.1
  stable/ChillFrames/manifest.toml
Labels: size-small

#2527 DelvUI release 2.1.0.1
  stable/DelvUI/manifest.toml
Labels: size-small

#2524 Emote Log 1.1.1.1
  stable/EmoteLog/manifest.toml
Labels: size-small

#2522 [Release] Better Mount Roulette 1.2.0.13
  stable/BetterMountRoulette/manifest.toml
Labels: size-small

#2523 DailyDuty v4.0.5.1
  stable/DailyDuty/manifest.toml
Labels: size-small

#2538 Allagan Tools v1.6.1.8
  stable/InventoryTools/manifest.toml
Labels: size-small

#2536 EzWondrousTails v2.3.0.1
  stable/WondrousTailsSolver/manifest.toml
Labels: size-mid

#2535 [Testing] TooltipNotes 1.2.0.0
  testing/live/TooltipNotes/manifest.toml
Labels: size-mid

#2534 [API9] TargetLines 1.3.1.0
  stable/TargetLines/manifest.toml
Labels: size-mid

#2533 TextToTalk/PingPlugin/SoundSetter API9
  stable/PingPlugin/manifest.toml
  stable/SoundSetter/manifest.toml
  stable/TextToTalk/manifest.toml
  testing/live/TextToTalk/manifest.toml
Labels: size-mid

#2532 ffxiv2mqtt and DutyTracker
  stable/DutyTracker/manifest.toml
  stable/Ffxiv2Mqtt/manifest.toml
Labels: size-mid

#2531 MacroRecorded 1.0.1.2
  stable/MacroRecorded/manifest.toml
Labels: size-small

#2529 [Testing] StanleyParableXiv 2.0.0.0
  testing/live/StanleyParableXiv/manifest.toml
Labels: size-mid

#2519 DeepDungeonTracker 1.0.0.4
  stable/DeepDungeonTracker/manifest.toml
Labels: size-small

#2540 Simple Tweaks 1.9.0.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#2541 [Stable] G4EUkrChatSupport update
  stable/G4EUkrChatSupport/manifest.toml
Labels: size-small

#2545 DeviceChangeFix 2.0.3
  stable/DeviceChangeFix/manifest.toml
Labels: size-small

#2546 [Release] Better Mount Roulette 1.2.0.14
  stable/BetterMountRoulette/manifest.toml
Labels: size-small

#2551 PartyPlanner 1.5.4
  stable/PartyPlanner/manifest.toml
Labels: size-small

#2550 Teleporter 2.0.2.3
  stable/TeleporterPlugin/manifest.toml
Labels: size-small

#2544 DiscordBridge 1.4.4.0
  stable/Dalamud.DiscordBridge/manifest.toml
Labels: size-small

#2543 ChatTyper 0.1.3.0
  stable/ChatTyper/manifest.toml
Labels: size-small

#2542 FlashOnTell 0.0.5.0
  stable/FlashOnTell/manifest.toml
Labels: size-small

#2539 Owofy 1.5.0.0
  stable/owofy/manifest.toml
Labels: size-small

#2547 [Testing] Lights, Camera, Action! v0.2.1.2
  testing/live/CameraLoader/manifest.toml
Labels: size-small

#2548 BigPlayerDebuffs v1.1.0.9
  stable/BigPlayerDebuffs/manifest.toml
Labels: size-small

#2553 TriadBuddy 1.9.0.1
  stable/TriadBuddy/manifest.toml
Labels: size-small

#2549 Currency Tracker 1.2.4.0
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#2554 JobBars v1.2.4.1
  stable/JobBars/manifest.toml
Labels: size-large

#2555 Pet Nicknames v1.4.0.2
  stable/PetRenamer/manifest.toml
Labels: size-small

#2556 SubmarineTracker 1.8.0.5
  stable/SubmarineTracker/manifest.toml
Labels: size-large

#2557 Tracky Track 1.0.0.5
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2558 [Stable] StanleyParableXiv 2.0.0.0
  stable/StanleyParableXiv/manifest.toml
Labels: size-mid

#2559 HuntHelper 1.0.0.8
  stable/HuntHelper/manifest.toml
Labels: size-small

#2560 Fungah 1.0.0.1
  stable/Fungah/images/icon.png
  stable/Fungah/manifest.toml
Labels: size-small

#2530 Stormtalons release 1.1.0.3
  stable/Stormtalons/manifest.toml
Labels: size-small

#2562 TrackyTrack 1.1.0.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#2563 borderless-fix 0.0.0.3
  stable/borderless-fix/images/icon.png
  stable/borderless-fix/manifest.toml
Labels: move channel, size-small

#2564 MimicryHelper 1.0.1.3
  stable/MimicryHelper/manifest.toml
Labels: size-small

#2565 Submarine Tracker 1.8.0.7
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2566 MemoryMarker v1.1.0.2
  stable/MemoryMarker/manifest.toml
Labels: size-small

#2567 Update CharacterSync to 2.0.0.9
  stable/Dalamud.CharacterSync/manifest.toml
Labels: size-small

#2568 Update StackSellPrice (stable)
  stable/StackSellPrice/manifest.toml
Labels: size-small

#2569 Update PositionalGuide (stable)
  stable/PositionalGuide/manifest.toml
Labels: size-small

#2570 Market Board 1.3.2
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#2571 Waitingway 1.2.6
  stable/Waitingway.Dalamud/manifest.toml
  testing/live/Waitingway.Dalamud/images/icon.png
  testing/live/Waitingway.Dalamud/manifest.toml
Labels: size-small

#2572 PaissaHouse 1.4.3
  stable/autoSweep/images/icon.png
  stable/autoSweep/manifest.toml
Labels: size-small

#2573 Tidychat v1.2.5
  stable/TidyChat/manifest.toml
Labels: size-small

#2575 DeathRoll 1.3.0.1
  stable/DeathRoll/manifest.toml
Labels: size-large

#2576 ItemVendorLocation update to 2.4.0.0
  stable/ItemVendorLocation/manifest.toml
Labels: size-mid

#2577 Distance 1.0.1.5
  stable/Distance/manifest.toml
Labels: size-small
