Repository goatcorp/DalamudPluginsD17, pull requests merged in 2023-08, with the labels that each got.

#2178 [Testing] WhoDidThat? v1.1.0
  testing/live/WhoDidThat/manifest.toml
Labels: size-small

#2172 ChillFrames v2.0.0.3
  stable/ChillFrames/manifest.toml
Labels: size-small

#2173 Mappy v1.0.1.4
  stable/Mappy/manifest.toml
Labels: size-small

#2175 NoTankYou v6.0.0.7
  stable/NoTankYou/manifest.toml
Labels: size-small

#2176 [Testing] PetRenamer v0.2.4
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#2179 [Testing] Who's Talking 0.3.0.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#2180 Bozja Buddy 1.1.5.0
  stable/BozjaBuddy/manifest.toml
Labels: size-small

#2181 SubmarineTracker 1.7.3.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2182 [Testing] TextToTalk v1.27.0
  testing/live/TextToTalk/manifest.toml
Labels: size-small

#2183 [Testing] PetRenamer v0.3.1.1
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#2184 EurekaLinker 1.4.1.1
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#2185 BlueMageHelper 3.0.1.0
  stable/BlueMageHelper/manifest.toml
Labels: size-small

#2186 [Testing] WhoDidThat v1.1.1.0
  testing/live/WhoDidThat/manifest.toml
Labels: size-small

#2187 Mappy v1.0.1.5
  stable/Mappy/manifest.toml
Labels: size-small

#2189 [Testing] WhoDidThat V1.1.1.1
  testing/live/WhoDidThat/manifest.toml
Labels: size-small

#2191 NoTankYou v6.0.0.8
  stable/NoTankYou/manifest.toml
Labels: size-small

#2192 [Testing] TextToTalk v1.27.1
  testing/live/TextToTalk/manifest.toml
Labels: size-small

#2193 SubmarineTracker 1.7.3.3
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2195 Orchestrion 2.0.0.3 -> 2.0.0.4
  stable/orchestrion/manifest.toml
Labels: size-small

#2198 NoTankYou v6.0.0.9
  stable/NoTankYou/manifest.toml
Labels: size-small

#2196 [Testing] PetRenamer v0.4.0.1
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#2201 [Testing] Who's Talking 0.4.0.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#2200 [Testing] PetRenamer v0.4.0.2
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2199 WhoDidThat Migration to Stable
  stable/WhoDidThat/images/icon.png
  stable/WhoDidThat/manifest.toml
Labels: move channel, size-small

#2203 [Testing] PetRenamer v0.4.1.0
  testing/live/PetRenamer/manifest.toml
Labels: size-large

#2202 SonarPlugin v0.5.3.0
  stable/SonarPlugin/manifest.toml
Labels: size-large

#2204 [Testing] Who's Talking 0.5.0.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#2205 Mappy v1.0.2.0
  stable/Mappy/manifest.toml
Labels: size-mid

#2206 PriceInsight 2.5.0.2
  stable/PriceInsight/manifest.toml
Labels: size-small

#2207 WhoDidThat v1.1.1.2
  stable/WhoDidThat/manifest.toml
Labels: size-small

#2208 SubmarineTracker 1.7.3.4
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2210 [Testing] PetRenamer v0.4.2.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2212 GoodFriend v3.0.0.0
  stable/GoodFriend/manifest.toml
Labels: size-large

#2213 Bozja Buddy 1.1.5.2
  stable/BozjaBuddy/manifest.toml
Labels: size-small

#2215 [Testing] HUDManager 2.5.16
  testing/live/HUDManager/manifest.toml
Labels: size-small

#2217 Mappy v1.0.2.1
  stable/Mappy/manifest.toml
Labels: size-small

#2219 [Testing] PetRenamer v0.4.2.2
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2216 DeepDungeonDex 2.6.0
  stable/DeepDungeonDex/manifest.toml
Labels: size-large

#2222 [Testing] PetRenamer v0.4.2.3
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2221 Team Fortress Fantasy 1.1.5.0
  stable/Tf2Hud/manifest.toml
Labels: size-small

#2223 Update Sound Filter to 1.4.11
  stable/SoundFilter/manifest.toml
Labels: size-small

#2225 SubmarineTracker 1.7.4.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#2224 feat. FFXIVRPEventCalendarPlugin update to 2023.08.09 version. (fixed icon image, added add/report event links)
  testing/live/FFXIVRPCalendarPlugin/manifest.toml
Labels: size-small

#2229 GoodFriend v3.0.1.0
  stable/GoodFriend/manifest.toml
Labels: size-mid

#2228 SubmarineTracker 1.7.4.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2227 [Testing] PetRenamer v0.4.3.0
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2230 Mappy v1.0.2.2
  stable/Mappy/manifest.toml
Labels: size-small

#2231 [Testing] PetRenamer v0.4.4.0
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2232 GoodFriend v3.0.2.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#2234 [Testing] PetRenamer 0.4.5.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2233 Mappy v1.0.2.3
  stable/Mappy/manifest.toml
Labels: size-small

#2236 BetterPlaytime 1.4.0.1
  stable/BetterPlaytime/manifest.toml
Labels: size-small

#2237 Distance 1.0.1.4
  stable/Distance/manifest.toml
Labels: size-small

#2239 Pet Nicknames v1.0.1.0
  stable/PetRenamer/manifest.toml
Labels: size-small

#2240 Mappy v1.0.2.3
  stable/Mappy/manifest.toml
Labels: size-small

#2241 XIVDeck 0.3.15
  stable/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-large

#2245 WorkshopOptimizerPlugin update to 0.2.7.3
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-small

#2243 Pet Nicknames v1.0.1.1
  stable/PetRenamer/manifest.toml
Labels: size-small

#2244 SubmarineTracker 1.7.4.5
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2246 TPie release 1.7.1.0
  stable/TPie/manifest.toml
Labels: size-mid

#2250 Echoglossian new version
  stable/Echoglossian/manifest.toml
Labels: size-small

#2249 Mappy v1.0.2.5
  stable/Mappy/manifest.toml
Labels: size-small

#2248 TPie release 1.7.1.1
  stable/TPie/manifest.toml
Labels: size-small

#2077 [Testing] Tracky Track 0.0.6.0
  testing/live/TrackyTrack/images/icon.png
  testing/live/TrackyTrack/manifest.toml
Labels: new plugin, size-large

#2155 [Testing] HotbarHelper v0.0.2.0
  testing/live/HotbarHelper/images/icon.png
  testing/live/HotbarHelper/manifest.toml
Labels: new plugin, code reviewed, size-large

#2167 [Testing] Tick Tracker 0.0.0.2
  testing/live/TickTracker/images/icon.png
  testing/live/TickTracker/manifest.toml
Labels: new plugin, code reviewed, size-large

#2255 [Testing] HotbarHelper v0.0.2.2
  testing/live/HotbarHelper/manifest.toml
Labels: size-small

#2253 SubmarineTracker 1.7.4.6
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2256 [Testing] TrackyTrack 0.0.6.2
  testing/live/TrackyTrack/manifest.toml
Labels: size-small

#2247 VFXEditor v1.7.8.0
  stable/VFXEditor/manifest.toml
Labels: size-large

#2254 [Testing] Tick Tracker 0.0.1.0
  testing/live/TickTracker/images/icon.png
  testing/live/TickTracker/manifest.toml
Labels: size-large

#2257 DeepDungeonDex 2.6.1
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#2209 [Testing] Currency Tracker 1.1.0.0
  testing/live/CurrencyTracker/images/icon.png
  testing/live/CurrencyTracker/manifest.toml
Labels: new plugin, size-large

#2220 [Testing] Adopt OhGeeCD & move from old repo.
  testing/live/OhGeeCD/images/icon.png
  testing/live/OhGeeCD/manifest.toml
Labels: new plugin, size-large

#2242 [Testing] Combat Cursor Containment v0.1.0
  testing/live/CombatCursorContainment/images/icon.png
  testing/live/CombatCursorContainment/manifest.toml
Labels: new plugin, size-large

#2260 SortaKinda v0.0.0.5
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2261 SortaKinda 0.0.0.6
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2262 [Testing] HotbarHelper v0.0.2.3
  testing/live/HotbarHelper/manifest.toml
Labels: size-small

#2263 SortaKinda v0.0.0.7
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2265 SortaKinda v0.0.0.8
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2266 [Testing] Currency Tracker 1.1.1.1
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2264 [Testing] Combat Cursor Containment v0.1.1
  testing/live/CombatCursorContainment/manifest.toml
Labels: size-small

#2267 SortaKinda v0.0.0.9
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2268 [Testing] BetterMountRoulette 1.3.0.13
  testing/live/BetterMountRoulette/images/icon.png
  testing/live/BetterMountRoulette/manifest.toml
Labels: move channel, size-mid

#2273 [WhoDidThat] v1.2.0.0
  stable/WhoDidThat/manifest.toml
Labels: size-small

#2151 [Testing] added GlamourWishlist
  testing/live/GlamourWishlist/images/icon.png
  testing/live/GlamourWishlist/manifest.toml
Labels: new plugin, size-large

#2270 SubmarineTracker 1.7.4.8
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2271 [Testing] TrackyTrack 0.0.6.3
  testing/live/TrackyTrack/manifest.toml
Labels: size-small

#2226 [Testing] Distant Seas 1.0.0.0
  testing/live/DistantSeas/images/icon.png
  testing/live/DistantSeas/manifest.toml
Labels: new plugin, size-large

#2274 [Testing] Who's Talking 0.6.0.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#2275 DelvUI release 2.0.0.0
  stable/DelvUI/manifest.toml
Labels: size-large

#2278 [Testing] TrackyTrack 0.0.6.4
  testing/live/TrackyTrack/manifest.toml
Labels: size-small

#2279 [Testing] Who's Talking 0.6.1.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#2280 SortaKinda v0.0.0.10
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2281 DelvUI release 2.0.1.0
  stable/DelvUI/manifest.toml
Labels: size-small

#2276 VFXEditor v1.7.8.1
  stable/VFXEditor/manifest.toml
Labels: size-large

#2282 [Testing] Pet Nicknames v1.1.0.0
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#2283 OrchestrionPlugin 2.0.0.4 -> 2.1.0.0
  stable/orchestrion/manifest.toml
Labels: size-small

#2284 DelvUI release 2.0.2.0
  stable/DelvUI/manifest.toml
Labels: size-small

#2286 [Testing] Pet Nicknames v1.1.0.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2285 [Testing] TrackyTrack 0.0.6.5
  testing/live/TrackyTrack/manifest.toml
Labels: size-small

#2287 VFXEditor v1.7.8.2
  stable/VFXEditor/manifest.toml
Labels: size-mid

#2292 DelvUI release 2.0.2.1
  stable/DelvUI/manifest.toml
Labels: size-small

#2291 [Testing] Currency Tracker 1.1.1.2
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2289 SortaKinda v0.0.1.0
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2293 [Testing] Tracky Track 0.0.7.0
  testing/live/TrackyTrack/manifest.toml
Labels: size-mid

#2295 WhoDidThat v1.2.0.1
  stable/WhoDidThat/manifest.toml
Labels: size-small

#2299 [Testing] Tracky Track 0.0.7.1
  testing/live/TrackyTrack/manifest.toml
Labels: size-small

#2296 [Testing] Tick Tracker 0.0.1.1
  testing/live/TickTracker/manifest.toml
Labels: size-small

#2300 [Testing] Currency Tracker 1.1.1.3
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2301 [Testing] Currency Tracker 1.1.1.4
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#2294 [Testing] Pet Nicknames v1.2.0.0
  testing/live/PetRenamer/manifest.toml
Labels: size-large

#2297 Simple Tweaks 1.8.9.2
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#2298 [Testing] HUDManager 2.5.17
  testing/live/HUDManager/manifest.toml
Labels: size-mid

#2302 SortaKinda v0.0.1.1
  testing/live/SortaKinda/manifest.toml
Labels: size-small

#2303 [Testing] Pet Nicknames v1.2.1.0
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#2305 [Testing] TextToTalk v1.27.2
  testing/live/TextToTalk/manifest.toml
Labels: size-small

#2269 Update lots of Anna plugins
  stable/BurntToast/manifest.toml
  stable/ChatTwo/manifest.toml
  stable/ExpandedSearchInfo/manifest.toml
  stable/ExtraChat/manifest.toml
  stable/Glamaholic/manifest.toml
  stable/Globetrotter/manifest.toml
  stable/Namingway/manifest.toml
  stable/OrangeGuidanceTomestone/manifest.toml
  stable/PeepingTom/manifest.toml
  stable/RemotePartyFinder/manifest.toml
  stable/SoundFilter/manifest.toml
  stable/TextBoxStyler/manifest.toml
  stable/TheGreatSeparator/manifest.toml
  stable/Tourist/manifest.toml
  stable/XIVChat/manifest.toml
Labels: build failed, size-large

#2308 SubmarineTracker 1.7.4.10
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#2309 [Testing] TextToTalk v1.27.3
  testing/live/TextToTalk/manifest.toml
Labels: size-small

#2310 TextToTalk v1.24.2.2
  stable/TextToTalk/manifest.toml
Labels: size-small

#2311 [Testing] Currency Tracker 1.1.2.0
  testing/live/CurrencyTracker/manifest.toml
Labels: size-mid

#2313 [Testing] Pet Nicknames v1.2.1.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#2312 SubmarineTracker 1.7.4.11
  stable/SubmarineTracker/manifest.toml
Labels: size-small
