Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-02, with the labels that each got.

#3150 Tracky 1.4.0.2
  stable/TrackyTrack/manifest.toml
Labels: size-large

#3131 [testing] SimpleMarketBoard 1.0.0.0
  testing/live/SimpleMarketBoard/images/icon.png
  testing/live/SimpleMarketBoard/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3149 [testing/live] Fast Job Switcher 1.0.0.3
  testing/live/FastJobSwitcher/images/icon.png
  testing/live/FastJobSwitcher/manifest.toml
Labels: new plugin, completed-code-review, size-mid, completed-rules-compliance, completed-testing

#3155 HuntHelper v1.0.0.15
  stable/HuntHelper/manifest.toml
Labels: size-small

#3153 PriceInsight 2.8.0.0
  stable/PriceInsight/manifest.toml
Labels: size-small

#3152 Simple Tweaks 1.9.6.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#3154 [testing] SimpleMarketBoard v1.1.0.0
  testing/live/SimpleMarketBoard/manifest.toml
Labels: size-large

#3116 DeeperDeepDungeonDex v1.0.0.0
  testing/live/OfDungeonsDeep/images/icon.png
  testing/live/OfDungeonsDeep/manifest.toml
Labels: new plugin, completed-code-review, size-large, pending-rules-compliance, completed-testing

#3070 [testing] ChatTranslated v1.0.0.0
  testing/live/ChatTranslated/images/icon.png
  testing/live/ChatTranslated/manifest.toml
Labels: new plugin, size-large, pending-code-review, completed-rules-compliance, completed-testing

#3156 Tracky 1.4.0.3
  stable/TrackyTrack/manifest.toml
Labels: size-small

#3157 [Testing] SimpleMarketBoard 1.2.0.0
  testing/live/SimpleMarketBoard/manifest.toml
Labels: size-small

#3159 Tracky 1.4.0.4
  stable/TrackyTrack/manifest.toml
Labels: size-small

#3158 TargetLines 1.5.0
  stable/TargetLines/manifest.toml
Labels: size-small

#3160 [testing-live] ChatTranslated v1.0.1
  testing/live/ChatTranslated/manifest.toml
Labels: size-small

#3163 [testing-live] ChatTranslated v1.1.0
  testing/live/ChatTranslated/manifest.toml
Labels: size-small

#3161 [Testing] SimpleMarketBoard 1.2.0.1
  testing/live/SimpleMarketBoard/images/image1.png
  testing/live/SimpleMarketBoard/images/image2.png
  testing/live/SimpleMarketBoard/manifest.toml
Labels: size-small

#3162 TargetLines 1.5.1
  stable/TargetLines/manifest.toml
Labels: size-small

#3164 GatherBuddy 3.3.1.2
  stable/GatherBuddy/manifest.toml
Labels: size-small

#3165 [Testing] The Great Controller Hud Switcher 1.0.1.0
  testing/live/XIVControllerToggle/manifest.toml
Labels: size-small

#3166 Pet Nicknames v1.4.6.4
  stable/PetRenamer/manifest.toml
Labels: size-small

#3167 [stable] ChatTranslated v1.2.0
  stable/ChatTranslated/images/icon.png
  stable/ChatTranslated/manifest.toml
  testing/live/ChatTranslated/manifest.toml
Labels: move channel, size-small

#3169 CurrencyAlert v1.0.1.1
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#3171 [stable] ChatTranslated v1.3.0
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3170 RoleplayProfiles 0.3.0.0
  stable/RoleplayProfiles/manifest.toml
Labels: size-small

#3168 Himbeertoni Raid Tool 1.5.2.2
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#3172 Currency Tracker 1.3.4.2
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3174 PushyFinder 1.1.1.0
  stable/PushyFinder/manifest.toml
Labels: size-small

#3175 Allagan Tools v1.6.2.3
  stable/InventoryTools/manifest.toml
Labels: size-small

#3177 OfDungeonsDeep v1.0.0.1
  stable/OfDungeonsDeep/images/icon.png
  stable/OfDungeonsDeep/manifest.toml
Labels: move channel, size-small

#3176 EngageTimer v2.3.2.0
  stable/EngageTimer/manifest.toml
Labels: size-mid

#3179 Himbeertoni Raid Tool 1.5.2.3
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#3178 [Testing] Pet Nicknames v1.4.7.0
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#3180 Bozja Buddy 1.1.5.5
  stable/BozjaBuddy/manifest.toml
Labels: size-small

#3181 SimpleCompare
  testing/live/SimpleCompare/manifest.toml
Labels: size-small

#3185 QuoteOfTheLobby
  testing/live/QuoteOfTheLobby/manifest.toml
Labels: size-small

#3187 Allagan Tools v1.6.2.4
  stable/InventoryTools/manifest.toml
Labels: size-small

#3188 Fantasy Player v2.2.0.1
  stable/FantasyPlayer/manifest.toml
Labels: size-small

#3189 cl_showpos 1.1.0.1
  stable/cl_showpos/manifest.toml
Labels: size-small

#3190 Pet Nicknames v1.4.7.1
  stable/PetRenamer/manifest.toml
Labels: size-small

#3191 SubmarineTracker 1.8.2.6
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3192 EurekaLinker 1.5.0.5
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#3193 [Testing] CoordImporter v1.1.0.4
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#3186 [stable] ChatTranslated v1.3.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3184 [Testing] ScoutHelper v1.0.0.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-large

#3197 Tracky 1.4.0.5
  stable/TrackyTrack/manifest.toml
Labels: size-small

#3196 [stable] ChatTranslated v1.3.2.1
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3195 [Testing] ScoutHelper v1.0.1.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#3198 [stable] ChatTranslated v1.3.2.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3203 Map Party Assist v2.1.1.0
  stable/MapPartyAssist/manifest.toml
Labels: size-small

#3201 Update AutoMountBgm (stable)
  stable/AutoMountBgm/images/icon.png
  stable/AutoMountBgm/manifest.toml
Labels: move channel, size-small

#3202 SonarPlugin v0.6.2.0
  stable/SonarPlugin/manifest.toml
Labels: size-mid

#3199 Distance 1.1.1.0
  stable/Distance/manifest.toml
Labels: move channel, size-large

#3204 Orchestrion 2.2.0.1 -> 2.2.0.2
  stable/orchestrion/manifest.toml
Labels: size-small

#3206 TitleEdit 2.2.6.13 -> 2.2.7.1
  stable/TitleEdit/manifest.toml
  testing/live/TitleEdit/images/icon.png
  testing/live/TitleEdit/images/image1.png
  testing/live/TitleEdit/images/image2.png
  testing/live/TitleEdit/images/image3.png
  testing/live/TitleEdit/images/image4.png
  testing/live/TitleEdit/manifest.toml
Labels: size-small

#3205 PrefPro 1.2.0.7 -> 1.2.1.1
  stable/PrefPro/manifest.toml
  testing/live/PrefPro/images/icon.png
  testing/live/PrefPro/images/image1.png
  testing/live/PrefPro/manifest.toml
Labels: size-mid

#3207 [Stable] G4EUkrChatSupport v1.0.0.32
  stable/G4EUkrChatSupport/images/icon.png
  stable/G4EUkrChatSupport/manifest.toml
Labels: size-small

#3200 [stable] ChatTranslated v1.4.0.0
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3212 Himbeertoni Raid Tool 1.5.2.5
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#3211 MonsterLootHunter 1.0.20.5
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#3210 1.4.0.7
  stable/TrackyTrack/manifest.toml
Labels: size-large

#3208 [Stable] G4EUkrChatSupport v1.0.0.34
  stable/G4EUkrChatSupport/images/icon.png
  stable/G4EUkrChatSupport/manifest.toml
Labels: size-small

#3209 [stable] ChatTranslated v1.4.0.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3213 GoodFriend v3.0.6.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#3215 RoleplayProfiles 1.0.0.0
  stable/RoleplayProfiles/manifest.toml
Labels: size-small

#3216 Allagan Tools v1.6.2.5
  stable/InventoryTools/manifest.toml
Labels: size-small

#3218 CurrencyAlert v1.0.1.2
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#3219 SimpleMarketBoard 1.3.0.3
  stable/SimpleMarketBoard/manifest.toml
  testing/live/SimpleMarketBoard/manifest.toml
Labels: size-small

#3220 [Stable] XIVWindowResizer 1.0.0.1
  stable/XIVWindowResizer/images/icon.png
  stable/XIVWindowResizer/manifest.toml
Labels: move channel, size-small

#3221 [Testing] Pet Nicknames v1.4.8.0
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#3222 [Testing] Pet Nicknames 1.4.8.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#3223 [Testing] ScoutHelper v1.1.0.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-mid

#3224 [stable] ChatTranslated v1.4.0.3
  stable/ChatTranslated/images/icon.png
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3226 Simple Tweaks 1.9.7.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#3228 Tilted 3.4.1.2
  stable/Tilted/manifest.toml
Labels: size-small

#3227 Himbeertoni Raid Tool 1.5.2.6
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#3232 Currency Tracker 1.3.4.3
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3182 [Testing] MouseTargetTooltip
  testing/live/MouseTargetTooltip/images/icon.png
  testing/live/MouseTargetTooltip/manifest.toml
Labels: new plugin, completed-code-review, size-large, pending-rules-compliance, completed-testing

#3237 Simple Tweaks 1.9.7.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#3238 [stable] ChatTranslated v1.4.1.0
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3235 Browsingway 1.5.6.0
  stable/Browsingway/manifest.toml
Labels: size-small

#3234 MPTickBar 1.4.1.7
  stable/MPTickBar/manifest.toml
Labels: size-large

#3233 Clarity In Chaos 1.4.0.1
  stable/ClarityInChaos/manifest.toml
Labels: size-mid

#3230 Update PositionalGuide (stable)
  stable/PositionalGuide/manifest.toml
Labels: size-mid

#3231 [Testing] ScoutHelper v1.1.1.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-mid

#3217 Tick Tracker 1.4.0.0
  testing/live/TickTracker/manifest.toml
Labels: size-large

#3240 DelvUI release 2.1.1.2
  stable/DelvUI/manifest.toml
Labels: size-small

#3239 Pet Nicknames v1.4.8.1
  stable/PetRenamer/manifest.toml
Labels: size-small

#3241 DelvUI release 2.1.1.3
  stable/DelvUI/manifest.toml
Labels: size-small

#3242 [Testing] ScoutHelper v1.1.2.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#3243 TextToTalk v1.28.9
  stable/TextToTalk/manifest.toml
Labels: size-small
