Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-05, with the labels that each got.

#3472 [Testing] Pet Nicknames 1.4.8.7
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#3468 [SimpleTodo] New Version 0.0.0.3
  testing/live/SimpleTodo/manifest.toml
Labels: size-small

#3469 [Testing] Umbra 1.0.3.0
  testing/live/Umbra/manifest.toml
Labels: size-mid

#3470 MacroMate 1.0.9.1
  stable/MacroMate/manifest.toml
Labels: size-large

#3473 [Testing] Umbra 1.0.3.1
  testing/live/Umbra/manifest.toml
Labels: size-small

#3474 ChatTwo 1.23.3
  stable/ChatTwo/manifest.toml
Labels: size-small

#3475 [Testing] Umbra 1.0.3.7
  testing/live/Umbra/manifest.toml
Labels: size-small

#3476 ChatTwo 1.23.4
  stable/ChatTwo/manifest.toml
Labels: size-small

#3477 [Testing] Umbra 1.0.3.8
  testing/live/Umbra/manifest.toml
Labels: size-small

#3478 TickTracker 1.4.2.0
  stable/TickTracker/manifest.toml
Labels: size-small

#3480 EngageTimer v2.3.3.0
  stable/EngageTimer/manifest.toml
Labels: size-small

#3483 [Testing] Minesweeper 1.1.0.3
  testing/live/DalamudMinesweeper/manifest.toml
Labels: size-small

#3481 [Testing] Umbra 1.0.4.1
  testing/live/Umbra/manifest.toml
Labels: size-mid

#3482 [TESTING] Echoglossian v3.1.x
  testing/live/Echoglossian/images/icon.png
  testing/live/Echoglossian/manifest.toml
Labels: move channel, size-large

#3486 EnemyListHP 2.1.0.2
  stable/EnmityHp/manifest.toml
Labels: size-small

#3485 [Testing] Minesweeper 1.1.0.4
  testing/live/DalamudMinesweeper/manifest.toml
Labels: size-small

#3484 [Testing] Umbra 1.0.4.5
  testing/live/Umbra/manifest.toml
Labels: size-small

#3487 Minesweeper 1.1.0.4 testing->stable
  stable/DalamudMinesweeper/images/icon.png
  stable/DalamudMinesweeper/manifest.toml
Labels: move channel, size-small

#3489 TickTracker 1.4.3.0
  stable/TickTracker/manifest.toml
Labels: size-small

#3490 [Testing] Umbra 1.0.6.0
  testing/live/Umbra/manifest.toml
Labels: size-small

#3491 [Testing] Umbra 1.0.6.3
  testing/live/Umbra/manifest.toml
Labels: size-mid

#3492 [Testing] Umbra 1.0.6.4
  testing/live/Umbra/manifest.toml
Labels: size-small

#3495 DiademCalculator 1.1.0.0
  stable/DiademCalculator/manifest.toml
Labels: size-small

#3494 [Testing] Umbra 1.0.6.10
  testing/live/Umbra/manifest.toml
Labels: size-mid

#3497 [Testing] Umbra 1.0.6.17
  testing/live/Umbra/manifest.toml
Labels: size-small

#3500 MacroMate 1.0.10.0
  stable/MacroMate/manifest.toml
Labels: size-small

#3502 [SimpleTodo] 0.0.0.5
  testing/live/SimpleTodo/manifest.toml
Labels: size-small

#3503 [FIX] - Echoglossian v3.1.x
  stable/Echoglossian/manifest.toml
Labels: version conflict, size-mid

#3505 Update EasyTranslate to version 2.0
  testing/live/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-large

#3506 [SimpleTodo] Update to 0.0.0.6
  testing/live/SimpleTodo/manifest.toml
Labels: size-small

#3507 Currency Tracker 1.3.5.2
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#3508 SubmarineTracker 1.8.4.3
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3499 ChatTwo 1.24.0
  stable/ChatTwo/manifest.toml
Labels: size-large

#3509 ChatTwo 1.24.2
  stable/ChatTwo/manifest.toml
Labels: size-small

#3510 MacroMate 1.0.10.1
  stable/MacroMate/manifest.toml
Labels: size-small

#3511 SonarPlugin v0.6.3.1
  stable/SonarPlugin/manifest.toml
Labels: size-large

#3512 ChatTwo 1.24.3
  stable/ChatTwo/manifest.toml
Labels: size-small

#3513 WhoDidThat v1.5.1.0
  stable/WhoDidThat/manifest.toml
Labels: size-small

#3515 SubmarineTracker 1.8.4.4
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3516 MacroMate 1.0.10.3
  stable/MacroMate/manifest.toml
Labels: size-small

#3524 MacroMate 1.0.11.0
  stable/MacroMate/manifest.toml
Labels: size-small

#3522 DelvUI release 2.1.3.0
  stable/DelvUI/manifest.toml
Labels: size-small

#3521 ChatTwo 1.25.0
  stable/ChatTwo/manifest.toml
Labels: size-mid

#3519 [testing] PvpStats v1.0.1.0
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#3523 EasyTranslate 2.1.0.0
  testing/live/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-large

#3496 [Testing] XIVInstantMessenger 1.4.0.1
  testing/live/Messenger/manifest.toml
Labels: size-small

#3525 Easy Translate version 2.1 stable
  stable/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-large

#3528 DelvCD release 1.0.1.1
  stable/DelvCD/manifest.toml
Labels: size-small

#3529 DelvUI release 2.1.3.1
  stable/DelvUI/manifest.toml
Labels: size-small

#3532 PvP Tracker v1.0.1.0
  stable/PvpStats/manifest.toml
Labels: size-large

#3530 ChatTwo 1.25.2
  stable/ChatTwo/manifest.toml
Labels: size-mid

#3517 [Testing] Allagan Tools v1.7.0.0
  testing/live/InventoryTools/manifest.toml
Labels: size-large

#3533 Echoglossian v3.2.x
  stable/Echoglossian/manifest.toml
  testing/live/Echoglossian/images/icon.png
  testing/live/Echoglossian/manifest.toml
Labels: size-large

#3535 [Simple Todo] Public Release
  stable/SimpleTodo/images/icon.png
  stable/SimpleTodo/manifest.toml
Labels: move channel, size-small

#3536 [Testing] Allagan Tools 1.7.0.1
  testing/live/InventoryTools/manifest.toml
Labels: size-mid

#3541 Market Board 1.4.0
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#3540 islandworkshopsearch v1.0.0
  stable/IslandWorkshopSearch/manifest.toml
Labels: size-small

#3539 Pet Nicknames v1.4.8.8
  stable/PetRenamer/manifest.toml
Labels: size-small

#3538 ChatTwo 1.25.3
  stable/ChatTwo/manifest.toml
Labels: size-large

#3546 [Stable] ItemVendorLocation 2.6.0.0
  stable/ItemVendorLocation/manifest.toml
  testing/live/ItemVendorLocation/images/icon.png
  testing/live/ItemVendorLocation/manifest.toml
Labels: size-large

#3545 Market Board 1.5.0
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#3542 ChatTwo 1.25.4
  stable/ChatTwo/manifest.toml
Labels: size-small

#3543 SubmarineTracker 1.8.5.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#3552 ChatTranslated v2.1.1.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3553 [Testing] Allagan Tools v1.7.0.2
  testing/live/InventoryTools/manifest.toml
Labels: size-small

#3554 EasyTranslate 2.1.1
  stable/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-large

#3549 [testing] PvP Tracker v2.0.0.0
  testing/live/PvpStats/manifest.toml
Labels: size-large

#3558 Simple Tweaks 1.9.7.3
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#3544 [Testing] Better Autoplay 1.0.0.0
  testing/live/BetterAutoplay/images/icon.png
  testing/live/BetterAutoplay/manifest.toml
Labels: new plugin, completed-code-review, size-small, completed-rules-compliance, completed-testing

#3562 [testing] PvP Tracker v2.0.0.1
  testing/live/PvpStats/manifest.toml
Labels: size-small
