Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-04, with the labels that each got.

#3372 NeatNoter 2.5.2.0
  stable/NeatNoter/manifest.toml
Labels: size-small

#3366 MapPartyAssist v2.1.3.1
  stable/MapPartyAssist/images/icon.png
  stable/MapPartyAssist/manifest.toml
Labels: size-small

#3369 [testing] PvpStats v0.2.3.1
  testing/live/PvpStats/manifest.toml
Labels: size-small

#3374 GoodFriend v3.3.1.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#3370 [Testing] ShowGear 1.2.1.2
  testing/live/ShowGear/images/icon.png
  testing/live/ShowGear/manifest.toml
Labels: size-small

#3375 ActionTimeline release 1.3.0.1
  stable/ActionTimeline/manifest.toml
Labels: size-small

#3377 TitleRoulette 3.0
  stable/TitleRoulette/manifest.toml
Labels: size-small

#3376 NoSoliciting v3.0.9.0
  stable/NoSoliciting/images/icon.png
  stable/NoSoliciting/manifest.toml
Labels: size-small

#3378 BurntToast 1.2.9
  stable/BurntToast/manifest.toml
Labels: size-small

#3380 ChatTwo 1.19.0
  stable/ChatTwo/manifest.toml
Labels: size-small

#3381 ChatTranslated 1.4.1.4
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3382 Tracky 1.4.0.9
  stable/TrackyTrack/manifest.toml
Labels: size-large

#3379 GoodFriend v3.3.3.0
  stable/GoodFriend/manifest.toml
Labels: size-large

#3383 MapPartyAssist v2.1.3.2
  stable/MapPartyAssist/manifest.toml
Labels: size-small

#3371 [Testing] PLX 1.1.0.0
  testing/live/PartyListExtras/manifest.toml
Labels: size-mid

#3367 Currency Tracker 1.3.5.0
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#3360 [Testing] MonsterDex 2.10.0
  testing/live/DeepDungeonDex/images/icon.png
  testing/live/DeepDungeonDex/manifest.toml
Labels: move channel, size-mid

#3385 ChatTranslated 1.4.1.5
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3384 [Testing] BetterPartyFinder 1.2.8
  testing/live/BetterPartyFinder/images/icon.png
  testing/live/BetterPartyFinder/manifest.toml
Labels: move channel, size-small

#3386 ChatTwo 1.19.1
  stable/ChatTwo/manifest.toml
Labels: size-small

#3387 ChatTwo 1.19.2
  stable/ChatTwo/manifest.toml
Labels: size-small

#3388 Pet Scale 1.2.1.0
  stable/PetScale/manifest.toml
Labels: size-small

#3389 TextToTalk v1.29.2
  stable/TextToTalk/manifest.toml
Labels: size-small

#3392 DelvUI release 2.1.2.1
  stable/DelvUI/manifest.toml
Labels: size-small

#3391 DelvCD release 1.0.1.0
  stable/DelvCD/manifest.toml
Labels: size-small

#3396 XIVWindowResizer 1.0.0.2
  stable/XIVWindowResizer/manifest.toml
Labels: size-small

#3395 PvPStats v0.2.3.2
  stable/PvpStats/images/icon.png
  stable/PvpStats/images/image1.PNG
  stable/PvpStats/images/image2.PNG
  stable/PvpStats/images/image3.PNG
  stable/PvpStats/manifest.toml
Labels: move channel, size-small

#3393 TriadBuddy 1.9.1
  stable/TriadBuddy/manifest.toml
Labels: size-small

#3394 ChatTwo 1.19.3
  stable/ChatTwo/manifest.toml
Labels: size-large

#3400 Death Recap 1.11.1.0
  stable/DeathRecap/manifest.toml
Labels: size-small

#3397 [Testing] ChatTwo 1.20.0
  testing/live/ChatTwo/images/icon.png
  testing/live/ChatTwo/manifest.toml
Labels: move channel, size-mid

#3399 [Testing] MacroMate 1.0.9.0
  testing/live/MacroMate/manifest.toml
Labels: size-large

#3401 RemotePartyFinder 1.0.12
  stable/RemotePartyFinder/manifest.toml
Labels: size-mid

#3403 [Testing] ChatTwo 1.20.1
  testing/live/ChatTwo/manifest.toml
Labels: size-large

#3404 ChatTwo 1.20.2
  testing/live/ChatTwo/manifest.toml
Labels: size-small

#3402 NeatNoter 2.5.3.0
  stable/NeatNoter/manifest.toml
Labels: size-small

#3406 PlayerTrack v3.2.11.0
  stable/PlayerTrack/manifest.toml
Labels: size-small

#3407 Pet Nicknames v1.4.8.5
  stable/PetRenamer/manifest.toml
Labels: size-small

#3405 Add Eorzea Votes 1.3.2
  stable/EorzeaVotes/manifest.toml
Labels: size-small

#3408 [Testing] ChatTwo 1.20.3
  testing/live/ChatTwo/manifest.toml
Labels: size-large

#3411 ChatTwo 1.20.4
  testing/live/ChatTwo/manifest.toml
Labels: size-small

#3414 ChatTwo 1.20.5
  testing/live/ChatTwo/manifest.toml
Labels: size-small

#3413 RoleplayProfiles 1.1.0.0
  stable/RoleplayProfiles/manifest.toml
Labels: size-small

#3415 NoSoliciting v3.0.10.0
  stable/NoSoliciting/manifest.toml
Labels: size-small

#3421 Tick Tracker 1.4.1.1
  stable/TickTracker/manifest.toml
Labels: size-small

#3420 [Testing] MacroMate 1.0.9.1
  testing/live/MacroMate/manifest.toml
Labels: size-small

#3419 Nameplate Debuffs 1.1.0.1
  stable/NamePlateDebuffs/manifest.toml
Labels: size-small

#3418 Tracky 1.4.1.0
  stable/TrackyTrack/manifest.toml
Labels: size-large

#3417 NeatNoter 2.5.4.0
  stable/NeatNoter/manifest.toml
Labels: size-small

#3422 ChatTwo 1.21.1
  stable/ChatTwo/manifest.toml
Labels: size-mid

#3425 ChatTwo 1.21.2
  stable/ChatTwo/manifest.toml
Labels: size-small

#3424 SubmarineTracker 1.8.4.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3426 Hunty 1.3.0.2
  stable/Hunty/manifest.toml
Labels: size-small

#3412 [testing] PvpStats v0.3.0.0
  testing/live/PvpStats/manifest.toml
Labels: size-large

#3427 ChatTwo 1.21.3
  stable/ChatTwo/manifest.toml
Labels: size-small

#3430 Currency Tracker 1.3.5.1
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3428 ChatTranslated v2.1
  stable/ChatTranslated/manifest.toml
Labels: size-large

#3429 update BurntToast testing to 1.3.0
  testing/live/BurntToast/images/icon.png
  testing/live/BurntToast/manifest.toml
Labels: move channel, size-mid

#3431 ChatTwo 1.21.4
  stable/ChatTwo/manifest.toml
Labels: size-small

#3433 ChatTranslated v2.1.0.1
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3436 DeathRoll 1.5.1.2
  stable/DeathRoll/manifest.toml
Labels: size-small

#3435 MapPartyAssist v2.1.3.3
  stable/MapPartyAssist/manifest.toml
  testing/live/MapPartyAssist/images/icon.png
Labels: size-small

#3434 ChatTwo 1.22.0
  testing/live/ChatTwo/manifest.toml
Labels: size-large

#3437 VFXEditor v1.8.3.7
  stable/VFXEditor/manifest.toml
Labels: size-large

#3439 1.22.1
  testing/live/ChatTwo/manifest.toml
Labels: size-small

#3438 XIVDeck 0.3.17
  stable/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-small

#3441 MapPartyAssist v2.1.3.4
  stable/MapPartyAssist/manifest.toml
Labels: size-small

#3442 Map Party Assist v2.1.3.5
  stable/MapPartyAssist/manifest.toml
Labels: size-small

#3432 [Testing] SimpleTodo
  testing/live/SimpleTodo/images/icon.png
  testing/live/SimpleTodo/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3390 [Testing] RpUtils
  testing/live/RpUtils/images/icon.png
  testing/live/RpUtils/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3443 BetterPartyFinder 1.2.8
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#3446 Pet Nicknames v1.4.8.6
  stable/PetRenamer/manifest.toml
Labels: size-small

#3445 [Testing] ItemVendorLocation 2.6.0.0
  testing/live/ItemVendorLocation/images/icon.png
  testing/live/ItemVendorLocation/manifest.toml
Labels: move channel, size-large

#3444 ChatTwo 1.23.0
  stable/ChatTwo/manifest.toml
Labels: size-large

#3447 TPie release 1.8.2.0
  stable/TPie/manifest.toml
Labels: size-small

#3423 [Testing] Minesweeper
  testing/live/DalamudMinesweeper/images/icon.png
  testing/live/DalamudMinesweeper/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3363 [Testing] Umbra
  testing/live/Umbra/images/icon.png
  testing/live/Umbra/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3448 [Testing] Umbra 1.0.0.2
  testing/live/Umbra/manifest.toml
Labels: size-small

#3449 PvPStats v0.3.0.0
  stable/PvpStats/manifest.toml
Labels: size-large

#3450 RpUtils v0.0.4
  testing/live/RpUtils/manifest.toml
Labels: size-small

#3452 [Testing] Umbra 1.0.1.0
  testing/live/Umbra/manifest.toml
Labels: size-small

#3453 RpUtils v0.1.0
  testing/live/RpUtils/manifest.toml
Labels: size-small

#3457 RpUtils v0.2.0
  testing/live/RpUtils/manifest.toml
Labels: size-small

#3455 [Testing] Umbra 1.0.2.0
  testing/live/Umbra/manifest.toml
Labels: size-mid

#3458 [SimpleTodo] New Version 0.0.0.2
  testing/live/SimpleTodo/manifest.toml
Labels: size-small

#3454 Pet Scale 1.2.1.1
  stable/PetScale/manifest.toml
Labels: size-small

#3451 [testing] PvPStats v0.3.1.0
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#3459 [Testing] Umbra 1.0.2.4
  testing/live/Umbra/manifest.toml
Labels: size-small

#3461 [Testing] Umbra 1.0.2.8
  testing/live/Umbra/manifest.toml
Labels: size-small

#3465 ChatTranslated v2.1.0.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3464 [Testing] Umbra 1.0.2.18
  testing/live/Umbra/manifest.toml
Labels: size-small

#3463 RpUtils v0.2.1
  testing/live/RpUtils/manifest.toml
Labels: size-small

#3467 RpUtils v0.2.2
  testing/live/RpUtils/manifest.toml
Labels: size-small

#3466 ChatTwo 1.23.1
  stable/ChatTwo/manifest.toml
Labels: size-large
