Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-11, with the labels that each got.

#4730 NoTankYou v7.1.0.2
  stable/NoTankYou/manifest.toml
Labels: size-small

#4732 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-small

#4733 [Stable] UsedName v0.8.6.0
  stable/UsedName/manifest.toml
Labels: size-small

#4734 ChatContext v0.0.0.2
  stable/ChatContext/images/icon.png
  stable/ChatContext/manifest.toml
Labels: move channel, size-small

#4736 VoiceDirector v1.0.1
  testing/live/VoiceDirector/manifest.toml
Labels: size-small

#4735 Dialog Copy 1.2.1.0
  stable/TalkCopy/manifest.toml
Labels: size-small

#4737 DragoonMayCry 1.2.1.0
  stable/DragoonMayCry/manifest.toml
Labels: size-mid

#4738 QuestTracker v1.0.1.2
  stable/QuestTracker/manifest.toml
  testing/live/QuestTracker/manifest.toml
Labels: size-small

#4739 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-mid

#4742 Title Edit v3.0.2.3
  stable/TitleEdit/manifest.toml
Labels: size-small

#4740 HUDUnlimited v1.0.0.6
  stable/HUDUnlimited/manifest.toml
Labels: size-small

#4741 PvP Tracker v.2.1.11.0
  stable/PvpStats/manifest.toml
Labels: size-mid

#4743 AutoBGM v1.0.0.0 - Promote to stable
  stable/AutoBGM/images/icon.png
  stable/AutoBGM/manifest.toml
Labels: move channel, size-small

#4744 [Testing] Altoholic v0.0.0.20
  testing/live/Altoholic/manifest.toml
Labels: size-large

#4745 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-mid

#4747 Migrate plugins
  stable/DamageInfoPlugin/manifest.toml
  stable/Housemate/manifest.toml
  stable/PrefPro/manifest.toml
  stable/ResLogger2.Plugin/manifest.toml
  stable/orchestrion/manifest.toml
Labels: size-large

#4752 Malmstone Calculator 1.0.7.2
  stable/Malmstone/manifest.toml
Labels: size-small

#4750 [Testing] XIVInstantMessenger 1.5.0.1
  testing/live/Messenger/manifest.toml
Labels: size-small

#4751 PvP Tracker v2.1.12.0
  stable/PvpStats/manifest.toml
Labels: size-mid

#4754 Umbra 2.2.42
  stable/Umbra/manifest.toml
Labels: size-small

#4753 ChatTranslated 3.3.0.4
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4755 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-small

#4756 [Testing] Altoholic v0.0.0.21
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4788 XIVWindowResizer 1.0.0.4
  stable/XIVWindowResizer/manifest.toml
Labels: size-small

#4787 Eureka Linker 1.5.1.5
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#4757 Who Am I Again v1.0.0.4
  stable/WhoAmIAgain/manifest.toml
Labels: size-small

#4762 MBHistory 1.0.1.1
  stable/MBHistory/manifest.toml
Labels: size-small

#4760 FlyTextFilter 4.2.1.0
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#4767 BetterPlaytime 1.4.1.1
  stable/BetterPlaytime/manifest.toml
Labels: size-small

#4782 DiademCalculator 1.1.1.5
  stable/DiademCalculator/manifest.toml
Labels: size-small

#4785 DeathRoll 1.5.3.5
  stable/DeathRoll/manifest.toml
Labels: size-small

#4783 NamePlate Debuffs 1.1.0.4
  stable/NamePlateDebuffs/manifest.toml
Labels: size-small

#4781 DutyTracker 1.0.2.5
  stable/DutyTracker/manifest.toml
Labels: size-small

#4780 WaymarkPresetPlugin 1.5.2.5
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#4771 Malmstone Calculator 1.0.7.3
  stable/Malmstone/manifest.toml
Labels: size-small

#4779 Fader 2.6.2.5
  stable/FaderPlugin/manifest.toml
Labels: size-small

#4774 EmoteLog v1.1.3.1
  stable/EmoteLog/manifest.toml
Labels: size-small

#4791 cl_showpos 1.1.0.3
  stable/cl_showpos/manifest.toml
Labels: size-small

#4790 LogogramHelper 0.0.3.3
  stable/LogogramHelper/manifest.toml
Labels: size-small

#4770 StanleyParableXiv 3.1.0.0
  stable/StanleyParableXiv/manifest.toml
Labels: size-small

#4773 borderless-fix v0.0.0.5
  stable/borderless-fix/manifest.toml
Labels: size-small

#4772 EnemyListDebuffs v1.11.0.0
  stable/EnemyListDebuffs/manifest.toml
Labels: size-small

#4769 Hunty 1.3.1.1
  stable/Hunty/manifest.toml
Labels: size-small

#4786 XIVDeck 0.3.22
  stable/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-small

#4784 BlueMageHelper 3.0.2.5
  stable/BlueMageHelper/manifest.toml
Labels: size-small

#4795 Stormtalons 1.1.0.4 --> 1.1.0.5
  stable/Stormtalons/manifest.toml
Labels: size-small

#4776 [Testing] BetterMountRoulette 1.6.0.22
  testing/live/BetterMountRoulette/manifest.toml
Labels: size-small

#4793 ReSanctuary 1.4.0.1
  stable/ReSanctuary/manifest.toml
Labels: size-small

#4792 Linkpearl 3.0.0.1
  stable/Linkpearl/manifest.toml
Labels: size-small

#4766 SubmarineTracker 1.9.3.5
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#4777 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-small

#4807 Wholist v1.7.1.0
  stable/Wholist/manifest.toml
Labels: size-small

#4812 Elden Ring v0.0.3.1
  stable/EldenRing/manifest.toml
Labels: size-small

#4813 Chat Bubbles v2.1.7.2
  stable/ChatBubbles/manifest.toml
Labels: size-small

#4806 NoTankYou v7.2.0.0
  stable/NoTankYou/manifest.toml
Labels: size-small

#4821 Of Dungeons Deep v1.0.2.0
  stable/OfDungeonsDeep/manifest.toml
Labels: size-small

#4796 ChillFrames v3.1.0.0
  stable/ChillFrames/manifest.toml
Labels: size-small

#4803 HUDUnlimited v1.1.0.0
  stable/HUDUnlimited/manifest.toml
Labels: size-small

#4814 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small

#4798 DailyDuty v5.2.0.0
  stable/DailyDuty/manifest.toml
Labels: size-small

#4815 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-small

#4804 Mappy v3.1.0.0
  stable/Mappy/manifest.toml
Labels: size-small

#4805 MemoryMarker v2.2.0.0
  stable/MemoryMarker/manifest.toml
Labels: size-small

#4808 SortaKinda v2.1.0.0
  stable/SortaKinda/manifest.toml
Labels: size-small

#4809 XIVUncombo v1.0.0.1 (Switch to Stable)
  stable/XIVUncombo/image1.png
  stable/XIVUncombo/image2.png
  stable/XIVUncombo/image3.png
  stable/XIVUncombo/images/icon.png
  stable/XIVUncombo/manifest.toml
  testing/live/XIVUncombo/manifest.toml
Labels: move channel, size-small

#4810 WhereAmIAgain v2.1.0.0
  stable/WhereAmIAgain/manifest.toml
Labels: size-small

#4794 Distant Seas 1.1.0.2
  stable/DistantSeas/manifest.toml
Labels: blocked, size-small

#4800 EzMiniCactpot v2.1.0.0
  stable/MiniCactpotSolver/manifest.toml
Labels: size-small

#4802 EzWondrousTails v3.2.0.0
  stable/WondrousTailsSolver/manifest.toml
Labels: size-small

#4799 EzFauxHollows v1.4.0.0
  stable/FauxHollowsSolver/manifest.toml
Labels: size-mid

#4764 [Stable and Testing] ZDs 1.0.0.4
  stable/ZDs/manifest.toml
  testing/live/ZDs/manifest.toml
Labels: size-small

#4819 islandworkshopsearch1.0.0.2
  stable/IslandWorkshopSearch/manifest.toml
Labels: size-small

#4801 MonsterDex 2.12.0
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#4816 XIVInstantMessenger 1.5.0.2
  stable/Messenger/manifest.toml
Labels: size-large

#4823 VoiceDirector 1.1.0.0
  testing/live/VoiceDirector/manifest.toml
Labels: size-small

#4822 TextToTalk v1.30.4
  stable/TextToTalk/manifest.toml
Labels: size-small

#4825 StanleyParableXiv 3.1.1.0
  stable/StanleyParableXiv/manifest.toml
Labels: size-small

#4778 Title Edit v3.0.3.0
  stable/TitleEdit/manifest.toml
Labels: blocked, size-small

#4789 [Testing] rtyping 0.1.0.5
  testing/live/rtyping/manifest.toml
Labels: size-small

#4818 hunthelper 1.0.0.26
  stable/HuntHelper/manifest.toml
Labels: size-small

#4827 Allagan Market 1.1.0.0
  stable/AllaganMarket/manifest.toml
Labels: size-small

#4828 Fantasy Player 2.3.0.0
  stable/FantasyPlayer/manifest.toml
Labels: size-small

#4829 TPie release 1.10.0.0
  stable/TPie/manifest.toml
Labels: size-small

#4830 SonarPlugin v0.6.7.0
  stable/SonarPlugin/manifest.toml
Labels: size-small

#4831 DelvCD release 1.2.0.0
  stable/DelvCD/manifest.toml
Labels: size-small

#4834 NOTED release 1.4.0.0
  stable/NOTED/manifest.toml
Labels: size-small

#4835 PennyPincher v1.8.0.1
  stable/PennyPincher/manifest.toml
Labels: size-small

#4837 [Stable] PlayerTrack v3.4.9
  stable/PlayerTrack/manifest.toml
Labels: size-small

#4838 ActionTimeline release 1.5.0.0
  stable/ActionTimeline/manifest.toml
Labels: size-small

#4839 [Stable] NoSoliciting v3.1.1
  stable/NoSoliciting/manifest.toml
Labels: size-small

#4824 Simple Tweaks 1.10.3.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-large

#4840 Combat Cursor Containment v1.0.5
  stable/CombatCursorContainment/manifest.toml
Labels: size-small

#4841 Minimap Marker Magnitude v0.1.2
  testing/live/MinimapMarkerMagnitude/manifest.toml
Labels: size-small

#4842 Seated Sidekick Spectator v0.1.2
  testing/live/SeatedSidekickSpectator/manifest.toml
Labels: size-small

#4843 DelvUI release 2.3.0.0
  stable/DelvUI/manifest.toml
Labels: size-small

#4844 PatMe 1.11
  stable/PatMe/manifest.toml
Labels: size-small

#4846 HarpHero 1.11
  stable/HarpHero/manifest.toml
Labels: size-small

#4845 TriadBuddy 1.11
  stable/TriadBuddy/manifest.toml
Labels: size-small

#4847 Weatherman 2.4.1.1
  stable/Weatherman/manifest.toml
Labels: size-small

#4820 CrossUp 1.7.0.6
  testing/live/CrossUp/manifest.toml
Labels: size-mid

#4817 WTSync 0.12.0.0
  stable/WTSync/manifest.toml
Labels: size-mid

#4765 Market Board 1.9.0
  stable/MarketBoardPlugin/manifest.toml
  testing/live/MarketBoardPlugin/manifest.toml
Labels: size-small

#4832 [Stable] PriceCheck v2.7.1
  stable/PriceCheck/manifest.toml
Labels: size-large

#4848 Gearset Helper Plugin 2.5
  stable/GearsetHelperPlugin/manifest.toml
Labels: size-mid

#4849 Updating Graphics Config, Teamcraft List Maker, and TwitchXIV for patch 7.1
  stable/GraphicsConfig/manifest.toml
  stable/TwitchXIV/manifest.toml
  testing/live/TeamcraftListMaker/manifest.toml
Labels: size-small

#4850 ChatTranslated & CopyTranslated api11
  stable/ChatTranslated/manifest.toml
  stable/CopyTranslated/manifest.toml
Labels: size-small

#4851 CrossUp 1.7.0.6 (Stable)
  stable/CrossUp/manifest.toml
Labels: size-mid

#4852 PvP Tracker v2.2.0.0
  stable/PvpStats/manifest.toml
Labels: size-mid

#4861 ChatCoordinates: 2.1.2.6
  stable/ChatCoordinates/manifest.toml
Labels: size-small

#4860 Update Doorbell for patch 7.1
  stable/Doorbell/manifest.toml
Labels: size-small

#4858 Update Random Class Selector and move to Stable
  stable/RandomClassSelector/images/icon.png
  stable/RandomClassSelector/manifest.toml
Labels: move channel, size-small

#4857 [Testing] HUDManager 2.5.21.0
  testing/live/HUDManager/manifest.toml
Labels: size-small

#4856 Party Icons 1.2.2.0
  stable/PartyIcons/manifest.toml
Labels: size-small

#4855 ZDs 1.0.0.5
  stable/ZDs/manifest.toml
  testing/live/ZDs/manifest.toml
Labels: size-small

#4854 [Testing] CoordImporter v1.2.0.1
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#4853 [Testing] Scout Helper v1.2.1
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#4836 FlashOnTell 0.0.7.0
  stable/FlashOnTell/manifest.toml
Labels: size-small

#4833 ChatTyper 0.1.5.0
  stable/ChatTyper/manifest.toml
Labels: size-small

#4826 Owofy 1.7.0.0
  stable/owofy/manifest.toml
Labels: size-small

#4811 ZodiacBuddy v1.1.0.0
  stable/ZodiacBuddy/manifest.toml
Labels: size-small

#4862 Wotsit 1.0.5.3
  stable/Dalamud.FindAnything/manifest.toml
Labels: size-small

#4863 DragoonMayCry 1.2.1.1
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#4864 Update FCNameColor to 5.0.2.0
  stable/FCNameColor/manifest.toml
Labels: size-small

#4865 Simple Tweaks 1.10.3.2
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#4868 [Testing] Collector's Anxiety v0.0.10
  testing/live/CollectorsAnxiety/manifest.toml
Labels: size-small

#4869 BetterPartyFinder 1.4.7
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#4867 WhoDidThat v1.7.1.0
  stable/WhoDidThat/manifest.toml
Labels: size-small

#4871 ReadyCheckHelper 1.0.7.7
  stable/ReadyCheckHelper/manifest.toml
Labels: size-small

#4874 RezPls 1.4.0.0
  stable/RezPls/manifest.toml
Labels: size-small

#4875 ChatAlerts 2.2.0.0
  stable/ChatAlerts/manifest.toml
Labels: size-small

#4866 GatherBuddy 3.5.0.0
  stable/GatherBuddy/manifest.toml
Labels: size-mid

#4873 Tracky 1.5.5.5
  stable/TrackyTrack/manifest.toml
Labels: size-mid

#4859 PartyPlanner 1.6.3.0
  stable/PartyPlanner/manifest.toml
Labels: size-small

#4876 ChatTwo 1.29.6
  stable/ChatTwo/manifest.toml
Labels: size-mid

#4872 Accountant 1.7.0.0
  stable/Accountant/manifest.toml
Labels: size-large

#4878 [CoordImporter] Fix images not being square
  stable/CoordImporter/images/icon.png
  stable/CoordImporter/manifest.toml
  testing/live/CoordImporter/images/icon.png
Labels: size-small

#4870 NotificationMaster 2.1.1.7
  stable/NotificationMaster/manifest.toml
Labels: size-large

#4884 PingPlugin v2.8.0
  stable/PingPlugin/manifest.toml
Labels: size-small

#4887 BetterPartyFinder 1.4.8
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#4882 [Testing] Altoholic v0.0.0.22
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#4881 Umbra 2.3.0
  stable/Umbra/manifest.toml
Labels: size-mid

#4885 Update easytranslate to version 4.0.0
  stable/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-mid

#4883 Mini 2.1.1.0
  stable/Mini/manifest.toml
Labels: size-mid

#4886 Echoglossian v3.16.x released
  stable/Echoglossian/manifest.toml
Labels: size-large

#4889 DelvUI release 2.3.1.0
  stable/DelvUI/manifest.toml
Labels: size-small

#4890 Simple Tweaks 1.10.3.3
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#4891 Allagan Tools 1.11.0.0
  stable/InventoryTools/manifest.toml
Labels: size-large

#4879 Dalamud.RichPresence 2.0.6.0
  stable/Dalamud.RichPresence/manifest.toml
Labels: size-small

#4880 Dalamud.DiscordBridge 1.5.1.0
  stable/Dalamud.DiscordBridge/manifest.toml
Labels: size-small

#4892 [Testing] ChatContext v0.0.1.1
  testing/live/ChatContext/manifest.toml
Labels: size-small
