Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-03, with the labels that each got.

#3251 Pet Nicknames v1.4.8.2
  stable/PetRenamer/manifest.toml
Labels: size-small

#3246 [stable] ChatTranslated v1.4.1.1
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3244 Tick Tracker 1.4.0.1
  testing/live/TickTracker/manifest.toml
Labels: size-small

#3254 Wholist v1.4.2.0
  stable/Wholist/manifest.toml
Labels: size-small

#3252 Tick Tracker 1.4.0.2
  testing/live/TickTracker/manifest.toml
Labels: size-small

#3248 GoodFriend v3.1.1.0
  stable/GoodFriend/manifest.toml
Labels: size-mid

#3250 Tracky 1.4.0.8
  stable/TrackyTrack/manifest.toml
Labels: size-large

#3236 VFXEditor v1.8.2.4
  stable/VFXEditor/manifest.toml
Labels: size-large

#3256 Pet Nicknames v1.4.8.3
  stable/PetRenamer/images/icon.png
  stable/PetRenamer/manifest.toml
Labels: size-small

#3255 OfDungeonsDeep v1.0.0.2
  stable/OfDungeonsDeep/manifest.toml
Labels: size-small

#3257 GoodFriend v3.2.0.0
  stable/GoodFriend/manifest.toml
Labels: size-large

#3258 GoodFriend v3.2.1.0-d17
  stable/GoodFriend/manifest.toml
Labels: size-small

#3259 Update PositionalGuide (stable)
  stable/PositionalGuide/manifest.toml
Labels: size-small

#3245 [Testing] PvP Tracker v.0.0.0.0
  testing/live/PvpStats/images/icon.png
  testing/live/PvpStats/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3262 [Testing] PvpStats v0.0.0.1
  testing/live/PvpStats/manifest.toml
Labels: new plugin, size-large

#3260 Wotsit v1.0.5.0
  stable/Dalamud.FindAnything/manifest.toml
Labels: size-small

#3093 [Testing] Gauge-O-Matic 0.0.1.6
  testing/live/GaugeOMatic/images/icon.png
  testing/live/GaugeOMatic/manifest.toml
Labels: new plugin, size-large, pending-code-review, completed-rules-compliance, completed-testing

#3266 NoKillPlugin 1.1.0.0
  stable/NoKillPlugin/manifest.toml
Labels: size-small

#3265 [Testing] PvpStats v0.0.1.0
  testing/live/PvpStats/manifest.toml
Labels: size-small

#3264 MacroRecorded 1.0.2.2
  stable/MacroRecorded/manifest.toml
Labels: size-small

#3269 Currency Tracker 1.3.4.4
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#3271 GoodFriend v3.2.2.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#3273 [Testing] PvpStats v0.1.0.0
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#3270 DeathRoll 1.5.0.0
  stable/DeathRoll/manifest.toml
Labels: size-large

#3274 NoTankYou v6.0.2.2
  stable/NoTankYou/manifest.toml
Labels: size-small

#3279 PatMe 1.9.0.1
  stable/PatMe/manifest.toml
Labels: size-small

#3278 [stable] ChatTranslated v1.4.1.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3276 GoodFriend v3.2.3.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#3275 [Testing] PvpStats v.0.1.1.0
  testing/live/PvpStats/manifest.toml
Labels: size-small

#3280 NoTankYou v6.0.3.0
  stable/NoTankYou/manifest.toml
Labels: size-small

#3281 TextToTalk v1.28.10
  stable/TextToTalk/manifest.toml
Labels: size-mid

#3283 [Testing] PvpStats v0.1.1.1
  testing/live/PvpStats/manifest.toml
Labels: size-small

#3284 Fader 2.6.1.1
  stable/FaderPlugin/manifest.toml
Labels: size-small

#3285 Simple Tweaks 1.9.7.2
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#3287 [Testing] Gauge-O-Matic 0.0.1.7
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#3282 Currency Tracker 1.3.4.5
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#3286 Orchestrion 2.2.0.2 -> 2.2.0.3
  stable/orchestrion/manifest.toml
Labels: size-large

#3293 Fantasy Player v2.2.0.2
  stable/FantasyPlayer/manifest.toml
Labels: size-small

#3292 Allagan Tools v1.6.2.6
  stable/InventoryTools/manifest.toml
Labels: size-small

#3289 MapPartyAssist v2.1.3.0
  stable/MapPartyAssist/manifest.toml
  testing/live/MapPartyAssist/manifest.toml
Labels: size-small

#3288 Fader 2.6.1.2
  stable/FaderPlugin/manifest.toml
Labels: size-small

#3290 Currency Tracker 1.3.4.6
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#3295 Add Eorzea Votes 1.3.1
  stable/EorzeaVotes/manifest.toml
Labels: size-mid

#3253 [Testing] Ntfynder 1.1.2.0
  testing/live/Ntfynder/images/icon.png
  testing/live/Ntfynder/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3297 Allagan Tools v1.6.2.7
  stable/InventoryTools/manifest.toml
Labels: size-small

#3296 SimpleMarketBoard 1.4.0.0
  stable/SimpleMarketBoard/images/image1.png
  stable/SimpleMarketBoard/images/image2.png
  stable/SimpleMarketBoard/images/image3.png
  stable/SimpleMarketBoard/manifest.toml
Labels: size-large

#3301 Currency Tracker 1.3.4.7
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3300 Distant Seas 1.1.0.0
  stable/DistantSeas/manifest.toml
Labels: size-small

#3299 [Testing] Who's Talking 0.6.8.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#3298 Allagan Tools v1.6.2.8
  stable/InventoryTools/manifest.toml
Labels: size-small

#3272 [Testing] EasyTranslate v1.0.0.0
  testing/live/EasyTranslate.DalamudPlugin/images/icon.png
  testing/live/EasyTranslate.DalamudPlugin/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3302 NeatNoter 2.5.1.0
  stable/NeatNoter/manifest.toml
Labels: size-small

#3294 [Testing] Paggles 1.0.0.1
  testing/live/Paggles/images/icon.png
  testing/live/Paggles/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3303 Allagan Tools v1.6.2.9
  stable/InventoryTools/manifest.toml
Labels: size-small

#3304 [Testing] EasyTranslate v1.0.1.0
  testing/live/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-small

#3305 SimpleMarketBoard 1.5.0.0
  stable/SimpleMarketBoard/manifest.toml
Labels: size-small

#3307 Orchestrion 2.2.0.3 -> 2.2.0.4
  stable/orchestrion/manifest.toml
Labels: size-small

#3306 PrefPro 1.2.1.1 -> 1.2.1.2
  stable/PrefPro/manifest.toml
Labels: size-small

#3308 DelvCD release 1.0.0.1
  stable/DelvCD/manifest.toml
Labels: size-small

#3309 A Realm Recorded v1.0.0.2
  stable/ARealmRecorded/manifest.toml
Labels: size-small

#3310 OfDungeonsDeep 1.0.0.3
  stable/OfDungeonsDeep/manifest.toml
Labels: size-small

#3311 Browsingway 1.6.0.0 (.net 8)
  stable/Browsingway/manifest.toml
Labels: size-large

#3314 Magitek Stratagem v0.3.0.0 - net8 upgrade
  stable/MagitekStratagem/images/icon.png
  stable/MagitekStratagem/manifest.toml
Labels: move channel, size-small

#3315 Fast Job Switcher 1.1.0.0
  stable/FastJobSwitcher/images/icon.png
  stable/FastJobSwitcher/manifest.toml
Labels: move channel, size-small

#3316 Clarity In Chaos 1.5.0.0
  stable/ClarityInChaos/manifest.toml
Labels: size-small

#3317 Tilted 3.5.0.0
  stable/Tilted/manifest.toml
Labels: size-small

#3313 PetScale 1.1.0.0
  stable/PetScale/images/icon.png
  stable/PetScale/manifest.toml
Labels: move channel, size-small

#3312 Tick Tracker 1.4.1.0
  stable/TickTracker/manifest.toml
Labels: size-large

#3320 MonterLootHunter 1.1.20.5
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#3322 MPTickBar 1.4.1.8
  stable/MPTickBar/manifest.toml
Labels: size-small

#3324 Pet Nicknames v1.4.8.4
  stable/PetRenamer/manifest.toml
Labels: size-small

#3326 FlyTextFilter 4.1.5.0
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#3327 LogogramHelper 0.0.3.1
  stable/LogogramHelper/manifest.toml
Labels: size-small

#3328 [Testing] rtyping 0.1.0.2
  testing/live/rtyping/manifest.toml
Labels: size-small

#3329 Update PositionalGuide (stable)
  stable/PositionalGuide/manifest.toml
Labels: size-small

#3330 Update StackSellPrice (stable)
  stable/StackSellPrice/manifest.toml
Labels: size-small

#3323 DeepDungeonTracker 1.0.0.8
  stable/DeepDungeonTracker/manifest.toml
Labels: size-large

#3325 Currency Tracker 1.3.4.8
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#3331 [Testing] EasyTranslate v1.0.2.0
  testing/live/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-small

#3318 JobBars 1.2.5.0
  stable/JobBars/manifest.toml
Labels: size-large

#3332 [Testing] Who's Talking 0.6.9.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#3334 MacroMate 1.0.8.1
  stable/MacroMate/manifest.toml
Labels: size-small

#3333 GoodFriend v3.2.3.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#3343 NOTED release 1.2.1.0
  stable/NOTED/manifest.toml
Labels: size-small

#3342 PvpStats v0.2.1.0
  testing/live/PvpStats/manifest.toml
Labels: size-small

#3340 ChatTranslated v1.4.1.3
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3339 GoodFriend v3.2.4.1
  stable/GoodFriend/manifest.toml
Labels: size-small

#3338 GatherBuddy 3.3.2.0
  stable/GatherBuddy/manifest.toml
Labels: size-small

#3337 [Testing] Gauge-O-Matic 0.0.1.8
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#3336 SubmarineTracker 1.8.3.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3335 DeathRoll 1.5.1.1
  stable/DeathRoll/manifest.toml
Labels: size-small

#3319 VFXEditor v1.8.3.0
  stable/VFXEditor/manifest.toml
Labels: size-large

#3345 Currency Tracker 1.3.4.9
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#3349 GoodFriend v3.3.0.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#3350 DelvCD release 1.0.0.2
  stable/DelvCD/manifest.toml
Labels: size-small

#3351 DelvUI release 2.1.2.0
  stable/DelvUI/manifest.toml
Labels: size-small

#3352 TPie release 1.8.1.0
  stable/TPie/manifest.toml
Labels: size-small

#3348 TextToTalk v1.29.0
  stable/TextToTalk/manifest.toml
Labels: size-large

#3347 [Testing] PvpStats v0.2.2.0
  testing/live/PvpStats/images/image1.PNG
  testing/live/PvpStats/images/image2.PNG
  testing/live/PvpStats/images/image3.PNG
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#3346 SubmarineTracker 1.8.4.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#3364 Mappy v1.0.7.6
  stable/Mappy/manifest.toml
Labels: size-small

#3362 CopyTranslated v1.4.3
  stable/CopyTranslated/manifest.toml
Labels: size-small

#3361 SubmarineTracker 1.8.4.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3359 [testing] PvpStats v0.2.2.1
  testing/live/PvpStats/manifest.toml
Labels: size-small

#3358 TextToTalk v1.29.1
  stable/TextToTalk/manifest.toml
Labels: size-small

#3357 NOTED release 1.2.1.1
  stable/NOTED/manifest.toml
Labels: size-small

#3356 PetScale 1.2.0.0
  stable/PetScale/manifest.toml
Labels: size-small

#3354 Nameplate Debuffs v1.1.0.0
  stable/NamePlateDebuffs/manifest.toml
  testing/live/NamePlateDebuffs/images/icon.png
  testing/live/NamePlateDebuffs/manifest.toml
Labels: size-mid

#3355 Update HuntBuddy (stable)
  stable/HuntBuddy/manifest.toml
Labels: size-large

#3365 [testing] PvpStats v0.2.3.0
  testing/live/PvpStats/manifest.toml
Labels: size-small
