Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-07, with the labels that each got.

#3651 ChatCoordinates 2.1.2.4
  stable/ChatCoordinates/manifest.toml
Labels: size-small

#3646 [Testing] VanillaHotbarExtender 1.1.1
  testing/live/VanillaHotbarExtender/manifest.toml
Labels: size-small

#3662 cl_showpos 1.1.0.2
  stable/cl_showpos/manifest.toml
Labels: size-small

#3665 ResizableHUD 1.3.0.0
  stable/ResizableHUD/manifest.toml
Labels: size-small

#3659 Market Board 1.6.0
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#3673 NameplateDebuffs 1.1.0.2
  stable/NamePlateDebuffs/manifest.toml
Labels: size-small

#3654 PaissaHouse 1.4.4.0
  stable/autoSweep/manifest.toml
Labels: size-small

#3652 Neko Fans 1.3.3
  stable/Neko/manifest.toml
Labels: size-small

#3667 EmoteLog 1.1.3.0
  stable/EmoteLog/manifest.toml
Labels: size-small

#3669 Browsingway 1.6.1.0
  stable/Browsingway/manifest.toml
Labels: size-small

#3670 TextToTalk v1.30.2
  stable/TextToTalk/manifest.toml
Labels: size-small

#3674 ChatCoordinates 2.1.2.5
  stable/ChatCoordinates/manifest.toml
Labels: size-small

#3664 Hybrid Camera 1.3.0.0
  stable/HybridCamera/manifest.toml
Labels: size-small

#3658 Dialogue Copy v1.0.0.0
  stable/TalkCopy/manifest.toml
Labels: size-small

#3656 ChatAlerts 2.1.0.0
  stable/ChatAlerts/manifest.toml
Labels: size-small

#3666 Update DeathRecap, CharacterPanelRefined, PriceInsight, WhichPatchWasThat
  stable/CharacterPanelRefined/manifest.toml
  stable/DeathRecap/manifest.toml
  stable/PriceInsight/manifest.toml
  stable/WhichPatchWasThat/manifest.toml
  testing/live/BetterAutoplay/images/icon.png
  testing/live/BetterAutoplay/manifest.toml
Labels: size-small

#3655 Accountant 1.5.0.0
  stable/Accountant/manifest.toml
Labels: size-small

#3660 FlyTextFilter 4.2.0.0
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#3649 [Stable] ChatBubbles 2.1.6.0
  stable/ChatBubbles/manifest.toml
Labels: size-small

#3668 MonsterLootHunter 1.1.21.5
  stable/MonsterLootHunter/manifest.toml
Labels: size-mid

#3671 Distant Seas 1.1.0.1
  stable/DistantSeas/manifest.toml
Labels: size-mid

#3672 XIVDeck 0.3.19
  stable/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-mid

#3644 update Owofy for API10
  stable/owofy/manifest.toml
Labels: size-small

#3645 update FlashOnTell for API10
  stable/FlashOnTell/manifest.toml
Labels: size-small

#3647 update Dalamud.DiscordBridge for API10
  stable/Dalamud.DiscordBridge/manifest.toml
Labels: size-small

#3699 PatMe 1.10
  stable/PatMe/manifest.toml
Labels: size-small

#3698 WhoDidThat v1.6.1.0
  stable/WhoDidThat/manifest.toml
Labels: size-small

#3697 XIVLogger 1.0.7.0
  stable/XIVLogger/manifest.toml
Labels: size-small

#3696 WaymarkPresetPlugin 1.5.2.0
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#3694 SubmarineTracker 1.9.2.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3692 MBHistory 1.0.1.0
  stable/MBHistory/manifest.toml
Labels: size-small

#3691 Hunty 1.3.1.0
  stable/Hunty/manifest.toml
Labels: size-small

#3689 DiademCalculator 1.1.1.0
  stable/DiademCalculator/manifest.toml
Labels: size-small

#3688 DeathRoll 1.5.2.0
  stable/DeathRoll/manifest.toml
Labels: size-small

#3687 ChatTwo 1.27.0
  stable/ChatTwo/manifest.toml
Labels: size-small

#3686 BlueMageHelper 3.0.2.0
  stable/BlueMageHelper/manifest.toml
Labels: size-small

#3685 BetterPlaytime 1.4.1.0
  stable/BetterPlaytime/manifest.toml
Labels: size-small

#3684 Fader 2.6.2.0
  stable/FaderPlugin/manifest.toml
Labels: size-small

#3683 Tilted v4.0.0.0 - Update to API10
  stable/Tilted/manifest.toml
Labels: size-small

#3682 WhereAmIAgain v2.0.0.0
  stable/WhereAmIAgain/manifest.toml
Labels: size-mid

#3703 BigPlayerDebuffs 1.1.0.10
  stable/BigPlayerDebuffs/manifest.toml
Labels: size-small

#3701 PriceCheck 2.7.0.0
  stable/PriceCheck/manifest.toml
Labels: size-small

#3677 QoL Bar v2.3.3.0
  stable/QoLBar/manifest.toml
Labels: size-small

#3680 [Testing] Damage Info 2.4.0.0
  testing/live/DamageInfoPlugin/images/icon.png
  testing/live/DamageInfoPlugin/images/image1.png
  testing/live/DamageInfoPlugin/manifest.toml
Labels: move channel, size-small

#3653 CrossUp v1.7.0.1
  stable/CrossUp/manifest.toml
Labels: size-mid

#3675 ChillFrames v3.0.0.0
  stable/ChillFrames/manifest.toml
Labels: size-mid

#3705 Kapture 1.8.0.0
  stable/Kapture/manifest.toml
Labels: size-small

#3693 ReadyCheckHelper 1.0.7.0
  stable/ReadyCheckHelper/manifest.toml
Labels: size-small

#3648 update ChatTyper for API 10
  stable/ChatTyper/manifest.toml
Labels: size-small

#3713 Adventurer in Need 1.5.0.0
  stable/AdventurerInNeed/manifest.toml
Labels: size-small

#3714 MacroChain 2.2.0.0
  stable/MacroChain/manifest.toml
Labels: size-small

#3712 Item Search 1.10.0.0
  stable/ItemSearchPlugin/manifest.toml
Labels: size-small

#3711 FPS Plugin 1.7.0.0
  stable/FPSPlugin/manifest.toml
Labels: size-small

#3710 Honorific 1.5.0.0
  stable/Honorific/manifest.toml
Labels: size-small

#3706 EasyTranslate apiX upgrade
  stable/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-small

#3695 Tracky 1.5.1.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#3690 EurekaLinker 1.5.1.0
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#3707 BurntToast 1.3.1
  stable/BurntToast/manifest.toml
  testing/live/BurntToast/images/icon.png
  testing/live/BurntToast/manifest.toml
Labels: size-mid

#3676 Updating TwitchXIV for API 10 and .NET 8
  stable/TwitchXIV/manifest.toml
Labels: size-small

#3715 Fader 2.6.2.1
  stable/FaderPlugin/manifest.toml
Labels: size-mid

#3719 GatherBuddy 3.4.0.1
  stable/GatherBuddy/manifest.toml
Labels: size-mid

#3722 [Testing] rtyping 0.1.0.3
  testing/live/rtyping/manifest.toml
Labels: size-small

#3721 LogogramHelper 0.0.3.2
  stable/LogogramHelper/manifest.toml
Labels: size-small

#3717 [Testing] Redirect 1.2.3.2
  testing/live/Redirect/manifest.toml
Labels: size-small

#3725 ChatTwo 1.27.1
  stable/ChatTwo/manifest.toml
Labels: size-small

#3732 CrossUp v1.7.0.2
  stable/CrossUp/manifest.toml
Labels: size-small

#3723 Browsingway 1.6.2.0
  stable/Browsingway/manifest.toml
Labels: size-small

#3726 Currency Tracker 1.4.0.0
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3727 borderless-fix 0.0.0.4
  stable/borderless-fix/manifest.toml
Labels: size-small

#3730 Update EasyTranslate to 3.0.1
  stable/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-small

#3734 Coordinate Importer v1.1.0.5
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#3731 Update TidyChat for 7.0
  stable/TidyChat/manifest.toml
Labels: size-small

#3739 Update Tourist to 1.2.15
  stable/Tourist/manifest.toml
Labels: size-small

#3738 Update Sound Filter to 1.4.14
  stable/SoundFilter/manifest.toml
Labels: size-small

#3741 [Testing] Redirect 1.2.3.3
  testing/live/Redirect/manifest.toml
Labels: size-small

#3737 Update Quest Map to 1.4.8
  stable/QuestMap/manifest.toml
Labels: size-small

#3728 hunthelper 1.0.0.20
  stable/HuntHelper/manifest.toml
Labels: size-small

#3733 Himbeertoni Raid Tool 1.6.0.0
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#3735 Pet Nicknames v1.5.0.1
  stable/PetRenamer/manifest.toml
Labels: size-small

#3589 Wotsit 1.0.5.1
  stable/Dalamud.FindAnything/manifest.toml
Labels: size-small

#3740 Update XIVChat to 1.7.9
  stable/XIVChat/manifest.toml
Labels: size-small

#3745 MacroRecorded 1.0.3.2
  stable/MacroRecorded/manifest.toml
Labels: size-small

#3747 RepairMe v1.0.1.16
  stable/RepairMe/manifest.toml
Labels: size-small

#3746 FFXIV RP Event Calendar 1.0.1.3 (7.0 Update)
  stable/FFXIVRPCalendarPlugin/images/icon.png
  stable/FFXIVRPCalendarPlugin/manifest.toml
Labels: size-small

#3748 Who's Talking 0.6.11.0
  stable/WhosTalking/manifest.toml
Labels: size-small

#3750 MemoryMarker v2.0.0.0
  stable/MemoryMarker/manifest.toml
Labels: size-small

#3724 Allagan Tools v1.7.0.7
  stable/InventoryTools/manifest.toml
Labels: size-large

#3708 TriadBuddy 1.10
  stable/TriadBuddy/manifest.toml
Labels: size-mid

#3729 HarpHero 1.10
  stable/HarpHero/manifest.toml
Labels: size-mid

#3736 Update Namingway to 1.1.13
  stable/Namingway/manifest.toml
Labels: size-mid

#3742 Update ExtraChat to 1.3.6
  stable/ExtraChat/manifest.toml
Labels: size-mid

#3743 Update PartyPlanner to 1.6.2
  stable/PartyPlanner/manifest.toml
Labels: size-mid

#3749 BetterShadows 1.4.0.0
  stable/BetterShadows/manifest.toml
Labels: size-large

#3752 AutoTimer v1.1.0.0
  stable/AutoTimer/manifest.toml
  testing/live/AutoTimer/manifest.toml
Labels: size-small

#3753 TargetLines 1.6.0.0
  stable/TargetLines/manifest.toml
Labels: size-small

#3754 TickTracker 1.5.0.0
  stable/TickTracker/manifest.toml
Labels: size-small

#3755 PingPlugin v2.7.0
  stable/PingPlugin/manifest.toml
Labels: size-small

#3751 [Testing] Scout Helper v1.2.0.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-mid

#3709 Update Orange Guidance Tomestone to 1.8.1
  stable/OrangeGuidanceTomestone/manifest.toml
Labels: size-large

#3765 NoSoliciting v3.1.0.0
  stable/NoSoliciting/manifest.toml
Labels: size-small

#3774 ClarityInChaos v2.0.0.0 - Update to API10
  stable/ClarityInChaos/manifest.toml
Labels: size-small

#3773 MagitekStratagem v0.5.0.0 - Update to API10
  stable/MagitekStratagem/manifest.toml
Labels: size-mid

#3768 [Release] BetterMountRoulette 1.3.0.16
  stable/BetterMountRoulette/manifest.toml
Labels: size-small

#3759 Allagan Tools v1.7.0.8
  stable/InventoryTools/manifest.toml
Labels: size-small

#3758 MacroMate 1.0.12.0
  stable/MacroMate/manifest.toml
Labels: size-small

#3760 EnemyListDebuffs v0.4.0.2
  stable/EnemyListDebuffs/manifest.toml
Labels: size-small

#3762 BetterShadows 1.4.1.0
  stable/BetterShadows/manifest.toml
Labels: size-mid

#3763 Teleporter 2.0.2.4
  stable/TeleporterPlugin/manifest.toml
Labels: size-small

#3764 ItemSearch 1.10.0.1
  stable/ItemSearchPlugin/manifest.toml
Labels: size-small

#3744 CrossUp v1.7.0.4
  stable/CrossUp/manifest.toml
Labels: size-small

#3756 Map Party Asssist v2.2.0.0
  stable/MapPartyAssist/manifest.toml
  testing/live/MapPartyAssist/manifest.toml
Labels: size-small

#3766 [Testing] HUDManager 2.5.20.0
  testing/live/HUDManager/manifest.toml
Labels: size-large

#3775 Fader 2.6.2.2
  stable/FaderPlugin/manifest.toml
Labels: size-small

#3778 Update Peeping Tom to 1.7.17
  stable/PeepingTom/manifest.toml
Labels: size-small

#3779 Wholist v1.4.4.0
  stable/Wholist/manifest.toml
Labels: size-small

#3550 [Testing] Eventy 0.0.0.1
  testing/live/Eventy/images/icon.png
  testing/live/Eventy/manifest.toml
Labels: new plugin, size-large, pending-code-review, pending-testing, completed-rules-compliance

#3770 Orchestrion 2.2.0.4 -> 2.2.0.5
  stable/orchestrion/manifest.toml
Labels: size-small

#3772 Housemate 1.0.2.11 -> 1.0.3.0
  stable/Housemate/manifest.toml
Labels: size-small

#3771 PrefPro 1.2.1.2 -> 1.2.2.0
  stable/PrefPro/manifest.toml
Labels: size-small

#3769 ResLogger2 0.0.2.5 -> 0.0.2.6
  stable/ResLogger2.Plugin/manifest.toml
Labels: size-small

#3776 JustBackup Dawntrail update
  stable/JustBackup/manifest.toml
Labels: size-small

#3781 Wotsit 1.0.5.2
  stable/Dalamud.FindAnything/manifest.toml
Labels: size-small

#3782 CollectableCalculator 3.0
  stable/CollectableCalculator/manifest.toml
Labels: size-small

#3780 Wholist v1.4.4.1
  stable/Wholist/manifest.toml
Labels: size-small

#3783 [Testing] Redirect 1.2.3.4
  testing/live/Redirect/manifest.toml
Labels: size-small

#3784 ChatTwo 1.27.2
  stable/ChatTwo/manifest.toml
Labels: size-small

#3785 TPie release 1.9.0.0
  stable/TPie/manifest.toml
Labels: size-small

#3786 Update Globetrotter to 1.2.11
  stable/Globetrotter/manifest.toml
Labels: size-small

#3787 JustBackup 1.1.0.8
  stable/JustBackup/manifest.toml
Labels: size-small

#3789 [Testing] Scout Helper v1.2.1.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#3793 ReadyCheckHelper 1.0.7.1
  stable/ReadyCheckHelper/manifest.toml
Labels: size-small

#3792 SubmarineTracker 1.9.2.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3791 ChatTwo 1.27.3
  stable/ChatTwo/manifest.toml
Labels: size-small

#3790 JobBars v1.3.0.0
  stable/JobBars/manifest.toml
Labels: size-mid

#3797 CopyTranslated v1.1.4.1
  stable/CopyTranslated/manifest.toml
Labels: size-small

#3795 ChatTranslated v2.1.2.4
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3794 WaymarkPresetPlugin 1.5.2.1
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#3800 Dialog Copy 1.1.0.1
  stable/TalkCopy/manifest.toml
Labels: size-small

#3801 TitleRoulette 4.0
  stable/TitleRoulette/manifest.toml
Labels: size-small

#3802 MapLinker to 1.1.8.0 (apiX)
  stable/MapLinker/manifest.toml
Labels: size-small

#3804 Fungah 1.0.0.4
  stable/Fungah/manifest.toml
Labels: size-small

#3803 IslandWorkshopSearch 1.0.0.1
  stable/IslandWorkshopSearch/manifest.toml
Labels: size-small

#3806 [Testing] Scout Helper v1.2.2.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#3808 RpUtils v0.2.3
  testing/live/RpUtils/manifest.toml
Labels: size-small

#3809 GatherBuddy 3.4.0.2
  stable/GatherBuddy/manifest.toml
Labels: size-small

#3810 PvP Tracker v2.1.0.0
  stable/PvpStats/manifest.toml
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#3813 NOTED release 1.3.0.0
  stable/NOTED/manifest.toml
Labels: size-small

#3812 ActionTimeline release 1.4.0.0
  stable/ActionTimeline/manifest.toml
Labels: size-small

#3811 [Testing] StanleyParableXiv 3.0.0.0
  testing/live/StanleyParableXiv/manifest.toml
Labels: size-mid

#3815 MemoryMarker v2.0.0.1
  stable/MemoryMarker/manifest.toml
Labels: size-small
