Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-10, with the labels that each got.

#4633 SubmarineTracker 1.9.2.7
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#4634 Chat Proximity 1.1.1
  stable/ChatProximity/manifest.toml
Labels: size-small

#4635 Wholist v1.5.1.0
  stable/Wholist/manifest.toml
Labels: size-small

#4636 hunthelper1.0.0.25
  stable/HuntHelper/manifest.toml
Labels: size-small

#4637 MagitekStratagem v0.7.0.2: Attempt to fix crashes during cutscenes
  stable/MagitekStratagem/manifest.toml
Labels: size-small

#4640 Snooper 1.4.0.0
  stable/Snooper/manifest.toml
Labels: size-small

#4639 DamageInfoPlugin 2.4.0.3 -> 2.4.1.0
  stable/DamageInfoPlugin/manifest.toml
Labels: size-small

#4638 DutyTracker 1.0.2.0
  stable/DutyTracker/manifest.toml
Labels: size-large

#4642 SubmarineTracker 1.9.2.8
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#4644 PvP Tracker v2.1.8.0
  stable/PvpStats/manifest.toml
Labels: size-mid

#4645 SubmarineTracker 1.9.2.9
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#4646 DiscordBridge 1.5.0.2
  stable/Dalamud.DiscordBridge/manifest.toml
Labels: size-small

#4647 BetterPartyFinder 1.4.4
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#4648 DutyTacker 1.0.2.1
  stable/DutyTracker/manifest.toml
Labels: size-small

#4649 Pet Nicknames v2.2.0.5
  stable/PetRenamer/manifest.toml
Labels: size-small

#4652 BetterPartyFinder 1.4.5
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#4651 PvP Tracker v2.1.9.0
  stable/PvpStats/manifest.toml
Labels: size-small

#4650 SubmarineTracker 1.9.3.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#4654 Umbra 2.2.38
  stable/Umbra/manifest.toml
Labels: size-small

#4655 Umbra 2.2.39
  stable/Umbra/manifest.toml
Labels: size-small

#4658 Title Edit v3.0.2.1
  stable/TitleEdit/manifest.toml
Labels: size-small

#4656 [Testing] DragoonMayCry v1.0.1.0
  testing/live/DragoonMayCry/manifest.toml
Labels: size-small

#4659 Wholist v1.6.0.0
  stable/Wholist/manifest.toml
Labels: size-small

#4661 SonarPlugin v0.6.2.2
  stable/SonarPlugin/manifest.toml
Labels: size-small

#4662 Himbeertoni Raid Tool 1.6.2.10
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#4665 Allagan Market 1.0.0.7
  stable/AllaganMarket/manifest.toml
Labels: size-small

#4660 [Testing] DragoonMayCry v1.1.0.1
  testing/live/DragoonMayCry/manifest.toml
Labels: size-large

#4409 [Testing] HUDUnlimited
  testing/live/HUDUnlimited/images/icon.png
  testing/live/HUDUnlimited/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4617 SAMMI Webhook Plugin v1.0.0.0
  testing/live/SammiPlugin/images/icon.png
  testing/live/SammiPlugin/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4643 HotbarBackup v1.0.0
  testing/live/HotbarBackup/images/icon.png
  testing/live/HotbarBackup/manifest.toml
Labels: new plugin, completed-code-review, size-mid, completed-rules-compliance, completed-testing

#4616 AutoBGM v1.0.0.0
  testing/live/AutoBGM/images/icon.png
  testing/live/AutoBGM/manifest.toml
Labels: new plugin, completed-code-review, size-mid, completed-rules-compliance, completed-testing

#4668 HUDUnlimited v1.0.0.1
  testing/live/HUDUnlimited/manifest.toml
Labels: size-small

#4669 ChatTranslated 3.3.0.0
  stable/ChatTranslated/manifest.toml
Labels: size-mid

#4672 ChatTranslated 3.3.0.1
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4671 SubmarineTracker 1.9.3.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#4670 Umbra 2.2.40
  stable/Umbra/manifest.toml
Labels: size-small

#3941 [Testing] Absolute Roleplay
  testing/live/AbsoluteRoleplay/images/bio.png
  testing/live/AbsoluteRoleplay/images/bookmarks.png
  testing/live/AbsoluteRoleplay/images/gallery.png
  testing/live/AbsoluteRoleplay/images/icon.png
  testing/live/AbsoluteRoleplay/images/story.png
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4673 SubmarineTracker 1.9.3.3
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#4674 [Testing] HUDManager 2.5.20.1
  testing/live/HUDManager/manifest.toml
Labels: size-small

#4535 [Testing] Voice Director v1.0.0.0
  testing/live/VoiceDirector/images/icon.png
  testing/live/VoiceDirector/images/preview1.png
  testing/live/VoiceDirector/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance

#4559 VenueManager v2.2.0
  testing/live/VenueManager/images/icon.png
  testing/live/VenueManager/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4675 HUDUnlimited v1.0.0.2
  testing/live/HUDUnlimited/manifest.toml
Labels: size-small

#4676 HUDUnlimited v1.0.0.3
  testing/live/HUDUnlimited/manifest.toml
Labels: size-small

#4677 [Testing] Altoholic 0.0.0.14
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#4681 Allagan Tools 1.7.1.1
  stable/InventoryTools/manifest.toml
Labels: size-small

#4680 [Testing] VenueManager v2.3.4
  testing/live/VenueManager/manifest.toml
Labels: size-small

#4679 [Testing] DragoonMayCry v1.1.0.2
  testing/live/DragoonMayCry/manifest.toml
Labels: size-small

#4678 PvP Tracker v2.1.10.0
  stable/PvpStats/manifest.toml
  testing/live/PvpStats/manifest.toml
Labels: size-large

#4657 [Testing] CWLSLastSeenTool 1.0.0.1
  testing/live/CWLSLastSeenTool/images/icon.png
  testing/live/CWLSLastSeenTool/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4584 Hybrid Camera 1.4.0 (Testing)
  testing/live/HybridCamera/images/icon.png
  testing/live/HybridCamera/manifest.toml
Labels: move channel, size-small

#4682 [Testing] CWLSLastSeenTool 1.1.0.0
  testing/live/CWLSLastSeenTool/manifest.toml
Labels: size-mid

#4685 [Testing] Altoholic v0.0.0.15
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4684 Title Edit v3.0.2.2
  stable/TitleEdit/manifest.toml
Labels: size-small

#4683 DragoonMayCry v1.1.0.2
  stable/DragoonMayCry/manifest.toml
Labels: size-large

#4664 [Testing] XIVInstantMessenger 1.5.0.0
  testing/live/Messenger/manifest.toml
Labels: size-large

#4686 HUDUnlimited v1.0.0.4
  testing/live/HUDUnlimited/manifest.toml
Labels: size-small

#4663 Discord.RichPresence 2.0.5.0
  stable/Dalamud.RichPresence/manifest.toml
Labels: size-small

#4689 [Testing] Altoholic v0.0.0.16
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4688 Wordsmith v1.15.2
  stable/Wordsmith/manifest.toml
Labels: size-small

#4687 ChatTranslated 3.3.0.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4690 ZodiacBuddy v1.0.0.3
  stable/ZodiacBuddy/manifest.toml
Labels: size-small

#4691 HUDUnlimited v1.0.0.4
  stable/HUDUnlimited/images/icon.png
  stable/HUDUnlimited/manifest.toml
Labels: move channel, size-small

#4693 [Testing] QuestTracker v1.0.1.0
  testing/live/QuestTracker/images/icon.png
  testing/live/QuestTracker/manifest.toml
Labels: size-small

#4694 [Testing] Altoholic v0.0.0.17
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4695 HUDUnlimited v1.0.0.5
  stable/HUDUnlimited/manifest.toml
Labels: size-small

#4692 AbsoluteRoleplay [testing-live]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-mid

#4696 Currency Tracker 1.4.5.0
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#4698 ChatTranslated 3.3.0.3
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4697 [Testing] DragoonMayCry 1.2.0.0
  testing/live/DragoonMayCry/manifest.toml
Labels: size-large

#4705 Umbra 2.2.41
  stable/Umbra/manifest.toml
Labels: size-small

#4704 [Testing] Altoholic v0.0.0.18
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4703 [Testing] ChatContext v0.0.0.2
  testing/live/ChatContext/manifest.toml
Labels: size-small

#4702 [Testing] Hybrid Camera 0.4.1
  testing/live/HybridCamera/manifest.toml
Labels: size-small

#4701 [Testing] Multihit 0.0.2.2
  testing/live/MultiHit/manifest.toml
Labels: size-mid

#4700 [Testing] Absolute Roleplay
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-mid

#4706 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-mid

#4707 [Testing] DragoonMayCry v1.2.0.1
  testing/live/DragoonMayCry/manifest.toml
Labels: size-small

#4708 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-small

#4709 Allagan Tools 1.7.1.2
  stable/InventoryTools/manifest.toml
Labels: size-small

#4711 Mappy v3.0.3.5
  stable/Mappy/manifest.toml
Labels: size-small

#4712 Who's Talking 0.8.0.0
  stable/WhosTalking/manifest.toml
Labels: size-small

#4713 DragoonMayCry 1.2.0.1
  stable/DragoonMayCry/manifest.toml
Labels: size-large

#4714 Multi-plugin drifting: Updating 4 plugins' URLs and nothing else (except there was other stuff, teehee)
  stable/GraphicsConfig/manifest.toml
  stable/TwitchXIV/manifest.toml
  testing/live/RandomClassSelector/manifest.toml
  testing/live/TeamcraftListMaker/manifest.toml
Labels: size-small

#4715 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small

#4717 [Testing] CWLSLastSeenTool 1.1.1.0
  testing/live/CWLSLastSeenTool/images/icon.png
  testing/live/CWLSLastSeenTool/manifest.toml
Labels: size-small

#4716 VFXEditor v1.9.1.2
  stable/VFXEditor/manifest.toml
Labels: size-large

#4718 [Testing] Altoholic v0.0.0.19
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#4719 SonarPlugin v0.6.6.5
  stable/SonarPlugin/manifest.toml
Labels: size-small

#4720 VenueManager 2.3.4
  stable/VenueManager/images/icon.png
  stable/VenueManager/manifest.toml
Labels: move channel, size-small

#4725 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-large

#4722 Dialog Copy 1.2.0.0
  stable/TalkCopy/manifest.toml
Labels: size-mid

#4724 WhichMount 1.0.0.2 release
  stable/WhichMount/images/icon.png
  stable/WhichMount/manifest.toml
Labels: move channel, size-small

#4726 SonarPlugin v0.6.6.7
  stable/SonarPlugin/manifest.toml
Labels: size-small

#4727 Wholist v1.7.0.0
  stable/Wholist/manifest.toml
Labels: size-large

#4729 Talk Copy 1.2.0.1
  stable/TalkCopy/manifest.toml
Labels: size-small
