Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-09, with the labels that each got.

#4488 [Testing] Grace Gawker
  testing/live/GraceGawker/images/icon.png
  testing/live/GraceGawker/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4520 Tracky 1.5.3.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#4521 EnemyListDebuffs v0.4.0.3
  stable/EnemyListDebuffs/manifest.toml
Labels: size-small

#4523 Graphics Config 1.0.0.3 (Update + moving to stable)
  stable/GraphicsConfig/images/icon.png
  stable/GraphicsConfig/manifest.toml
  testing/live/GraphicsConfig/manifest.toml
Labels: move channel, size-small

#4524 DailyDuty v5.1.0.3
  stable/DailyDuty/manifest.toml
Labels: size-small

#4518 [Testing] Altoholic v0.0.0.11
  testing/live/Altoholic/manifest.toml
Labels: size-large

#4522 Umbra 2.2.32
  stable/Umbra/manifest.toml
Labels: size-large

#4513 ChatTwo 1.29.0
  stable/ChatTwo/manifest.toml
Labels: size-large

#4525 [Testing] Who's Talking 0.8.0.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#4526 Umbra 2.2.33
  stable/Umbra/manifest.toml
Labels: size-large

#3807 [Testing] XIVUncombo 1.0.0.0
  testing/live/XIVUncombo/image1.png
  testing/live/XIVUncombo/image2.png
  testing/live/XIVUncombo/image3.png
  testing/live/XIVUncombo/images/icon.png
  testing/live/XIVUncombo/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4527 DailyDuty v5.1.0.5
  stable/DailyDuty/manifest.toml
Labels: size-small

#4475 [Testing] DragoonMayCry v0.4.2
  testing/live/DragoonMayCry/images/icon.png
  testing/live/DragoonMayCry/manifest.toml
Labels: new plugin, completed-code-review, size-large, pending-testing, completed-rules-compliance, completed-testing

#4529 ChatTwo 1.29.1
  stable/ChatTwo/manifest.toml
Labels: size-small

#4532 Which mount 1.0.0.2
  testing/live/WhichMount/manifest.toml
Labels: size-small

#4530 MacroMate 1.0.19.0
  stable/MacroMate/manifest.toml
Labels: size-large

#4533 [Testing] ZDs 1.0.0.2
  testing/live/ZDs/manifest.toml
Labels: size-small

#4534 [Testing] DragoonMayCry v0.6.4
  testing/live/DragoonMayCry/manifest.toml
Labels: size-small

#4465 [Testing] Allagan Market 1.0.0.0
  testing/live/AllaganMarket/images/icon.png
  testing/live/AllaganMarket/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4536 Umbra 2.2.35
  stable/Umbra/manifest.toml
Labels: size-small

#4537 [Testing] Allagan Market 1.0.0.1
  testing/live/AllaganMarket/manifest.toml
Labels: size-small

#4538 Graphics Config 1.0.0.4
  stable/GraphicsConfig/manifest.toml
Labels: size-small

#4539 [Testing] Gauge-O-Matic 0.8.0.8
  testing/live/GaugeOMatic/manifest.toml
Labels: size-large

#4544 [Testing] Avant-Garde v0.1.2.0 (& v0.1.1.2 Stable)
  stable/AvantGarde/manifest.toml
  testing/live/AvantGarde/manifest.toml
Labels: size-small

#4543 [Testing] DragoonMayCry v0.7.1
  testing/live/DragoonMayCry/manifest.toml
Labels: size-small

#4541 Move WTSync from Testing to Stable.
  stable/WTSync/images/icon.png
  stable/WTSync/images/image1.png
  stable/WTSync/manifest.toml
  testing/live/WTSync/manifest.toml
Labels: move channel, size-small

#4546 [Testing] DragoonMayCry v0.7.3
  testing/live/DragoonMayCry/manifest.toml
Labels: size-small

#4547 ChatTwo 1.29.2
  stable/ChatTwo/manifest.toml
Labels: size-small

#4548 Pet Nicknames v2.2.0.2
  stable/PetRenamer/manifest.toml
Labels: size-mid

#4494 [Testing] Malmstone Calculator 1.0.0.0
  testing/live/Malmstone/images/icon.png
  testing/live/Malmstone/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4549 [Testing] Malmstone Calculator v1.0.5.5
  testing/live/Malmstone/manifest.toml
Labels: size-small

#4550 Umbra 2.2.36
  stable/Umbra/manifest.toml
Labels: size-mid

#4552 Better Mount Roulette 1.6.0.21
  testing/live/BetterMountRoulette/images/icon.png
  testing/live/BetterMountRoulette/manifest.toml
Labels: move channel, size-small

#4551 Target Lines 1.7.0
  stable/TargetLines/manifest.toml
Labels: size-large

#4553 [Testing] Allagan Market 1.0.0.2
  testing/live/AllaganMarket/manifest.toml
Labels: size-large

#4554 [Testing] Title Edit v3.0.0.0
  testing/live/TitleEdit/images/icon.png
  testing/live/TitleEdit/images/image1.png
  testing/live/TitleEdit/images/image2.png
  testing/live/TitleEdit/images/image3.png
  testing/live/TitleEdit/images/image4.png
  testing/live/TitleEdit/manifest.toml
Labels: move channel, size-large

#4555 [Testing] Malmstone Calculator v1.0.6.0
  testing/live/Malmstone/manifest.toml
Labels: size-mid

#4557 [Testing] DragoonMayCry v0.7.5
  testing/live/DragoonMayCry/manifest.toml
Labels: size-mid

#4556 Simple Tweaks 1.10.1.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#4558 [Testing] Gauge-O-Matic 0.8.0.9
  testing/live/GaugeOMatic/manifest.toml
Labels: size-mid

#4560 [Testing] Malmstone Calculator v1.0.6.5
  testing/live/Malmstone/manifest.toml
Labels: size-small

#4561 Simple Tweaks 1.10.1.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#4562 [Testing] Allagan Market 1.0.0.3
  testing/live/AllaganMarket/manifest.toml
Labels: size-mid

#4563 [Testing] Altoholic 0.0.0.12
  testing/live/Altoholic/manifest.toml
Labels: size-large

#4565 ChatTwo 1.29,3
  stable/ChatTwo/manifest.toml
Labels: size-small

#4567 [Testing] Allagan Market 1.0.0.4
  testing/live/AllaganMarket/manifest.toml
Labels: size-small

#4568 CoordImporter v1.2.0.0
  stable/CoordImporter/images/icon.png
  stable/CoordImporter/manifest.toml
Labels: move channel, size-small

#4569 Target Lines 1.7.1
  stable/TargetLines/manifest.toml
Labels: size-small

#4566 MacroMate 1.0.19.1
  stable/MacroMate/manifest.toml
Labels: size-mid

#4570 NeatNoter 2.6.4
  stable/NeatNoter/manifest.toml
Labels: size-small

#4571 Chat Proximity 1.0.0
  stable/ChatProximity/images/icon.png
  stable/ChatProximity/manifest.toml
Labels: move channel, size-small

#4572 [Testing] Title Edit v3.0.1.0
  testing/live/TitleEdit/manifest.toml
Labels: size-small

#4425 [Testing] QuestTracker v1.0.0.0
  testing/live/QuestTracker/images/icon.png
  testing/live/QuestTracker/manifest.toml
Labels: new plugin, completed-code-review, blocked, size-large, completed-rules-compliance, completed-testing

#4577 [Testing] Allagan Market 1.0.0.5
  testing/live/AllaganMarket/manifest.toml
Labels: size-small

#4576 SimpleMarketBoard 1.7.0.0
  stable/SimpleMarketBoard/manifest.toml
Labels: size-mid

#4575 BilingualTooltips 1.0.0.0
  stable/BilingualTooltips/images/icon.png
  stable/BilingualTooltips/images/image1.png
  stable/BilingualTooltips/images/image2.png
  stable/BilingualTooltips/manifest.toml
Labels: move channel, size-mid

#4578 ChatTranslated 3.2.1.0
  stable/ChatTranslated/manifest.toml
Labels: size-mid

#4574 [Testing] Lights, Camera, Action! v1.0.0
  testing/live/CameraLoader/manifest.toml
Labels: size-mid

#4573 [Testing] DragoonMayCry v0.12.0.2
  testing/live/DragoonMayCry/manifest.toml
Labels: size-large

#4579 [Testing] Scout Helper v1.6.3.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#4582 [Testing] DragoonMayCry v0.12.0.3
  testing/live/DragoonMayCry/manifest.toml
Labels: size-small

#4581 Allagan Market 1.0.0.5
  stable/AllaganMarket/images/icon.png
  stable/AllaganMarket/manifest.toml
Labels: move channel, size-small

#4580 BilingualTooltips 1.0.1.0
  stable/BilingualTooltips/manifest.toml
Labels: size-small

#4593 [Testing] Title Edit v3.0.1.1
  testing/live/TitleEdit/manifest.toml
Labels: size-small

#4592 Tracky 1.5.4.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#4591 MacroMate 1.0.19.2
  stable/MacroMate/manifest.toml
Labels: size-small

#4589 Pet Nicknames v2.2.0.4
  stable/PetRenamer/manifest.toml
Labels: size-small

#4588 SimpleMarketBoard 1.8.0.0
  stable/SimpleMarketBoard/manifest.toml
Labels: size-small

#4586 [Stable] SelfCare v0.2.0
  stable/SelfCare/images/icon.png
  stable/SelfCare/manifest.toml
  testing/live/SelfCare/manifest.toml
Labels: move channel, size-small

#4585 [Testing] Pathfinder v0.1.2
  testing/live/Pathfinder/manifest.toml
Labels: size-small

#4583 [Testing] Scout Helper v1.7.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#4590 [Testing] Malmstone Calculator 1.0.7.0
  testing/live/Malmstone/manifest.toml
Labels: size-mid

#4598 Avant-Garde v0.1.2.0
  stable/AvantGarde/manifest.toml
Labels: size-small

#4599 MacroMate 1.0.19.3
  stable/MacroMate/manifest.toml
Labels: size-small

#4600 SimpleMarketBoard 1.9.0.0
  stable/SimpleMarketBoard/manifest.toml
Labels: size-small

#4602 ChatTranslated 3.2.1.1
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4603 Simple Tweaks 1.10.2.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#4594 [Testing] DragoonMayCry v0.12.2.1
  testing/live/DragoonMayCry/manifest.toml
Labels: size-mid

#4597 SonarPlugin v0.6.6.0
  stable/SonarPlugin/manifest.toml
Labels: size-mid

#4595 [Testing] Altoholic 0.0.0.13
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#4601 [testing] PvP Tracker v.2.1.7.0
  testing/live/PvpStats/manifest.toml
Labels: size-large

#4596 Tracky 1.5.5.1
  stable/TrackyTrack/manifest.toml
Labels: size-large

#4604 ChatTranslated 3.2.1.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4605 SimpleMarketBoard 1.9.3.0
  stable/SimpleMarketBoard/manifest.toml
Labels: size-small

#4607 MacroMate 1.0.19.4
  stable/MacroMate/manifest.toml
Labels: size-small

#4608 Title Edit v3.0.1.2
  stable/TitleEdit/manifest.toml
Labels: size-large

#4606 [Testing] DragoonMayCry v0.12.2.5
  testing/live/DragoonMayCry/manifest.toml
Labels: size-mid

#4609 SubmarineTracker 1.9.2.6
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#4610 Tracky 1.5.5.2
  stable/TrackyTrack/manifest.toml
Labels: size-small

#4611 [Testing] AutoTimer v1.1.0.1
  testing/live/AutoTimer/manifest.toml
Labels: size-small

#4612 MonsterLootHunter 1.2.21.7
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#4614 Simple Tweaks 1.10.3.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#4613 PvP Tracker v2.1.7.0
  stable/PvpStats/manifest.toml
Labels: size-large

#4615 Allagan Market 1.0.0.6
  stable/AllaganMarket/manifest.toml
Labels: size-small

#4619 Wordsmith V1.15.1
  stable/Wordsmith/manifest.toml
Labels: size-small

#4620 [Testing] UsedName v0.8.5.0
  testing/live/UsedName/manifest.toml
Labels: size-mid

#4628 Tracky 1.5.5.3
  stable/TrackyTrack/manifest.toml
Labels: size-small

#4626 Umbra 2.2.37
  stable/Umbra/manifest.toml
Labels: size-small

#4625 [Testing] UsedName v0.8.5.1
  testing/live/UsedName/manifest.toml
Labels: size-small

#4624 Lights, Camera, Action! v1.0.0 (Stable)
  stable/CameraLoader/images/icon.png
  stable/CameraLoader/manifest.toml
Labels: move channel, size-small

#4623 TitleEdit v3.0.2.0
  stable/TitleEdit/manifest.toml
Labels: size-small

#4621 Malmstone Calculator 1.0.7.1
  stable/Malmstone/images/icon.png
  stable/Malmstone/manifest.toml
Labels: move channel, size-small

#4622 [testing] PvP Tracker v2.1.8.0
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#4627 [Testing] DragoonMayCry v0.13.2.0
  testing/live/DragoonMayCry/manifest.toml
Labels: size-large

#4629 Chat Proximity 1.1.0
  stable/ChatProximity/manifest.toml
Labels: size-small

#4630 [Stable] PlayerTrack v3.4.8
  stable/PlayerTrack/manifest.toml
Labels: size-small

#4631 hunt helper 1.0.0.24
  stable/HuntHelper/manifest.toml
Labels: size-large

#4632 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small
