Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-06, with the labels that each got.

#3564 MBHistory 1.0.0.3
  stable/MBHistory/manifest.toml
Labels: size-small

#3567 fungah 1.0.0.3
  stable/Fungah/manifest.toml
Labels: size-small

#3560 Update AutoMountBgm (stable)
  stable/AutoMountBgm/manifest.toml
Labels: size-mid

#3566 [testing] PvP Tracker v.2.0.1.0
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#3559 ChatTranslated v2.1.1.4
  stable/ChatTranslated/manifest.toml
Labels: size-mid

#3563 Currency Tracker 1.3.6.0
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#3569 ChatTranslated v2.1.2.0
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3571 [Stable] ItemVendorLocation 2.6.0.1
  stable/ItemVendorLocation/manifest.toml
Labels: size-small

#3570 Chatter 0.3.0.2
  testing/live/Chatter/manifest.toml
Labels: size-small

#3572 VFXEditor v1.8.3.8
  stable/VFXEditor/manifest.toml
Labels: size-large

#3565 [Testing] ReadyCheckHelper 1.0.5.0
  testing/live/ReadyCheckHelper/images/icon.png
  testing/live/ReadyCheckHelper/images/image1.png
  testing/live/ReadyCheckHelper/images/image2.png
  testing/live/ReadyCheckHelper/manifest.toml
Labels: move channel, size-large

#3573 [testing] PvP Tracker v2.0.2.0
  testing/live/PvpStats/manifest.toml
Labels: size-small

#3574 [Testing] Allagan Tools v1.7.0.3
  testing/live/InventoryTools/manifest.toml
Labels: size-small

#3576 Tracky 1.5.0.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#3575 ChatTranslated v2.1.2.1
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3577 [testing] PvP Tracker v2.0.2.1
  testing/live/PvpStats/manifest.toml
Labels: size-small

#3579 easy-translate-2-1-2
  stable/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-small

#3580 TextToTalk v1.30.0
  stable/TextToTalk/manifest.toml
Labels: size-large

#3583 Allagan Tools v1.7.0.5
  stable/InventoryTools/manifest.toml
Labels: size-mid

#3582 SubmarineTracker 1.8.5.0
  testing/live/SubmarineTracker/manifest.toml
Labels: size-large

#3556 [Testing] XIVInstantMessenger 1.4.0.2
  testing/live/Messenger/manifest.toml
Labels: size-large

#3600 SimpleMarketBoard 1.6.0.0
  stable/SimpleMarketBoard/manifest.toml
Labels: size-small

#3587 TextToTalk v1.30.1
  stable/TextToTalk/manifest.toml
Labels: size-small

#3593 update MagitekStratagem v0.4.0.0
  stable/MagitekStratagem/manifest.toml
  testing/live/MagitekStratagem/images/icon.png
  testing/live/MagitekStratagem/manifest.toml
Labels: size-small

#3595 [Testing] Who's Talking 0.6.10.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#3594 [Testing] XIVInstantMessenger 1.4.0.3
  testing/live/Messenger/manifest.toml
Labels: size-mid

#3598 [Testing] WaymarkPreset 1.5.0.0
  testing/live/WaymarkPresetPlugin/images/icon.png
  testing/live/WaymarkPresetPlugin/images/image1.png
  testing/live/WaymarkPresetPlugin/images/image2.png
  testing/live/WaymarkPresetPlugin/images/image3.png
  testing/live/WaymarkPresetPlugin/manifest.toml
Labels: move channel, size-small

#3597 Allagan Tools v1.7.0.6
  stable/InventoryTools/manifest.toml
Labels: size-small

#3596 PushyFinder 1.2.0.0
  stable/PushyFinder/manifest.toml
Labels: size-large

#3599 ChatTwo 1.26.0
  stable/ChatTwo/manifest.toml
Labels: size-large

#3590 ReadyCheckHelper 1.0.6.0
  stable/ReadyCheckHelper/manifest.toml
Labels: size-large

#3586 PlayerTrack v3.3.0.0
  testing/live/PlayerTrack/manifest.toml
Labels: size-large

#3591 [testing] PvP Tracker v2.0.3.0
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#3604 Accountant 1.4.1.0
  stable/Accountant/manifest.toml
Labels: size-small

#3605 Himbeertoni Raid Tool 1.5.3.0
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#3602 ChatTwo 1.26.2
  stable/ChatTwo/manifest.toml
Labels: size-small

#3606 SubmarineTracker 1.9.0.3
  testing/live/SubmarineTracker/manifest.toml
Labels: size-small

#3607 PlayerTrack v3.3.1.0
  testing/live/PlayerTrack/manifest.toml
Labels: size-mid

#3603 HuntHelper v1.0.0.16
  stable/HuntHelper/manifest.toml
Labels: size-mid

#3612 [testing] PvP Tracker v2.0.4.0
  testing/live/PvpStats/manifest.toml
Labels: size-mid

#3610 PlayerTrack v3.3.2.0
  stable/PlayerTrack/manifest.toml
Labels: size-large

#3613 hunthelper 1.0.0.17
  stable/HuntHelper/manifest.toml
Labels: size-small

#3614 PlayerTrack v3.3.3.0
  stable/PlayerTrack/manifest.toml
Labels: size-small

#3615 QoL Bar v2.3.2.3
  stable/QoLBar/manifest.toml
Labels: size-small

#3618 ChatTranslated v2.1.2.3
  stable/ChatTranslated/manifest.toml
Labels: size-small

#3619 PvP Tracker v2.0.4.1
  stable/PvpStats/manifest.toml
Labels: size-large

#3625 MacroMate 1.0.11.1
  stable/MacroMate/manifest.toml
Labels: size-small

#3623 Update EngageTimer v2.3.4.0
  stable/EngageTimer/manifest.toml
Labels: size-small

#3608 Update Orange Guidance Tomestone to 1.8.0
  stable/OrangeGuidanceTomestone/manifest.toml
Labels: size-mid

#3626 ChatTwo 1.26.3
  stable/ChatTwo/manifest.toml
Labels: size-small

#3628 WaymarkPresetPlugin 1.5.1.0
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-mid

#3627 SubmarineTracker 1.9.1.0
  stable/SubmarineTracker/manifest.toml
Labels: size-large

#3629 MagitekStratagem v0.4.1.0 - fix overlays in multi-monitor windows mode
  stable/MagitekStratagem/manifest.toml
Labels: size-small

#3630 MagitekStratagem v0.4.2.0
  stable/MagitekStratagem/manifest.toml
Labels: size-small

#3632 PriceInsight 2.8.0.1
  stable/PriceInsight/manifest.toml
Labels: size-small

#3633 TickTracker 1.4.4.0
  stable/TickTracker/manifest.toml
Labels: size-small

#3634 ChatTwo 1.26.4
  stable/ChatTwo/manifest.toml
Labels: size-small

#3635 [stable] WorkshopOptimizerPlugin v0.2.8.4
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-small

#3639 Tracky 1.5.0.1
  stable/TrackyTrack/manifest.toml
Labels: size-small

#3640 Update AutoMountBgm (stable)
  stable/AutoMountBgm/manifest.toml
Labels: size-small

#3641 SonarPlugin v0.6.3.4
  stable/SonarPlugin/manifest.toml
Labels: size-mid

#3642 hunthelper 1.0.0.18
  stable/HuntHelper/manifest.toml
Labels: size-small
