Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-08, with the labels that each got.

#4247 [Testing] Altoholic 0.0.0.5
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4249 Simple Tweaks 1.10.0.4
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#4250 [Testing] Glamaholic 1.10.7
  testing/live/Glamaholic/manifest.toml
Labels: size-small

#4251 Umbra 2.2.4
  stable/Umbra/manifest.toml
Labels: size-small

#4254 Himbeertoni Raid Tool 1.6.2.6
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#4257 Umbra 2.2.5 (Redundant code cleanup)
  stable/Umbra/manifest.toml
Labels: size-small

#4256 Distance 1.1.3.0
  stable/Distance/manifest.toml
Labels: size-small

#4255 [Testing] Gauge-O-Matic 0.7.0.10
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#4259 PetScale 2.0.1.0 stable
  stable/PetScale/manifest.toml
Labels: size-large

#4260 [Testing] Update FCNameColor to 5.0.1.0
  testing/live/FCNameColor/manifest.toml
Labels: size-mid

#4261 ChatTranslated v3.1.0.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4262 [Testing] Gauge-O-Matic 0.7.0.11
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#4263 MacroMate 1.0.16.0
  stable/MacroMate/manifest.toml
Labels: size-small

#4264 PriceInsight 2.11.0.0
  stable/PriceInsight/manifest.toml
Labels: size-small

#4265 Umbra 2.2.6
  stable/Umbra/manifest.toml
Labels: size-large

#4268 [Testing] Glamaholic 1.10.8
  testing/live/Glamaholic/manifest.toml
Labels: size-small

#4269 Mappy v3.0.1.4
  stable/Mappy/manifest.toml
Labels: size-small

#4270 Himbeertoni Raid Tool 1.6.2.7
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-mid

#4271 DelvUI release 2.2.0.9
  stable/DelvUI/manifest.toml
Labels: size-small

#4274 JobBars v1.3.1.4
  stable/JobBars/manifest.toml
Labels: size-small

#4273 [Testing] Glamaholic 1.10.9
  testing/live/Glamaholic/manifest.toml
Labels: size-small

#4275 Update FCNameColor to 5.0.1.0
  stable/FCNameColor/manifest.toml
Labels: size-small

#4276 [testing] Map Party Assist v2.3.0.0
  testing/live/MapPartyAssist/manifest.toml
Labels: size-mid

#4278 [Testing] TooltipNotes 1.4.0.0
  testing/live/TooltipNotes/manifest.toml
Labels: size-small

#4279 Umbra 2.2.7
  stable/Umbra/manifest.toml
Labels: size-large

#4277 [Testing] Pet Nicknames v2.0.0.5
  testing/live/PetRenamer/manifest.toml
Labels: completed-code-review, big, size-large, pending-testing

#4281 [Testing] Dalamud-OBS 1.0.4.1
  testing/live/OBSPlugin/images/icon.png
  testing/live/OBSPlugin/manifest.toml
Labels: move channel, size-mid

#4282 Glamaholic 1.10.9 Testing -> Stable
  stable/Glamaholic/manifest.toml
Labels: size-mid

#4280 Chatter Updated to v1.2.0--events
  stable/Chatter/manifest.toml
Labels: size-large

#4288 Echoglossian v3.11.x Released!
  stable/Echoglossian/manifest.toml
Labels: size-mid

#4287 Umbra 2.2.8
  stable/Umbra/manifest.toml
Labels: size-small

#4286 [Testing] Pet nicknames v2.0.0.6
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#4285 [Testing] Altoholic 0.0.0.6
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#4284 MacroMate 1.0.17.0
  stable/MacroMate/manifest.toml
Labels: size-small

#4283 Allagan Tools 1.7.0.20
  stable/InventoryTools/manifest.toml
Labels: size-small

#4289 Umbra 2.2.9
  stable/Umbra/manifest.toml
Labels: size-mid

#4290 Echoglossian v3.12.x Released
  stable/Echoglossian/manifest.toml
Labels: size-small

#4296 NoTankYou v7.0.2.0
  testing/live/NoTankYou/manifest.toml
Labels: size-small

#4295 Mappy v3.0.1.5
  stable/Mappy/manifest.toml
Labels: size-small

#4293 CurrencyAlert v2.0.1.0
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#4292 EzMiniCactpot v2.0.0.1
  stable/MiniCactpotSolver/manifest.toml
Labels: size-small

#4291 SortaKinda v2.0.0.4
  stable/SortaKinda/manifest.toml
Labels: size-small

#4294 DailyDuty v5.0.2.0
  testing/live/DailyDuty/manifest.toml
Labels: size-mid

#4297 Mappy v3.0.1.6
  stable/Mappy/manifest.toml
Labels: size-small

#4298 Umbra 2.2.10
  stable/Umbra/manifest.toml
Labels: size-small

#4299 Umbra 2.2.11
  stable/Umbra/manifest.toml
Labels: size-small

#4300 ReadyCheckHelper 1.0.7.5
  stable/ReadyCheckHelper/manifest.toml
Labels: size-small

#4301 ChatTwo 1.28.0
  stable/ChatTwo/manifest.toml
Labels: size-small

#4303 Mappy v3.0.1.7
  stable/Mappy/manifest.toml
Labels: size-small

#4302 [TESTING] xivcombo 1.8.5
  testing/live/XIVCombo/manifest.toml
Labels: size-small

#4304 Currency Tracker 1.4.3.0
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#4305 [Testing] Dalamud-OBS 1.0.4.2
  testing/live/OBSPlugin/manifest.toml
Labels: size-small

#4309 GatherBuddy 3.4.2.3
  stable/GatherBuddy/manifest.toml
Labels: size-small

#4307 Echoglossian v3.13.x Released
  stable/Echoglossian/manifest.toml
Labels: size-small

#4306 ffxiv2mqtt 1.0.6.0
  testing/live/Ffxiv2Mqtt/images/icon.png
  testing/live/Ffxiv2Mqtt/manifest.toml
Labels: move channel, size-small

#4308 Umbra 2.2.12
  stable/Umbra/manifest.toml
Labels: size-mid

#4312 Umbra 2.2.13
  stable/Umbra/manifest.toml
Labels: size-mid

#4311 [Testing] Pet Nicknames v2.1.0.0
  testing/live/PetRenamer/manifest.toml
Labels: size-large

#4313 Umbra 2.2.14 (Minor hotfix)
  stable/Umbra/manifest.toml
Labels: size-small

#4315 ChatTranslated 3.1.0.3
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4314 [Testing] Gauge-O-Matic 0.8.0.0
  testing/live/GaugeOMatic/manifest.toml
Labels: size-large

#4316 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small

#4317 Map Party Assist v2.3.0.0
  stable/MapPartyAssist/manifest.toml
Labels: size-mid

#4320 [Testing] Altoholic 0.0.0.7
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4321 Better Mount Roulette 1.4.0.17
  stable/BetterMountRoulette/manifest.toml
Labels: size-small

#4044 [Testing] WTSync 0.8.0.0
  testing/live/WTSync/images/icon.png
  testing/live/WTSync/images/image1.png
  testing/live/WTSync/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4324 Map Party Assist v2.3.1.0
  stable/MapPartyAssist/manifest.toml
Labels: size-small

#4325 Update Visibility (stable)
  stable/Visibility/manifest.toml
Labels: size-small

#4326 DelvUI release 2.2.0.10
  stable/DelvUI/manifest.toml
Labels: size-small

#4327 [Testing] Altoholic 0.0.0.8
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4330 MacroMate 1.0.17.1
  stable/MacroMate/manifest.toml
Labels: size-small

#4328 Umbra 2.2.15
  stable/Umbra/manifest.toml
Labels: size-large

#4331 [Testing] WTSync 0.8.1.0
  testing/live/WTSync/manifest.toml
Labels: size-small

#4332 [Testing] Pet Nicknames v2.1.0.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#4334 Himbeertoni Raid Tool 1.6.2.8
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#4335 [Testing] Scout Helper v1.5.4.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#4337 Umbra 2.2.16
  stable/Umbra/manifest.toml
Labels: size-small

#4329 WinTitle adoption
  stable/WinTitle/manifest.toml
Labels: size-small

#4345 ffxiv2mqtt 1.0.6.1
  stable/Ffxiv2Mqtt/manifest.toml
  testing/live/Ffxiv2Mqtt/images/icon.png
  testing/live/Ffxiv2Mqtt/manifest.toml
Labels: size-small

#4343 NoTankYou v7.0.2.1
  stable/NoTankYou/manifest.toml
Labels: size-small

#4342 [Testing] Scout Helper v1.5.5.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#4341 MacroMate 1.0.17.2
  stable/MacroMate/manifest.toml
Labels: size-small

#4338 Mappy v3.0.1.8
  stable/Mappy/manifest.toml
Labels: size-small

#4347 NeatNoter 2.6.1
  stable/NeatNoter/manifest.toml
Labels: size-small

#4340 Echoglossian v3.14.x Released!
  stable/Echoglossian/manifest.toml
Labels: size-mid

#4346 [Testing] Pet Nicknames v2.1.1.0
  testing/live/PetRenamer/manifest.toml
Labels: size-mid

#4348 Mappy v3.0.2.0
  stable/Mappy/manifest.toml
Labels: size-small

#4350 DelvUI release 2.2.1.0
  stable/DelvUI/manifest.toml
Labels: size-small

#4352 NeatNoter 2.6.2
  stable/NeatNoter/manifest.toml
  testing/live/NeatNoter/manifest.toml
Labels: size-small

#4353 [Testing] WTSync v0.9.0.0
  testing/live/WTSync/manifest.toml
Labels: size-small

#4355 Mappy v3.0.3.0
  stable/Mappy/manifest.toml
Labels: size-small

#4356 DailyDuty v5.0.3.0
  stable/DailyDuty/manifest.toml
Labels: size-small

#4357 [Testing] Pet Nicknames v2.1.1.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#4358 WinTitle 1.1.0.0
  stable/WinTitle/manifest.toml
Labels: size-small

#4360 OfDungeonsDeep v1.0.1.0
  stable/OfDungeonsDeep/manifest.toml
Labels: size-small

#4349 MonsterDex 2.11.1
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#4361 DailyDuty v5.0.3.1
  stable/DailyDuty/manifest.toml
Labels: size-small

#4362 Mappy v3.0.3.1
  stable/Mappy/manifest.toml
Labels: size-small

#4363 WinTitle 1.1.1.0
  stable/WinTitle/manifest.toml
Labels: size-small

#4354 Umbra 2.2.17
  stable/Umbra/manifest.toml
Labels: size-mid

#4364 XIVCombo 1.8.5
  stable/XIVCombo/manifest.toml
  testing/live/XIVCombo/images/icon.png
  testing/live/XIVCombo/manifest.toml
Labels: size-mid

#4365 DailyDuty v5.0.3.2
  stable/DailyDuty/manifest.toml
Labels: size-small

#4366 [Testing] Pet Nicknames v2.1.1.2
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#4368 DelvUI release 2.2.1.1
  stable/DelvUI/manifest.toml
Labels: size-small

#4369 DailyDuty v5.0.3.3
  stable/DailyDuty/manifest.toml
Labels: size-small

#4371 DailyDuty v5.0.3.4
  stable/DailyDuty/manifest.toml
Labels: size-small

#4374 [Testing] Altoholic 0.0.0.10
  testing/live/Altoholic/manifest.toml
Labels: size-small

#4373 [Testing] Scout Helper v1.6.0.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#4372 WinTitle 1.1.2.0
  stable/WinTitle/manifest.toml
Labels: size-small

#4339 XIVInstantMessenger 1.4.0.8
  stable/Messenger/manifest.toml
Labels: size-small

#4359 [Testing] Gauge-O-Matic 0.8.0.2
  testing/live/GaugeOMatic/manifest.toml
Labels: size-large

#4376 MonsterDex 2.11.2
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#4378 [Testing] Gauge-O-Matic 0.8.0.3
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#4367 Umbra 2.2.18
  stable/Umbra/manifest.toml
Labels: size-mid

#4197 [Testing] ZDs 1.0.0.0
  testing/live/ZDs/images/icon.png
  testing/live/ZDs/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3937 [Testing] Bartender 1.0
  testing/live/Bartender/images/icon.png
  testing/live/Bartender/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#3946 [Testing] ChatProximity 0.0.6
  testing/live/ChatProximity/images/icon.png
  testing/live/ChatProximity/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4052 [Testing] GraphicsConfig 1.0
  testing/live/GraphicsConfig/images/icon.png
  testing/live/GraphicsConfig/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4059 [Testing] Toastingway v1.0.0
  testing/live/ToastingwayPlugin/images/icon.png
  testing/live/ToastingwayPlugin/manifest.toml
Labels: new plugin, size-large, pending-code-review, completed-rules-compliance, completed-testing

#4379 Umbra 2.2.19
  stable/Umbra/manifest.toml
Labels: size-mid

#4382 Umbra 2.2.20 (Fixes a CTD)
  stable/Umbra/manifest.toml
Labels: size-small

#4381 HuntHelper 1.0.0.22
  stable/HuntHelper/manifest.toml
Labels: size-small

#4380 DailyDuty v5.0.3.5
  stable/DailyDuty/manifest.toml
Labels: size-small

#4383 XIVControllerToggle re-adoption and bugfix
  stable/XIVControllerToggle/manifest.toml
Labels: size-mid

#4384 ChatTwo 1.28.1
  stable/ChatTwo/manifest.toml
Labels: size-small

#4385 [Testing] Gauge-O-Matic 0.8.0.4
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#4386 Umbra 2.2.21
  stable/Umbra/manifest.toml
Labels: size-large

#4388 Eventy 1.0.1.0
  stable/Eventy/manifest.toml
Labels: size-small

#4389 Tracky 1.5.2.5
  stable/TrackyTrack/manifest.toml
Labels: size-small

#4390 Party Icons v1.2.1.0
  stable/PartyIcons/manifest.toml
Labels: size-small

#4387 Pet Nicknames v2.1.1.3
  stable/PetRenamer/manifest.toml
Labels: size-large

#3592 [testing] Dynamic UI Scaling 0.0.0.1
  testing/live/DynamicUIScaling/images/icon.png
  testing/live/DynamicUIScaling/manifest.toml
Labels: new plugin, completed-code-review, size-large, pending-testing, completed-rules-compliance

#4391 DelvUI release 2.2.1.2
  stable/DelvUI/manifest.toml
Labels: size-small

#4392 [Testing] Scout Helper v1.6.1.0
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#4393 Graphics Config update 1.0.0.1
  testing/live/GraphicsConfig/manifest.toml
Labels: size-small

#4394 Umbra 2.2.22
  stable/Umbra/manifest.toml
Labels: size-mid

#4201 [Testing] CleanHuntChat 1.0
  testing/live/CleanHuntChat/images/icon.png
  testing/live/CleanHuntChat/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4395 [Testing] Chat Proximity 0.0.8
  testing/live/ChatProximity/manifest.toml
Labels: size-small

#4396 Mappy v3.0.3.2
  stable/Mappy/manifest.toml
Labels: size-small

#4397 [Testing] Chat Proximity 0.0.9
  testing/live/ChatProximity/manifest.toml
Labels: size-small

#4398 ChatTranslated 3.1.0.4
  stable/ChatTranslated/manifest.toml
Labels: size-small

#4399 [Stable] Move beegwindow to stable
  stable/BeegWindow/images/icon.png
  stable/BeegWindow/manifest.toml
Labels: move channel, size-small

#4377 [Testing] Directional 0.0.1
  testing/live/Directional/images/icon.png
  testing/live/Directional/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4272 Glamour spam remover
  testing/live/GlamourSpamRemover/images/icon.png
  testing/live/GlamourSpamRemover/images/image1.png
  testing/live/GlamourSpamRemover/images/image2.png
  testing/live/GlamourSpamRemover/manifest.toml
Labels: new plugin, completed-code-review, size-mid, completed-rules-compliance, completed-testing

#4336 Add launchpadhotbars to testing
  testing/live/LaunchpadHotbars/images/icon.png
  testing/live/LaunchpadHotbars/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4375 [Testing] Item Use 0.9.0.0
  testing/live/ItemUse/images/icon.png
  testing/live/ItemUse/images/image1.png
  testing/live/ItemUse/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4400 Pet Nicknames v2.1.1.4
  stable/PetRenamer/manifest.toml
Labels: size-small

#4402 Pet Nicknames v2.1.2.0
  stable/PetRenamer/manifest.toml
Labels: size-small

#4403 Umbra 2.2.23
  stable/Umbra/manifest.toml
Labels: size-small

#4404 [Testing] Lights, Camera, Action! v0.2.2.0
  testing/live/CameraLoader/manifest.toml
Labels: size-mid
