Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-01, with the labels that each got.

#3062 Himbeertoni Raid Tool 1.5.0.1
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#3063 Tracky 1.3.4.8
  stable/TrackyTrack/manifest.toml
Labels: size-large

#3064 SonarPlugin v0.6.1.0
  stable/SonarPlugin/manifest.toml
Labels: size-large

#3060 Pet Nicknames v1.4.5.3
  stable/PetRenamer/manifest.toml
Labels: size-mid

#3068 [Testing] Who's Talking 0.6.6.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#3066 chore. Move FFXIVRPCalendarPlugin to stable, remove PluginLog references.
  stable/FFXIVRPCalendarPlugin/images/icon.png
  stable/FFXIVRPCalendarPlugin/manifest.toml
Labels: move channel, size-small

#3065 Pet Nicknames 1.4.5.4
  stable/PetRenamer/manifest.toml
Labels: size-small

#3067 TickTracker 1.3.0.0
  stable/TickTracker/manifest.toml
Labels: size-small

#3071 Distant Seas 1.0.0.4
  stable/DistantSeas/manifest.toml
Labels: size-small

#3072 [Testing] HUDManager 2.5.18.3
  testing/live/HUDManager/manifest.toml
Labels: size-small

#3073 SonarPlugin v0.6.1.1
  stable/SonarPlugin/manifest.toml
Labels: size-small

#3075 SubmarineTracker 1.8.2.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3076 Tracky 1.3.4.9
  stable/TrackyTrack/manifest.toml
Labels: size-large

#3077 [Testing] Pet Nicknames v1.4.6.0
  testing/live/PetRenamer/images/icon.png
  testing/live/PetRenamer/manifest.toml
Labels: move channel, size-small

#3074 Update Eorzea Votes to 1.2.0
  stable/EorzeaVotes/manifest.toml
Labels: size-mid

#3078 Mappy v1.0.7.3
  stable/Mappy/manifest.toml
Labels: size-small

#3079 SubmarineTracker 1.8.2.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3080 Currency Tracker 1.3.3.6
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3081 [testing] MapPartyAssist v2.0.0.0
  testing/live/MapPartyAssist/manifest.toml
Labels: size-large

#3084 Pet Nicknames v1.4.6.0
  stable/PetRenamer/manifest.toml
Labels: size-small

#3082 XIVLogger 1.0.6.0
  stable/XIVLogger/manifest.toml
Labels: size-small

#3083 SubmarineTracker 1.8.2.2
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#3086 Title Edit 2.2.6.13 -> 2.2.7.0
  testing/live/TitleEdit/images/icon.png
  testing/live/TitleEdit/images/image1.png
  testing/live/TitleEdit/images/image2.png
  testing/live/TitleEdit/images/image3.png
  testing/live/TitleEdit/images/image4.png
  testing/live/TitleEdit/manifest.toml
Labels: move channel, size-small

#3088 PrefPro 1.2.0.7 -> 1.2.1.0
  testing/live/PrefPro/images/icon.png
  testing/live/PrefPro/images/image1.png
  testing/live/PrefPro/manifest.toml
Labels: move channel, size-mid

#3089 DeepDungeonDex 2.9.0
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#3090 DeepDungeonDex 2.9.1
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#3094 [Testing] Pet Nicknames v1.4.6.1
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#3095 SubmarineTracker 1.8.2.4
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#3098 DeepDungeonDex 2.9.2
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#3100 NoTankYou v6.0.2.1
  stable/NoTankYou/manifest.toml
Labels: size-small

#3096 Target Lines 1.4.0.0
  stable/TargetLines/manifest.toml
Labels: size-large

#3099 Currency Tracker 1.3.3.8
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#3092 Who's Talking 0.6.7.0
  stable/WhosTalking/images/icon.png
  stable/WhosTalking/manifest.toml
  testing/live/WhosTalking/manifest.toml
Labels: move channel, size-large

#3101 BetterShadows 1.3.0.0
  stable/BetterShadows/manifest.toml
Labels: size-mid

#3091 Allagan Tools v1.6.2.2
  stable/InventoryTools/manifest.toml
Labels: size-mid

#3102 DeepDungeonDex 2.9.3
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#3103 SortaKinda v1.0.4.7
  stable/SortaKinda/manifest.toml
Labels: size-small

#3107 Update Eorzea Votes to 1.2.1
  stable/EorzeaVotes/manifest.toml
Labels: size-small

#3105 [Testing] MapPartyAssist v2.1.0.0
  testing/live/MapPartyAssist/manifest.toml
Labels: size-large

#3108 [stable] WorkshopOptimizerPlugin 0.2.8.3
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-small

#3106 Currency Tracker 1.3.3.9
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#3109 [Testing] TooltipNotes 1.3.0.0
  testing/live/TooltipNotes/manifest.toml
Labels: size-small

#3114 DeepDungeonDex 2.9.4
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#3113 Currency Tracker 1.3.4.0
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3112 Update EngageTimer v2.3.1.1
  stable/EngageTimer/manifest.toml
Labels: size-large

#3115 TextToTalk v1.28.8
  stable/TextToTalk/manifest.toml
Labels: size-small

#3117 [Testing] TooltipNotes 1.3.0.1
  testing/live/TooltipNotes/manifest.toml
Labels: size-small

#3118 [Testing] HUDManager 2.5.18.4
  testing/live/HUDManager/manifest.toml
Labels: size-small

#3119 Pet Nicknames v1.4.6.1
  stable/PetRenamer/manifest.toml
Labels: size-small

#3120 Currency Tracker 1.3.4.1
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#3121 Honorific 1.4.2.0
  stable/Honorific/manifest.toml
Labels: size-small

#3126 SortaKinda v1.0.4.8
  stable/SortaKinda/manifest.toml
Labels: size-small

#3124 XIVLogger 1.0.6.1
  stable/XIVLogger/manifest.toml
Labels: size-small

#3122 BetterPlaytime 1.4.0.4
  stable/BetterPlaytime/manifest.toml
Labels: size-small

#3128 Coordinate Importer v1.1.0.3
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#3125 MapPartyAssist 2.1.0.0
  stable/MapPartyAssist/manifest.toml
Labels: size-large

#3123 Tracky 1.4.0.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#3130 OofPlugin v1.3.0.0
  stable/OofPlugin/images/icon.png
  stable/OofPlugin/manifest.toml
  testing/live/OofPlugin/manifest.toml
Labels: move channel, size-small

#3132 BetterShadows 1.3.1.0
  stable/BetterShadows/manifest.toml
Labels: size-small

#3136 [Testing] TooltipNotes 1.3.0.2
  testing/live/TooltipNotes/manifest.toml
Labels: size-small

#3135 Pet Nicknames v1.4.6.2
  stable/PetRenamer/manifest.toml
Labels: size-small

#3134 BetterShadows 1.3.2.0
  stable/BetterShadows/manifest.toml
Labels: size-small

#3127 GatherBuddy 3.3.1.0
  stable/GatherBuddy/manifest.toml
Labels: size-small

#3137 BetterShadows 1.3.3.0
  stable/BetterShadows/manifest.toml
Labels: size-small

#3139 [Stable] AutoTimer v1.0.0.3
  stable/AutoTimer/images/icon.png
  stable/AutoTimer/manifest.toml
Labels: move channel, size-small

#3145 IslandWorkshopSearch 0.0.0.3
  stable/IslandWorkshopSearch/manifest.toml
Labels: size-small

#3143 Tracky 1.4.0.1
  stable/TrackyTrack/manifest.toml
Labels: size-small

#3142 GatherBuddy 3.3.1.1
  stable/GatherBuddy/manifest.toml
Labels: size-small

#3140 TidyChat v.1.2.9 - Compatibility fix by Glyceri
  stable/TidyChat/manifest.toml
Labels: size-small

#3144 [Testing] Pet Nicknames v1.4.6.3
  testing/live/PetRenamer/manifest.toml
Labels: size-small

#3141 [Testing] Tilted v3.4.1.2
  testing/live/Tilted/manifest.toml
Labels: size-small

#3138 VFXEditor v1.8.2.0
  stable/VFXEditor/manifest.toml
Labels: size-large

#3146 hunthelper v1.0.0.14
  stable/HuntHelper/manifest.toml
Labels: size-small

#3147 WhoDidThat v1.4.0.0
  stable/WhoDidThat/manifest.toml
Labels: size-small
