Repository goatcorp/DalamudPluginsD17, pull requests merged in 2024-12, with the labels that each got.

#5095 [Testing] MonsterLootHunter 1.2.22.7
  testing/live/MonsterLootHunter/manifest.toml
Labels: size-large

#5146 Eureka Helper v2.0.0.1
  stable/EurekaHelper/manifest.toml
Labels: size-small

#5150 A Realm Recorded v1.0.1.2
  stable/ARealmRecorded/manifest.toml
Labels: size-small

#5147 Simple Tweaks 1.10.5.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#5145 [Testing] StanleyParableXiv 3.2.0.0
  testing/live/StanleyParableXiv/manifest.toml
Labels: size-mid

#5153 DailyDuty v5.2.1.2
  stable/DailyDuty/manifest.toml
Labels: size-small

#5149 Umbra 2.3.3
  stable/Umbra/manifest.toml
Labels: size-mid

#5154 AutoTimer v1.1.0.3
  stable/AutoTimer/manifest.toml
  testing/live/AutoTimer/manifest.toml
Labels: size-small

#5156 OofPlugin v1.3.3.0
  stable/OofPlugin/manifest.toml
Labels: size-small

#5152 Dalamud.RichPresence 2.0.6.4
  stable/Dalamud.RichPresence/manifest.toml
Labels: size-small

#5159 GlamourSpamRemover-1.2.3.0
  stable/GlamourSpamRemover/manifest.toml
Labels: size-small

#5164 Update Tidy Chat v2.0.11
  stable/TidyChat/manifest.toml
Labels: size-small

#5166 DailyDuty v5.2.1.3
  stable/DailyDuty/manifest.toml
Labels: size-small

#5165 NoTankYou v5.2.1.3
  stable/NoTankYou/manifest.toml
Labels: size-small

#5163 DragoonMayCry 1.2.3.4
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#5162 ChatTranslated 3.3.1.0
  stable/ChatTranslated/manifest.toml
Labels: size-small

#5160 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-small

#5158 Umbra 2.3.4
  stable/Umbra/manifest.toml
Labels: size-small

#5167 [Testing] WhereIsMyMouse v0.0.1.3
  testing/live/WhereIsMyMouse/manifest.toml
Labels: size-small

#5168 DailyDuty v5.2.1.4
  stable/DailyDuty/manifest.toml
Labels: size-small

#5170 Allagan Tools 1.11.0.4
  stable/InventoryTools/manifest.toml
Labels: size-large

#5172 DragoonMayCry 1.2.4.0
  stable/DragoonMayCry/manifest.toml
  testing/live/DragoonMayCry/images/icon.png
  testing/live/DragoonMayCry/manifest.toml
Labels: size-small

#5173 WTSync 0.15.0.0
  stable/WTSync/manifest.toml
Labels: size-small

#5174 Update The Heart of the Party to 1.0.8
  stable/TheHeartOfTheParty/manifest.toml
Labels: size-small

#5175 Update XIVChat to 1.7.10
  stable/XIVChat/manifest.toml
Labels: size-small

#5176 Update SoundFilter to 1.4.15
  stable/SoundFilter/manifest.toml
Labels: size-small

#5177 Allagan Tools 1.11.0.5
  stable/InventoryTools/manifest.toml
Labels: size-small

#5005 [Simple Todo] - API 11
  stable/SimpleTodo/manifest.toml
Labels: size-small

#5131 xivcombo 7.1
  stable/XIVCombo/manifest.toml
Labels: size-small

#5178 Allagan Tools 1.11.0.6
  stable/InventoryTools/manifest.toml
Labels: size-small

#5179 SubmarineTracker 1.9.5.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5180 MonsterLootHunter 1.2.23.7
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#5181 Battery Gauge 1.2.1
  stable/BatteryGauge/manifest.toml
Labels: size-small

#5182 [Testing] Gauge-O-Matic 0.8.1.4
  testing/live/GaugeOMatic/manifest.toml
Labels: size-mid

#5185 PvP Tracker v2.2.0.1
  stable/PvpStats/manifest.toml
Labels: size-small

#5184 Tippy 1.11.0.0
  stable/Tippy/manifest.toml
Labels: size-large

#5186 Bartender v1.1.5
  testing/live/Bartender/images/icon.png
  testing/live/Bartender/manifest.toml
Labels: size-small

#5189 Who's Talking 0.8.2.0
  stable/WhosTalking/manifest.toml
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#5190 Minesweeper 1.2.3.0
  stable/DalamudMinesweeper/manifest.toml
Labels: size-small

#5183 update beegwindow
  stable/BeegWindow/manifest.toml
Labels: size-small

#5194 Tf2CriticalHitsPlugin 3.6.0.1
  stable/Tf2CriticalHitsPlugin/manifest.toml
  testing/live/Tf2CriticalHitsPlugin/manifest.toml
Labels: size-small

#5195 Congratulations 1.3.1.1
  stable/Congratulations/manifest.toml
Labels: size-small

#5196 OfDungeonsDeep v1.0.3.0
  stable/OfDungeonsDeep/manifest.toml
Labels: size-mid

#5197 SillyChat v1.7.1.0
  stable/SillyChat/manifest.toml
Labels: size-mid

#5191 StanleyParableXiv 3.2.0.0
  stable/StanleyParableXiv/manifest.toml
Labels: size-mid

#5188 [ChatProximity] 1.3.0
  stable/ChatProximity/manifest.toml
Labels: size-mid

#5187 Title Edit v3.0.4.0
  stable/TitleEdit/manifest.toml
Labels: size-mid

#5198 Umbra 2.3.6
  stable/Umbra/manifest.toml
Labels: size-small

#5200 EasyEyes v1.3.0.1
  stable/EasyEyes/manifest.toml
Labels: size-small

#5201 ChatProximity 1.3.1
  stable/ChatProximity/manifest.toml
Labels: size-mid

#5202 StanleyParableXiv 3.2.1.0
  stable/StanleyParableXiv/manifest.toml
Labels: size-small

#5203 [Testing] StanleyParableXiv 3.2.1.0
  testing/live/StanleyParableXiv/manifest.toml
Labels: size-small

#5205 DeviceChangeFix v2.0.6
  stable/DeviceChangeFix/manifest.toml
Labels: size-small

#5209 Tracky 1.5.5.7
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5206 Tippy 1.11.0.1
  stable/Tippy/manifest.toml
Labels: size-small

#5208 Memory Marker 2.2.1.0
  stable/MemoryMarker/manifest.toml
  testing/live/MemoryMarker/manifest.toml
Labels: size-mid

#5210 TwitchXIV 1.0.0.4, the oauth update
  stable/TwitchXIV/manifest.toml
Labels: size-small

#5212 TwitchXIV 1.0.0.5
  stable/TwitchXIV/manifest.toml
Labels: size-small

#5211 [Testing] BurntToast 1.4.0
  testing/live/BurntToast/images/icon.png
  testing/live/BurntToast/manifest.toml
Labels: move channel, size-small

#5215 ChatAlerts 2.2.0.1
  stable/ChatAlerts/manifest.toml
Labels: size-small

#5216 RepairMe v1.0.1.17
  stable/RepairMe/manifest.toml
Labels: size-small

#5214 HUDUnlimited v1.1.0.1
  stable/HUDUnlimited/manifest.toml
Labels: size-small

#5218 Pet Nicknames v2.3.0.6
  stable/PetRenamer/manifest.toml
Labels: size-small

#5219 BetterTargetingSystem v0.0.12
  testing/live/BetterTargetingSystem/manifest.toml
Labels: size-small

#5220 Title Edit v3.0.4.1
  stable/TitleEdit/manifest.toml
Labels: size-small

#5221 Allagan Tools 1.11.0.7
  stable/InventoryTools/manifest.toml
Labels: size-small

#5224 Item Search v1.10.0.2
  stable/ItemSearchPlugin/manifest.toml
Labels: size-small

#5225 Dalamud.CharacterSync 2.0.0.11
  stable/Dalamud.CharacterSync/manifest.toml
Labels: size-small

#5229 ChatTwo 1.29.12
  stable/ChatTwo/manifest.toml
Labels: size-small

#5231 SubmarineTracker 1.9.5.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5230 ItemSearchPlugin v1.10.0.3
  stable/ItemSearchPlugin/manifest.toml
Labels: size-small

#5228 Pet Nicknames v2.3.0.7
  stable/PetRenamer/manifest.toml
Labels: size-small

#5232 Title Edit v3.0.4.2
  stable/TitleEdit/manifest.toml
Labels: size-small

#5227 BilingualTooltips 1.1.1.0
  stable/BilingualTooltips/manifest.toml
Labels: size-mid

#5233 Wholist v1.8.1.0
  stable/Wholist/manifest.toml
Labels: size-small

#5234 Update Tidy Chat v2.0.12
  stable/TidyChat/manifest.toml
Labels: size-small

#5236 Echoglossian v3.17.x Released
  stable/Echoglossian/manifest.toml
Labels: size-small

#5237 ItemVendorLocation v2.9.0.3
  stable/ItemVendorLocation/manifest.toml
Labels: size-small

#5238 VenueManager 2.4.1
  stable/VenueManager/manifest.toml
Labels: size-small

#5239 [Testing] Gauge-O-Matic 0.8.1.5
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#5241 BilingualTooltips 1.2.1.0
  stable/BilingualTooltips/images/image2.png
  stable/BilingualTooltips/images/image3.png
  stable/BilingualTooltips/manifest.toml
Labels: size-large

#5246 Title Edit v3.0.4.3
  stable/TitleEdit/manifest.toml
Labels: size-large

#5242 VenueManager 2.5.0
  stable/VenueManager/manifest.toml
Labels: size-large

#5243 EurekaLinker 1.5.2.0
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-large

#5245 GatherBuddy 3.5.1.0
  stable/GatherBuddy/manifest.toml
Labels: size-large

#5244 Allagan Tools 1.11.0.8
  stable/InventoryTools/manifest.toml
Labels: size-large

#5247 ItemSearch Plugin v1.10.1.0
  stable/ItemSearchPlugin/manifest.toml
Labels: size-large

#5248 ChatTwo 1.29.13
  stable/ChatTwo/manifest.toml
Labels: size-small

#5249 Allagan Tools 1.11.0.9
  stable/InventoryTools/manifest.toml
Labels: size-small

#5250 Allagan Market 1.1.0.2
  stable/AllaganMarket/manifest.toml
Labels: size-small

#5252 ChatTwo 1.29.14
  stable/ChatTwo/manifest.toml
Labels: size-small

#5253 Of Dungeons Deep v1.0.4.0
  stable/OfDungeonsDeep/manifest.toml
Labels: size-small

#5254 StackSellPrice 4.4.0
  stable/StackSellPrice/manifest.toml
Labels: size-small

#5255 Tracky 1.5.5.8
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5240 MOAction 4.4.0
  stable/MOAction/manifest.toml
Labels: size-large

#5256 Glamaholic 1.10.12
  stable/Glamaholic/manifest.toml
Labels: size-small

#5257 Tracky 1.5.5.9
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5258 [Testing] Altoholic v0.0.0.28
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5081 Add AFKMute to testing/live.
  testing/live/AFKMute/images/icon.png
  testing/live/AFKMute/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5259 StackSellPrice 4.4.1
  stable/StackSellPrice/manifest.toml
Labels: size-small

#4749 Mount Radio
  testing/live/MountRadio/images/blank
  testing/live/MountRadio/images/icon.png
  testing/live/MountRadio/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#4986 Quiet the Den 1.0
  testing/live/QuietDen/images/icon.png
  testing/live/QuietDen/manifest.toml
Labels: new plugin, completed-code-review, size-mid, completed-rules-compliance, completed-testing

#5169 Add BigNaelQuotes to testing
  testing/live/BigNaelQuotes/images/icon.png
  testing/live/BigNaelQuotes/manifest.toml
Labels: new plugin, completed-code-review, size-mid, pending-rules-compliance, completed-testing

#5260 [Testing] Altoholic v0.0.0.29
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5261 Tracky 1.5.5.10
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5262 SubmarineTracker 1.9.5.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5263 Umbra 2.3.7
  stable/Umbra/manifest.toml
Labels: size-small

#5265 Update MultiHit to 0.0.2.4
  stable/MultiHit/manifest.toml
Labels: size-small

#5266 Update OBSPlugin to 1.0.4.4
  stable/OBSPlugin/manifest.toml
Labels: size-small

#5264 Updating for 7.1
  testing/live/RpUtils/manifest.toml
Labels: size-small

#5267 ChatTwo 1.29.16
  stable/ChatTwo/manifest.toml
Labels: size-small

#5268 Echoglossian v3.18.x released
  stable/Echoglossian/manifest.toml
Labels: size-small

#5269 Echoglossian v3.19.x released
  stable/Echoglossian/manifest.toml
Labels: size-small

#5270 A Realm Recorded v1.0.1.3
  stable/ARealmRecorded/manifest.toml
Labels: size-small

#5271 Map Party Assist v2.4.1.0
  stable/MapPartyAssist/manifest.toml
Labels: size-mid

#5274 Avant-Garde v1.0.2
  stable/AvantGarde/manifest.toml
Labels: size-small

#5273 [Testing] PlayerTrack v3.4.10
  testing/live/PlayerTrack/manifest.toml
Labels: size-large

#5278 AbilityAnts 1.0.0.3
  stable/AbilityAnts/manifest.toml
Labels: size-small

#5275 Aether Compass v1.6.5.1
  testing/live/AetherCompass/manifest.toml
Labels: size-small

#5276 [Testing] PlayerTrack v3.4.11
  testing/live/PlayerTrack/manifest.toml
Labels: size-small

#5277 ScoutHelper v1.8.0
  stable/ScoutHelper/manifest.toml
Labels: size-small

#5279 Title Edit v3.0.4.4
  stable/TitleEdit/manifest.toml
Labels: size-small

#5280 MonsterDex 2.12.1
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#5281 Update PositionalGuide (stable)
  stable/PositionalGuide/manifest.toml
Labels: size-small

#5283 [Testing] PlayerTrack v3.4.12
  testing/live/PlayerTrack/manifest.toml
Labels: size-mid

#5282 Himbeertoni Raid Tool 1.8.0.0
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#4942 CurrencySpender Release
  testing/live/CurrencySpender/images/icon.png
  testing/live/CurrencySpender/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5193 [Testing] HUDLayoutHelper v1.0.0
  testing/live/HUDLayoutHelper/images/icon.png
  testing/live/HUDLayoutHelper/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5204 [Testing] ShopItemRevealer 1.0.0.0
  testing/live/ShopItemRevealer/images/icon.png
  testing/live/ShopItemRevealer/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5272 [Testing] Acquired Date 0.1.0.0
  testing/live/AcquisitionDate/images/icon.png
  testing/live/AcquisitionDate/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5251 RetainerSales Initial Evaluation
  testing/live/RetainerSales/images/icon.png
  testing/live/RetainerSales/manifest.toml
Labels: new plugin, completed-code-review, size-mid, pending-testing, completed-rules-compliance

#5284 Himbeertoni Raid Tool 1.8.0.1
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#5289 ShopItemRevealer 1.0.0.1
  testing/live/ShopItemRevealer/manifest.toml
Labels: size-small

#5285 NoTankYou v7.2.0.4
  stable/NoTankYou/manifest.toml
Labels: size-small

#5286 Acquisition Date 0.1.0.1
  testing/live/AcquisitionDate/manifest.toml
Labels: size-small

#5287 Eureka Helper v2.0.1.0
  stable/EurekaHelper/manifest.toml
Labels: size-small

#5288 Update Tourist to 1.2.16
  stable/Tourist/manifest.toml
Labels: size-small

#5290 NoTankYou v7.2.0.5
  stable/NoTankYou/manifest.toml
Labels: size-small

#5291 Eureka Helper v2.0.1.1
  stable/EurekaHelper/manifest.toml
Labels: size-small
