Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-04, with the labels that each got.

#5881 [BozjaBuddy] 1.1.6.6 - API bump. Modified the build script.
  stable/BozjaBuddy/manifest.toml
Labels: size-small

#5882 DeepDungeonTracker 1.0.1.2
  stable/DeepDungeonTracker/manifest.toml
Labels: size-small

#5883 Mappy v3.1.1.1
  stable/Mappy/manifest.toml
Labels: size-small

#5884 HuntHelper v1.0.0.28
  stable/HuntHelper/manifest.toml
Labels: size-small

#5885 JobBars v1.3.2.0
  stable/JobBars/manifest.toml
Labels: size-small

#5886 DailyDuty v5.2.2.1
  stable/DailyDuty/manifest.toml
Labels: size-small

#5888 ArchipelagoXIV: v0.23.2
  testing/live/ArchipelagoXIV/manifest.toml
Labels: size-small

#5887 DailyDuty v5.2.2.2
  stable/DailyDuty/manifest.toml
Labels: size-small

#5538 Wave Wrangler Testing Release
  testing/live/WaveWrangler/images/icon.png
  testing/live/WaveWrangler/manifest.toml
Labels: new plugin, completed-code-review, size-mid, completed-rules-compliance

#5551 [Testing] Fatal Frame v0.1.0.0
  testing/live/XivFatalFrame/images/icon.png
  testing/live/XivFatalFrame/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance

#5536 New Plugin: Quest Share
  testing/live/QuestShare/images/icon.png
  testing/live/QuestShare/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance

#5891 [Testing] FatalFrame 0.2.0.0
  testing/live/XivFatalFrame/manifest.toml
Labels: size-small

#5890 Browsingway 1.6.5.0
  stable/Browsingway/manifest.toml
Labels: size-small

#5892 ChillFrames v3.1.1.2
  stable/ChillFrames/manifest.toml
Labels: size-small

#5894 [Testing] ScoutHelper v1.8.4
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#5895 DragoonMayCry 1.2.7.1
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#5897 DelvUI release 2.4.0.1
  stable/DelvUI/manifest.toml
Labels: size-small

#5896 [Testing] Altoholic v0.0.0.44
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5889 Allagan Tools 1.12.0.1
  stable/InventoryTools/manifest.toml
Labels: size-large

#5899 Mappy v3.1.1.2
  stable/Mappy/manifest.toml
Labels: size-small

#5900 Quest Share 0.0.0.4
  testing/live/QuestShare/manifest.toml
Labels: size-small

#5898 Umbra 2.3.14
  stable/Umbra/manifest.toml
Labels: size-mid

#5903 [stable] WorkshopOptimizerPlugin 0.3.0.2
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-small

#5904 HUDUnlimited v1.1.1.4
  stable/HUDUnlimited/manifest.toml
Labels: size-small

#5905 Lights, Camera, Action! v1.0.3
  stable/CameraLoader/manifest.toml
Labels: size-small

#5906 DragoonMayCry 1.2.7.2
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#5902 Party Icons 1.2.3.0
  stable/PartyIcons/manifest.toml
Labels: size-large

#5908 Update TidyChat 2.0.14
  stable/TidyChat/manifest.toml
Labels: size-small

#5909 [Testing] Racingway v0.0.6.5
  testing/live/Racingway/manifest.toml
Labels: size-small

#5910 1.1.1 updated mute feature
  stable/QuietDen/manifest.toml
Labels: size-small

#5913 TextToTalk v1.31.1
  stable/TextToTalk/manifest.toml
Labels: size-small

#5914 XIVWindowResizer 1.0.0.5
  stable/XIVWindowResizer/manifest.toml
Labels: size-small

#5911 PvP Tracker v2.3.4.0
  stable/PvpStats/manifest.toml
Labels: size-mid

#5912 VFXEditor v1.9.2.1
  stable/VFXEditor/manifest.toml
Labels: size-large

#5915 Allagan Market 1.1.0.5
  stable/AllaganMarket/manifest.toml
Labels: size-small

#5916 MagitekStratagem v0.12.0.0 - Upgrade builtin-server to "stable"
  stable/MagitekStratagem/manifest.toml
  testing/live/MagitekStratagem/images/icon.png
  testing/live/MagitekStratagem/manifest.toml
Labels: size-large

#5919 Accountant 1.8.0.1
  stable/Accountant/manifest.toml
Labels: size-small

#5918 VFXEditor v1.9.2.3
  stable/VFXEditor/manifest.toml
Labels: size-small

#5917 SonarPlugin v0.7.1.2
  stable/SonarPlugin/manifest.toml
Labels: size-small

#5920 ChatProximity 1.3.3
  stable/ChatProximity/manifest.toml
Labels: size-small

#5921 TextToTalk v1.31.2
  stable/TextToTalk/manifest.toml
Labels: size-small

#5922 GatherBuddy 3.6.1.0
  stable/GatherBuddy/manifest.toml
Labels: size-small

#5923 PvP Tracker v2.3.4.1
  stable/PvpStats/manifest.toml
Labels: size-small

#5924 Quest Share 0.0.0.5
  testing/live/QuestShare/manifest.toml
Labels: size-small

#5928 Tf2CriticalHitsPlugin 3.7.0.0
  stable/Tf2CriticalHitsPlugin/manifest.toml
Labels: size-small

#5582 BetterShadows 1.5.0.0 (API12)
  stable/BetterShadows/manifest.toml
  testing/live/BetterShadows/images/icon.png
  testing/live/BetterShadows/manifest.toml
Labels: blocked, size-mid

#5929 GatherBuddy 3.6.1.1
  stable/GatherBuddy/manifest.toml
Labels: size-small

#5927 Congratulations 1.4.0.0
  stable/Congratulations/manifest.toml
Labels: size-small

#5925 Allagan Market 1.1.0.6
  stable/AllaganMarket/manifest.toml
Labels: size-small

#5926 Allagan Tools 1.12.0.2
  stable/InventoryTools/manifest.toml
Labels: size-small

#5930 SonarPlugin v0.7.1.3
  stable/SonarPlugin/manifest.toml
Labels: size-small

#5540 New Plugin: Conditional Tweaks
  stable/ConditionalTweaks/images/goat.png
  stable/ConditionalTweaks/images/icon.png
  stable/ConditionalTweaks/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5931 fix: move ConditionalTweaks to testing
  testing/live/ConditionalTweaks/images/goat.png
  testing/live/ConditionalTweaks/images/icon.png
  testing/live/ConditionalTweaks/manifest.toml
Labels: move channel, size-large

#5932 Where Am I Again v2.1.1.1
  stable/WhereAmIAgain/manifest.toml
Labels: size-small

#5933 PennyPincher 1.8.0.5
  stable/PennyPincher/manifest.toml
Labels: size-small

#5934 Promote NoTypeSay to stable
  stable/NoTypeSay/images/icon.png
  stable/NoTypeSay/images/image1.png
  stable/NoTypeSay/manifest.toml
Labels: move channel, size-large

#5936 Congratulations 1.4.0.2
  stable/Congratulations/manifest.toml
Labels: size-small

#5937 Tf2CriticalHitsPlugin 3.7.0.1
  stable/Tf2CriticalHitsPlugin/manifest.toml
Labels: size-small

#5939 TitleEdit v3.0.5.3
  stable/TitleEdit/manifest.toml
Labels: size-small

#5943 QuestMap v1.7.0.1
  stable/QuestMap/manifest.toml
Labels: size-small

#5942 Mappy v3.1.1.3
  stable/Mappy/manifest.toml
Labels: size-small

#5941 Promotion from Testing to Stable
  stable/Sightseeingway/images/icon.png
  stable/Sightseeingway/manifest.toml
Labels: move channel, size-large

#5944 [Testing] Quest Share 0.0.0.6
  testing/live/QuestShare/manifest.toml
Labels: size-small

#5945 Mappy v3.1.1.4
  stable/Mappy/manifest.toml
Labels: size-small

#5947 Update Audible Character Status to 1.0.1.7
  stable/AudibleCharacterStatus/manifest.toml
Labels: size-small

#5949 Allagan Market 1.1.0.7
  stable/AllaganMarket/manifest.toml
Labels: size-small

#5950 ffxiv2mqtt 1.0.8.0
  stable/Ffxiv2Mqtt/manifest.toml
Labels: size-small

#5951 SubmarineTracker 1.9.9.5
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5952 WaymarkPresetPlugin 1.5.4.2
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#5953 Sound Filter v1.5.0.0 to stable
  stable/SoundFilter/manifest.toml
  testing/live/SoundFilter/images/icon.png
  testing/live/SoundFilter/manifest.toml
Labels: size-small

#5954 Himbeertoni Raid Tool 1.9.0.4
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#5955 [Testing] Quest Share 0.0.0.7
  testing/live/QuestShare/manifest.toml
Labels: size-small

#5956 [Target Furniture] 7.2 Update
  stable/TargetFurniture/manifest.toml
Labels: size-small

#5957 Mappy v3.1.1.5
  stable/Mappy/manifest.toml
Labels: size-small

#5958 Update manifest.toml
  stable/FauxHollowsSolver/manifest.toml
Labels: size-small

#5959 Allagan Market 1.1.0.8
  stable/AllaganMarket/manifest.toml
Labels: size-small

#5960 MonsterLootHunter 1.3.24.7
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#5961 [Testing] SimpleCompare 2.0.1.0
  testing/live/SimpleCompare/manifest.toml
Labels: size-small

#5963 PP for 7.2
  stable/PixelPerfect/manifest.toml
Labels: size-small

#5964 Map Party Assist v2.4.1.3
  stable/MapPartyAssist/manifest.toml
Labels: size-small

#5907 WhoSaidWhatNow 0.5.5
  testing/live/WhoSaidWhatNow/images/icon.png
  testing/live/WhoSaidWhatNow/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5966 SortaKinda v3.1.1.1
  stable/SortaKinda/manifest.toml
Labels: size-small

#5965 Pet Nicknames v2.4.0.2
  stable/PetRenamer/manifest.toml
Labels: size-small

#5967 Himbeertoni Raid Tool 1.9.0.5
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#5970 PingPlugin v2.8.2
  stable/PingPlugin/manifest.toml
Labels: size-small

#5968 Questmap v1.7.2.0
  stable/QuestMap/manifest.toml
Labels: size-mid

#5973 InventorySearchBar release 1.7.0.0
  stable/InventorySearchBar/manifest.toml
Labels: size-small

#5974 Razer Reader v1.1.0
  stable/RazerReader/manifest.toml
Labels: size-small

#5975 [Stable] Quest Share
  stable/QuestShare/images/icon.png
  stable/QuestShare/manifest.toml
Labels: move channel, size-large

#5979 Honorific 1.5.2.2
  stable/Honorific/manifest.toml
Labels: size-small

#5980 ArchipelagoXIV v23.3
  testing/live/ArchipelagoXIV/manifest.toml
Labels: size-small

#5981 OfDungeonsDeep v1.0.4.3
  stable/OfDungeonsDeep/manifest.toml
Labels: size-small

#5982 Better Mount Roulette 1.7.1.26
  stable/BetterMountRoulette/manifest.toml
Labels: size-small

#5983 Pet Nicknames v2.4.0.3 (Shame.... again)
  stable/PetRenamer/manifest.toml
Labels: size-small

#5984 [Testing] BisBuddy v0.1.2.0
  testing/live/BisBuddy/manifest.toml
Labels: size-large

#5985 Razer Reader v1.1.1
  stable/RazerReader/manifest.toml
Labels: size-small

#5987 Sightseeingway: Event handling optimization
  stable/Sightseeingway/manifest.toml
Labels: size-small

#5986 DragoonMayCry v1.3.0.0
  stable/DragoonMayCry/manifest.toml
Labels: size-mid

#5988 Doorbell 1.0.3.9
  stable/Doorbell/manifest.toml
Labels: size-small

#5990 NotificationMaster 2.1.1.9
  stable/NotificationMaster/manifest.toml
Labels: size-small

#5993 Mappy v3.1.1.6
  stable/Mappy/manifest.toml
Labels: size-small

#5994 HUDUnlimited v1.1.1.5
  stable/HUDUnlimited/manifest.toml
Labels: size-small

#5995 Allagan Tools 1.12.0.3
  stable/InventoryTools/manifest.toml
Labels: size-mid

#5997 Wholist v1.9.2.0
  stable/Wholist/manifest.toml
Labels: size-small

#5999 Fader 2.7.2.0
  stable/FaderPlugin/manifest.toml
Labels: size-mid

#6000 Pet Nicknames v2.4.0.4
  stable/PetRenamer/manifest.toml
Labels: blocked, size-small

#6001 [Testing] BisBuddy v0.1.3.0
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#6003 Fader 2.7.2.1
  stable/FaderPlugin/manifest.toml
Labels: size-mid

#6004 [Testing] BisBuddy v0.1.3.1
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#6005 Honorific 1.6.0.0
  stable/Honorific/manifest.toml
Labels: size-small

#5972 [Testing] DotPosition v1.0.0.1
  testing/live/DotPosition/images/icon.png
  testing/live/DotPosition/images/screenshot.png
  testing/live/DotPosition/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5976 [Testing] [New Plugin] StatusContrast v0.0.1
  testing/live/StatusContrast/images/icon.png
  testing/live/StatusContrast/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6006 ZodiacBuddy v1.1.1.2
  stable/ZodiacBuddy/manifest.toml
Labels: size-small

#6008 [Testing] BisBuddy v0.1.4.0
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#6009 Allagan Tools 1.12.0.4
  stable/InventoryTools/manifest.toml
Labels: size-small

#6011 ContactsTracker v1.0.4
  stable/ContactsTracker/manifest.toml
Labels: size-small

#6013 [Testing] BisBuddy v0.1.4.1
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#6014 Wholist v1.9.2.1
  stable/Wholist/manifest.toml
Labels: size-small

#6015 DragoonMayCry 1.3.0.1
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#6017 Mappy v3.1.2.0
  stable/Mappy/manifest.toml
Labels: size-small

#6019 [Testing] StatusContrast 0.0.2
  testing/live/StatusContrast/manifest.toml
Labels: size-small

#6018 BisBuddy v0.1.4.1
  stable/BisBuddy/manifest.toml
Labels: size-large

#6020 Teleporter 2.0.2.7
  stable/TeleporterPlugin/manifest.toml
Labels: size-small

#6021 Update manifest for CurrencySpender
  stable/CurrencySpender/manifest.toml
Labels: size-small

#6024 [Testing] ScoutHelper v1.8.5
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#6025 [Testing] Racingway v0.0.6.6
  testing/live/Racingway/manifest.toml
Labels: size-small

#6026 Promote ScoutHelper to Stable
  stable/ScoutHelper/manifest.toml
Labels: size-mid

#6027 PvP Tracker v2.4.0.0
  stable/PvpStats/manifest.toml
Labels: size-mid

#6023 Aether Compass 1.6.6.0
  testing/live/AetherCompass/manifest.toml
Labels: size-large

#6022 DragoonMayCry 1.3.1.0
  stable/DragoonMayCry/manifest.toml
Labels: size-large

#5977 [Testing] [New Plugin] PartySortPlus v1.0.0.0
  testing/live/PartySortPlus/images/icon.png
  testing/live/PartySortPlus/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5992 [Testing] Render Adjust alpha
  testing/live/RenderAdjust/images/icon.png
  testing/live/RenderAdjust/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6031 PvP Tracker v2.4.0.0
  stable/PvpStats/manifest.toml
Labels: size-small

#6030 RP Utils 0.3.1
  testing/live/RpUtils/manifest.toml
Labels: size-small

#6029 [stable] NowPlaying 1.3.0.3
  stable/NowPlaying/manifest.toml
Labels: size-small

#6028 Neko Fans 1.3.5
  stable/Neko/manifest.toml
Labels: size-small

#6032 [WhoSaidWhatNow] v0.6.1
  testing/live/WhoSaidWhatNow/manifest.toml
Labels: size-small

#6033 TextToTalk v1.31.3
  stable/TextToTalk/manifest.toml
Labels: size-small

#6034 EasyEyes v1.3.1.0
  stable/EasyEyes/manifest.toml
Labels: size-small

#6036 Bartender v1.1.7.0
  stable/Bartender/manifest.toml
Labels: size-small

#6037 Hunty 1.3.4.0
  stable/Hunty/manifest.toml
Labels: size-small

#6035 MacroMate 1.0.22.0
  stable/MacroMate/manifest.toml
Labels: size-mid

#6040 [Testing] StatusContrast 0.0.3
  testing/live/StatusContrast/images/icon.png
  testing/live/StatusContrast/images/image1.png
  testing/live/StatusContrast/images/image2.png
  testing/live/StatusContrast/manifest.toml
Labels: size-small

#6041 Tracky 1.5.9.1
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6042 Simple Tweaks 1.10.9.2
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#6043 FlyTextFilter 4.3.0.2
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#6044 GatherBuddy 3.7.0.0
  stable/GatherBuddy/manifest.toml
Labels: size-small

#6045 [Testing] HUDManager 2.5.22.0
  testing/live/HUDManager/manifest.toml
Labels: size-small

#6048 [Testing] ScoutHelper v1.8.6
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#6050 GatherBuddy 3.7.1.0
  stable/GatherBuddy/manifest.toml
Labels: size-mid
