Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-05, with the labels that each got.

#5989 [Testing] [New Plugin] CashFlow 1.0.1.7
  testing/live/CashFlow/images/icon.png
  testing/live/CashFlow/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6081 ZDs 1.0.0.8
  stable/ZDs/manifest.toml
  testing/live/ZDs/manifest.toml
Labels: size-small

#6082 v11.1.3.0 - Fixed linux permissions issue
  stable/NextUIPlugin/manifest.toml
Labels: size-small

#6083 Allagan Market 1.1.0.10
  stable/AllaganMarket/manifest.toml
Labels: size-mid

#6080 Mappy v3.1.3.2
  testing/live/Mappy/manifest.toml
Labels: size-large

#6084 NoSol 3.1.7
  stable/NoSoliciting/manifest.toml
Labels: size-small

#6038 [Testing] [New Plugin] XivGearExport
  testing/live/XivGearExport/images/icon.png
  testing/live/XivGearExport/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6007 [Testing] [New Plugin] PvP Announcer
  testing/live/PvPAnnouncer/images/icon.png
  testing/live/PvPAnnouncer/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance

#6085 Mappy v3.1.4.0
  testing/live/Mappy/manifest.toml
Labels: size-small

#6086 NextUIPlugin v11.1.5.0 - Fixed crash in case of microplugin download error
  stable/NextUIPlugin/manifest.toml
Labels: size-small

#6087 [Testing] StatusContrast v0.1.0
  testing/live/StatusContrast/manifest.toml
Labels: size-small

#6089 [Testing] Moonbase Omega 1.1.0.0
  testing/live/MoonbaseOmega/manifest.toml
Labels: size-mid

#6091 MagitekStratagem v0.12.0.1 - Fix to crash on startup w/ no tracker
  stable/MagitekStratagem/manifest.toml
Labels: size-small

#6093 [Testing] Umbra 3.0.1
  testing/live/Umbra/manifest.toml
Labels: size-small

#6094 [Testing] Racingway v0.0.6.7
  testing/live/Racingway/manifest.toml
Labels: size-small

#6097 BetterPlaytime 1.4.2.1
  stable/BetterPlaytime/manifest.toml
Labels: size-small

#6098 SubmarineTracker 1.9.9.8
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#6096 XIVLogger 1.0.8.1
  stable/XIVLogger/manifest.toml
Labels: size-mid

#6095 Allagan Tools 1.12.0.5
  stable/InventoryTools/manifest.toml
Labels: size-large

#6099 Mappy v3.1.5.1
  testing/live/Mappy/manifest.toml
Labels: size-small

#6100 [Testing] Umbra 3.0.2
  testing/live/Umbra/manifest.toml
Labels: size-mid

#6101 GatherBuddy 3.7.2.1
  stable/GatherBuddy/manifest.toml
Labels: size-small

#6102 Mappy v3.1.5.4
  testing/live/Mappy/manifest.toml
Labels: size-mid

#6105 AbilityAnts 1.0.0.5
  stable/AbilityAnts/manifest.toml
Labels: size-small

#6104 MacroMate 1.0.24.2
  stable/MacroMate/manifest.toml
Labels: size-small

#6107 [Testing] Umbra 3.0.3
  testing/live/Umbra/manifest.toml
Labels: size-small

#6108 [Testing] Umbra 3.0.4
  testing/live/Umbra/manifest.toml
Labels: size-small

#6109 Mappy v3.1.5.6
  testing/live/Mappy/manifest.toml
Labels: size-small

#6110 PvP Tracker v2.5.1.0
  testing/live/PvpStats/manifest.toml
Labels: size-small

#6052 [Testing] [New Plugin] SettingsEnhanced
  testing/live/SettingsEnhanced/images/icon.png
  testing/live/SettingsEnhanced/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6111 Allagan Tools 1.12.0.6
  stable/InventoryTools/manifest.toml
Labels: size-large

#6112 Simple Tweaks 1.10.9.3
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#6115 DailyDuty v5.2.2.4
  stable/DailyDuty/manifest.toml
Labels: size-small

#6116 Allagan Tools 1.12.0.7
  stable/InventoryTools/manifest.toml
Labels: size-small

#6118 PvPAnnouncer v0.0.0.7
  testing/live/PvPAnnouncer/manifest.toml
Labels: size-small

#6119 DailyDuty v5.2.2.5
  stable/DailyDuty/manifest.toml
Labels: size-small

#6120 QuestShare v1.0.1.0
  stable/QuestShare/manifest.toml
Labels: size-small

#6121 CashFlow 1.0.2.3
  testing/live/CashFlow/manifest.toml
Labels: size-small

#6124 PvPAnnouncer v0.0.0.8
  testing/live/PvPAnnouncer/manifest.toml
Labels: size-small

#6123 DutyPusher [Moving Channel]
  stable/DutyPusher/images/icon.png
  stable/DutyPusher/manifest.toml
Labels: move channel, size-large

#6122 Allagan Tools 1.12.0.8
  stable/InventoryTools/manifest.toml
Labels: size-small

#6127 Wholist v1.9.4.0
  stable/Wholist/manifest.toml
Labels: size-small

#6128 Sightseeingway 1.1.0.0
  testing/live/Sightseeingway/manifest.toml
Labels: size-large

#6125 PvP Tracker v.2.5.1.0
  stable/PvpStats/manifest.toml
Labels: size-large

#6129 PvPAnnouncer v.0.1.2.0
  testing/live/PvPAnnouncer/manifest.toml
Labels: size-small

#6130 ChatTranslated v3.3.3.1
  stable/ChatTranslated/manifest.toml
Labels: size-large

#6131 Mappy v3.1.5.7
  testing/live/Mappy/manifest.toml
Labels: size-small

#6133 PvP Tracker v2.5.1.1
  stable/PvpStats/manifest.toml
Labels: size-small

#6134 SettingsEnhanced v0.1.3.0
  testing/live/SettingsEnhanced/manifest.toml
Labels: size-small

#6136 Collections v1.0.2.5
  stable/Collections/manifest.toml
Labels: size-small

#6137 [Testing] Collections v1.0.2.6
  testing/live/Collections/manifest.toml
Labels: size-large

#6135 Update The Great Controller HUD Switcher to 1.2
  stable/XIVControllerToggle/manifest.toml
Labels: size-large

#6138 Wholist v1.9.5.0
  stable/Wholist/manifest.toml
Labels: size-small

#6139 Add Compass 1.30.0
  stable/Compass/manifest.toml
Labels: size-small

#6140 SettingsEnhanced v0.1.3.1
  testing/live/SettingsEnhanced/manifest.toml
Labels: size-small

#6141 [Testing] BisBuddy v0.1.5.0
  testing/live/BisBuddy/manifest.toml
Labels: size-large

#6142 Quest Share 1.0.2.0
  stable/QuestShare/manifest.toml
Labels: size-small

#6143 Tracky 1.5.9.4
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6145 Move PvPAnnouncer to Stable
  stable/PvPAnnouncer/images/icon.png
  stable/PvPAnnouncer/manifest.toml
  testing/live/PvPAnnouncer/manifest.toml
Labels: move channel, size-small

#6146 Gposingway v1.0.1.0
  stable/Sightseeingway/manifest.toml
Labels: size-large

#6147 Update The Great Controller HUD Switcher to 1.2.1
  stable/XIVControllerToggle/manifest.toml
Labels: size-small

#6148 GatherBuddy 3.8.0.0
  stable/GatherBuddy/manifest.toml
Labels: size-large

#6149 SettingsEnhanced v0.1.4.0
  testing/live/SettingsEnhanced/manifest.toml
Labels: size-small

#6150 [Testing] BisBuddy v0.1.5.1
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#6151 GatherBuddy 3.8.1.0
  stable/GatherBuddy/manifest.toml
Labels: size-small

#6152 AutoMountBGM 2.2.5
  stable/AutoMountBgm/manifest.toml
Labels: size-small

#6155 Goodfriend v3.5.0.0
  stable/GoodFriend/manifest.toml
Labels: size-large

#6156 Pet Nicknames v2.4.0.5
  stable/PetRenamer/manifest.toml
Labels: size-small

#6159 Better Mount Roulette 1.7.2.27
  stable/BetterMountRoulette/manifest.toml
Labels: size-small

#6160 Wholist v1.10.0.0
  stable/Wholist/manifest.toml
Labels: size-small

#6161 SettingsEnhanced v0.1.5.0
  testing/live/SettingsEnhanced/manifest.toml
Labels: size-small

#6162 VFXEditor v1.9.2.5
  stable/VFXEditor/manifest.toml
Labels: size-small

#6163 GoodFriend v3.6.0.0
  stable/GoodFriend/manifest.toml
Labels: size-mid

#6157 SimpleCompare 2.1.0.0
  stable/SimpleCompare/images/icon.png
  stable/SimpleCompare/manifest.toml
  testing/live/SimpleCompare/manifest.toml
Labels: move channel, size-mid

#6164 Allagan Tools 1.12.0.9
  stable/InventoryTools/manifest.toml
Labels: size-small

#6165 SimpleCompare 2.1.0.1
  stable/SimpleCompare/manifest.toml
Labels: size-small

#6166 GoodFriend v3.6.1.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#6167 [Testing] DutyPusher v0.1.3.2 [ntfy.sh channel test]
  testing/live/DutyPusher/images/icon.png
  testing/live/DutyPusher/manifest.toml
Labels: move channel, size-large

#6169 [Testing] StatusContrast v1.0.0
  testing/live/StatusContrast/manifest.toml
Labels: size-mid

#6170 [Testing] Racingway v0.0.6.9
  testing/live/Racingway/manifest.toml
Labels: size-large

#6171 DailyDuty v5.3.0.0
  testing/live/DailyDuty/manifest.toml
Labels: size-large

#6172 Allagan Tools 1.12.0.10
  stable/InventoryTools/manifest.toml
Labels: size-large

#6173 [Testing] Umbra 3.0.5
  testing/live/Umbra/manifest.toml
Labels: size-large

#6002 [Testing] Added RetainerAlerts for testing.
  testing/live/RetainerAlerts/images/icon.png
  testing/live/RetainerAlerts/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6174 DailyDuty v5.3.0.2
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#6175 CashFlow 1.0.2.5
  testing/live/CashFlow/manifest.toml
Labels: size-small

#6177 DailyDuty v5.3.0.3
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#6178 DailyDuty v5.3.0.4
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#6179 Mappy v3.1.6.0
  stable/Mappy/manifest.toml
Labels: size-large

#6180 Allagan Tools 1.12.0.11
  stable/InventoryTools/manifest.toml
Labels: size-small

#6181 ChatTranslated 3.3.3.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#6183 Mappy v3.1.6.1
  stable/Mappy/manifest.toml
Labels: size-small

#6182 DailyDuty v5.3.0.5
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#6184 [Testing] Tourist 1.12.1.0
  testing/live/Tourist/images/icon.png
  testing/live/Tourist/manifest.toml
Labels: move channel, size-large

#6185 [Testing] Racingway v0.1.0.0
  testing/live/Racingway/manifest.toml
Labels: size-mid

#6188 HuntHelper 1.0.0.29
  stable/HuntHelper/manifest.toml
Labels: size-small

#6189 [Testing] Tourist 1.12.1.2
  testing/live/Tourist/manifest.toml
Labels: size-small

#6191 PvP Tracker v2.5.2.0
  stable/PvpStats/manifest.toml
Labels: size-large

#6193 Allagan Tools 1.12.0.12
  stable/InventoryTools/manifest.toml
Labels: size-mid

#6200 DutyTracker 1.0.3.4
  stable/DutyTracker/manifest.toml
Labels: size-small

#6199 [Testing] Racingway v0.1.0.1
  testing/live/Racingway/manifest.toml
Labels: size-mid

#6198 SortaKinda v2.1.1.2
  testing/live/SortaKinda/manifest.toml
Labels: size-mid

#6194 [Testing->Stable] Tourist 1.12.1.2
  stable/Tourist/manifest.toml
Labels: size-large

#6158 Fast Waymarks Plugin Submission
  testing/live/FastWaymarksPlugin/images/icon.png
  testing/live/FastWaymarksPlugin/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6202 [Testing] Altoholic v0.0.0.48
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#6201 Simple Tweaks 1.10.9.4
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#6203 FlyTextFilter 4.3.0.4
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#6207 Tracky 1.6.0.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6205 [Testing] Altoholic v0.0.0.49
  testing/live/Altoholic/manifest.toml
Labels: size-small

#6206 Settings Enhanced 0.1.6.0
  testing/live/SettingsEnhanced/manifest.toml
Labels: size-small

#6208 [Testing] ScoutHelper v1.8.7
  testing/live/ScoutHelper/manifest.toml
Labels: size-small

#6209 Tracky 1.6.0.1
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6212 Allagan Tools 1.12.0.13
  stable/InventoryTools/manifest.toml
Labels: size-small

#6213 PvP Tracker v2.5.3.0
  stable/PvpStats/manifest.toml
Labels: size-small

#6216 Sightseeingway 1.1.0.0
  stable/Sightseeingway/manifest.toml
Labels: size-small

#6215 Tracky 1.6.0.3
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6217 ChatTwo 1.30.3
  stable/ChatTwo/manifest.toml
Labels: size-small

#6218 [XivGearExport] Move from testing to stable
  stable/XivGearExport/images/icon.png
  stable/XivGearExport/manifest.toml
Labels: move channel, size-large

#6222 Tracky 1.6.0.5
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6221 Allagan Tools 1.12.0.14
  stable/InventoryTools/manifest.toml
Labels: size-small

#6227 SortaKinda v2.1.1.3
  stable/SortaKinda/manifest.toml
Labels: size-small

#6226 Mappy v3.1.6.2
  stable/Mappy/manifest.toml
Labels: size-small

#6220 GoodFriend v3.7.0.0
  stable/GoodFriend/manifest.toml
Labels: size-mid

#6224 EurekaLinker 1.5.4.0
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-mid

#6229 CurrencyAlert v2.2.1.3
  testing/live/CurrencyAlert/manifest.toml
Labels: size-mid

#6225 DailyDuty 5.3.0.6
  stable/DailyDuty/manifest.toml
Labels: size-mid

#6223 [Testing/live] Quest Journal v1.1.2.0
  testing/live/QuestJournal/manifest.toml
Labels: size-large

#6230 Simple Tweaks 1.10.10.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#6228 SonarPlugin v0.7.2.2
  stable/SonarPlugin/manifest.toml
Labels: size-large

#6232 CurrencyAlert v2.2.1.5
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#6233 GoodFriend v1.7.1.0
  stable/GoodFriend/manifest.toml
Labels: size-large

#6234 Mappy v3.1.6.4
  stable/Mappy/manifest.toml
Labels: size-small

#6236 Fatal Frame 1.0.0.0
  stable/XivFatalFrame/images/icon.png
  stable/XivFatalFrame/manifest.toml
Labels: move channel, size-large

#6237 Acquisition Date 1.0.0.0
  stable/AcquisitionDate/images/icon.png
  stable/AcquisitionDate/manifest.toml
Labels: move channel, size-large

#6238 EurekaLinker 1.5.4.3
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small
