Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-06, with the labels that each got.

#6239 [Testing] Altoholic v0.0.0.50
  testing/live/Altoholic/manifest.toml
Labels: size-small

#6242 EurekaLinker 1.5.4.4
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6243 Tracky 1.6.0.6
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6241 [Testing/Live] QuestJournal v1.1.3.0
  testing/live/QuestJournal/manifest.toml
Labels: size-large

#6245 Tracky 1.6.0.7
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6247 EurekaLinker 1.5.4.5
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6244 DailyDuty v5.3.1.0
  stable/DailyDuty/manifest.toml
Labels: size-mid

#6249 EurekaLinker 1.5.4.6
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6253 EurekaLinker 1.5.4.7
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6251 [Testing] DailyDuty v5.3.1.2
  testing/live/DailyDuty/manifest.toml
Labels: size-mid

#6252 CurrencyAlert v2.2.1.6
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#6256 ZDs 1.1.0.1
  stable/ZDs/manifest.toml
  testing/live/ZDs/manifest.toml
Labels: size-small

#6257 GoodFriend v3.7.2.0
  stable/GoodFriend/manifest.toml
Labels: size-small

#6261 Wholist v1.11.0.0
  stable/Wholist/manifest.toml
Labels: size-small

#6263 [DutyPusher] v0.1.4.0 (Bug fixed; Add new commands; Migration to Dalamud.NEW.Sdk)
  stable/DutyPusher/manifest.toml
  testing/live/DutyPusher/manifest.toml
Labels: size-mid

#6267 FastJobSwitcher v3.0.0.0
  stable/FastJobSwitcher/manifest.toml
Labels: size-small

#6269 Collections v1.0.2.7
  stable/Collections/manifest.toml
  testing/live/Collections/manifest.toml
Labels: size-large

#6270 GoodFriend v3.7.2.1
  stable/GoodFriend/manifest.toml
Labels: size-small

#6271 QuestMap v1.7.2.2
  stable/QuestMap/manifest.toml
Labels: size-small

#6275 FastJobSwitcher v3.0.1.0
  stable/FastJobSwitcher/manifest.toml
Labels: size-small

#6274 [Testing] Racingway v0.1.1.0
  testing/live/Racingway/manifest.toml
Labels: size-mid

#6276 CashFlow 1.0.2.5
  stable/CashFlow/images/icon.png
  stable/CashFlow/manifest.toml
Labels: move channel, size-large

#6282 Allagan Tools 1.12.0.18
  stable/InventoryTools/manifest.toml
Labels: size-small

#6186 [Testing] [New Plugin] Wikilinx Rightclicks
  testing/live/Wikilinx/images/icon.png
  testing/live/Wikilinx/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance

#6195 PFSearch 1.0.0.0
  testing/live/PFSearch/images/icon.png
  testing/live/PFSearch/manfiest.toml
Labels: new plugin, completed-code-review, size-large, pending-testing, completed-rules-compliance

#6287 EurekaLinker 1.5.4.9
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-mid

#6290 WhichMount 1.2.0
  stable/WhichMount/manifest.toml
Labels: size-small

#6291 WhichMount 1.2.0.2
  stable/WhichMount/manifest.toml
Labels: size-small

#6294 [Testing]DutyPusher v0.1.4.1 Add Icon & Update Documents
  testing/live/DutyPusher/manifest.toml
Labels: size-small

#6295 [Testing] NotificationMaster 2.1.1.10
  testing/live/NotificationMaster/images/icon.png
  testing/live/NotificationMaster/manifest.toml
Labels: move channel, size-large

#6286 DailyDuty v5.3.1.4
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#6288 EzMiniCactpot v3.0.0.0
  testing/live/MiniCactpotSolver/images/icon.png
  testing/live/MiniCactpotSolver/manifest.toml
Labels: move channel, size-mid

#6292 HUDUnlimited v1.1.2.0
  testing/live/HUDUnlimited/manifest.toml
Labels: size-mid

#6293 EurekaLinker 1.5.5.0
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-large

#6296 HUDUnlimited v1.1.2.1
  testing/live/HUDUnlimited/manifest.toml
Labels: size-small

#6301 Allagan Tools 1.12.0.20
  stable/InventoryTools/manifest.toml
Labels: size-small

#6302 Fader 2.7.4.0
  stable/FaderPlugin/manifest.toml
Labels: size-small

#6303 MOAction 4.6.0
  stable/MOAction/manifest.toml
Labels: size-small

#6298 Allagan Item Search 1.0.0.5
  stable/AllaganItemSearch/manifest.toml
Labels: size-large

#6305 Eureka Linker 1.5.5.4
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6307 MOAction 4.7.0
  stable/MOAction/manifest.toml
Labels: size-small

#6308 Tracky 1.6.0.8
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6306 MacroMate 1.0.25.1
  stable/MacroMate/manifest.toml
Labels: size-small

#6300 [Testing] I Hate Caps Lock v0.0.0.2
  testing/live/IHateCapsLock/images/icon.png
  testing/live/IHateCapsLock/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6310 CashFlow 1.0.2.6
  stable/CashFlow/manifest.toml
Labels: size-small

#6278 [New Plugin] [Testing] Occult Crescent Helper v0.1
  testing/live/OccultCrescentHelper/images/icon.png
  testing/live/OccultCrescentHelper/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6312 SonarPlugin v0.7.2.3
  stable/SonarPlugin/manifest.toml
Labels: size-small

#6313 [Testing] Umbra 3.0.8
  testing/live/Umbra/manifest.toml
Labels: size-small

#6319 WhichMount 1.3.0.0
  stable/WhichMount/manifest.toml
Labels: size-mid

#6321 [Testing] Altoholic v0.0.0.53
  testing/live/Altoholic/manifest.toml
Labels: size-small

#6323 EurekaLinker 1.5.6.1
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6326 ChatTwo 1.30.5
  stable/ChatTwo/manifest.toml
Labels: size-small

#6327 EurekaLinker 1.5.6.2
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6328 [Testing] Altoholic v0.0.0.54
  testing/live/Altoholic/manifest.toml
Labels: size-small

#6322 [Stable] & [Testing/Live] QuestJournal
  stable/QuestJournal/images/icon.png
  stable/QuestJournal/manifest.toml
  testing/live/QuestJournal/manifest.toml
Labels: move channel, size-large

#6330 [Testing] TextToTalk v1.32.0
  testing/live/TextToTalk/manifest.toml
Labels: size-large

#6333 AbilityAnts 1.0.0.6
  stable/AbilityAnts/manifest.toml
Labels: size-small

#6335 Chatter 1.3.1
  stable/Chatter/manifest.toml
Labels: size-small

#6342 [Testing] Racingway v0.1.1.1
  testing/live/Racingway/manifest.toml
Labels: size-small

#6343 [Testing] CustomResolution v0.3.2.0
  testing/live/CustomResolution2782/manifest.toml
Labels: size-small
