Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-08, with the labels that each got.

#6454 DailyDuty v5.3.2.3
  stable/DailyDuty/manifest.toml
Labels: size-small

#6455 aetherdraw v2.3.0.2
  stable/AetherDraw/manifest.toml
Labels: size-small

#6456 QuestMap v1.7.2.3
  stable/QuestMap/manifest.toml
Labels: size-small

#6457 SubmarineTracker 1.9.9.11
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#6458 NoTankYou v7.2.2.7
  stable/NoTankYou/manifest.toml
Labels: size-small

#6168 Submit BetterFriendList to test
  testing/live/BetterFriendList/images/icon.png
  testing/live/BetterFriendList/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance

#6550 StanleyParableXiv 4.0.0.0
  stable/StanleyParableXiv/manifest.toml
  testing/live/StanleyParableXiv/manifest.toml
Labels: size-small

#6546 ShopItemRevealer 1.1.3
  stable/ShopItemRevealer/manifest.toml
Labels: size-small

#6545 QuestShare 1.0.3.0
  stable/QuestShare/manifest.toml
Labels: size-small

#6548 WhereAmIAgain 2.1.1.2
  stable/WhereAmIAgain/manifest.toml
Labels: size-small

#6543 SimpleCompare 2.1.1.0
  stable/SimpleCompare/manifest.toml
Labels: size-small

#6539 dotcalc API13 update
  testing/live/DotCalculator/manifest.toml
Labels: size-small

#6536 bump launchpadhotbars to api 13 and move to stable
  stable/LaunchpadHotbars/images/icon.png
  stable/LaunchpadHotbars/manifest.toml
Labels: move channel, size-small

#6535 bump nicedamage for api13
  stable/NICEDamage/manifest.toml
Labels: size-small

#6534 ReSanctuary 1.4.0.4
  stable/ReSanctuary/manifest.toml
Labels: size-small

#6533 cl_showpos 1.1.0.5
  stable/cl_showpos/manifest.toml
Labels: size-small

#6531 Update my plogon
  stable/NamePlateDebuffs/manifest.toml
  stable/borderless-fix/manifest.toml
Labels: size-small

#6530 PriceInsight 2.11.3.0
  stable/PriceInsight/manifest.toml
Labels: size-small

#6527 ChatContext v0.0.3.0
  stable/ChatContext/manifest.toml
Labels: size-small

#6522 BetterFriendList Update API 13
  testing/live/BetterFriendList/manifest.toml
Labels: size-small

#6520 Party Icons 1.2.3.1
  stable/PartyIcons/manifest.toml
Labels: size-small

#6519 [Testing] HUDManager 2.5.22.1
  testing/live/HUDManager/manifest.toml
Labels: size-small

#6518 Market Board v1.11.0
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#6517 XIVDeck 0.4.0
  stable/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-small

#6512 Questmap v1.8.0.0
  stable/QuestMap/manifest.toml
Labels: size-small

#6510 Rezo Scale Plugin v1.3.0.0
  stable/RezoPlugin/manifest.toml
Labels: size-small

#6507 DeathRoll 1.5.5.0
  stable/DeathRoll/manifest.toml
Labels: size-small

#6506 BetterPartyFinder 1.5.7
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#6505 MoAction 4.8.0
  stable/MOAction/manifest.toml
Labels: version conflict, size-small

#6503 Fader 2.4.5.0
  stable/FaderPlugin/manifest.toml
Labels: size-small

#6502 WaymarkPresetPlugin 1.5.5.0
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#6501 Inspecto 0.0.0.5
  testing/live/Inspecto/manifest.toml
Labels: size-small

#6498 OpenerCreator 0.5.0
  stable/OpenerCreator/manifest.toml
Labels: size-small

#6494 DiademCalculator 1.1.3.0
  stable/DiademCalculator/manifest.toml
Labels: size-small

#6489 Directional 1.0.0.0
  stable/Directional/manifest.toml
Labels: size-small

#6487 EurekaLinker 1.5.9.0
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6483 FlyTextFilter 4.4.0.0
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#6480 ZDs 1.1.0.4
  stable/ZDs/manifest.toml
  testing/live/ZDs/manifest.toml
Labels: size-small

#6479 AbilityAnts 1.0.1.0
  stable/AbilityAnts/manifest.toml
Labels: size-small

#6477 RezPls 1.5.1.0
  stable/RezPls/manifest.toml
Labels: size-small

#6551 HighFpsPhysics - Update manifest.toml for patch 7.3
  stable/HighFpsPhysicsPlugin/manifest.toml
Labels: size-small

#6476 Chat Proximity 1.4.1
  stable/ChatProximity/manifest.toml
Labels: size-small

#6475 ChatAlerts 2.2.2.0
  stable/ChatAlerts/manifest.toml
Labels: size-small

#6465 MonsterDex 2.13.0
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#6584 SortaKinda v2.1.1.4
  stable/SortaKinda/manifest.toml
Labels: size-small

#6583 NoTankYou v7.2.2.8
  stable/NoTankYou/manifest.toml
Labels: size-small

#6580 ChillFrames v3.1.1.5
  stable/ChillFrames/manifest.toml
Labels: size-small

#6578 Eventy v2
  stable/Eventy/manifest.toml
Labels: size-small

#6542 WTSync 0.17.0.0
  stable/WTSync/manifest.toml
Labels: size-small

#6577 BigNaelQuotes 0.0.7 (api13)
  stable/BigNaelQuotes/manifest.toml
Labels: size-small

#6576 Resizable HUD 1.5.0.0
  stable/ResizableHUD/manifest.toml
Labels: size-small

#6515 PlayerTrack 3.5.2.0
  stable/PlayerTrack/manifest.toml
Labels: size-small

#6553 Handy Hotbar Helper v0.1.2
  stable/HandyHotbarHelper/images/icon.png
  stable/HandyHotbarHelper/manifest.toml
  testing/live/HandyHotbarHelper/manifest.toml
Labels: move channel, size-small

#6562 SillyChat v1.7.2.0
  stable/SillyChat/manifest.toml
Labels: size-small

#6565 Bartender v1.1.7.1
  stable/Bartender/manifest.toml
Labels: size-small

#6575 TargetLines 1.9.0.0
  stable/TargetLines/manifest.toml
Labels: size-small

#6558 EldenRingPlugin v0.0.4.0
  stable/EldenRing/manifest.toml
Labels: size-small

#6563 XIVUncombo v1.0.2.0
  stable/XIVUncombo/manifest.toml
Labels: size-small

#6560 ItemSearch v1.10.3.0
  stable/ItemSearchPlugin/manifest.toml
Labels: size-small

#6554 Minimap Marker Magnitude v1.0.1
  stable/MinimapMarkerMagnitude/manifest.toml
Labels: size-small

#6571 MoAction 4.8.0 v2
  stable/MOAction/manifest.toml
Labels: size-small

#6556 [Testing/Live] FastWaymarksPlugin v1.3.2
  testing/live/FastWaymarksPlugin/manifest.toml
Labels: size-small

#6589 PingPlugin v2.9.0
  stable/PingPlugin/manifest.toml
Labels: size-small

#6588 SoundSetter v1.12.0
  stable/SoundSetter/manifest.toml
Labels: size-small

#6564 The Heart of The Party v1.0.10
  stable/TheHeartOfTheParty/manifest.toml
Labels: size-small

#6574 DalamudMinesweeper 1.4.0.0 (api13)
  stable/DalamudMinesweeper/manifest.toml
Labels: size-small

#6557 Namingway v1.1.19.0
  stable/Namingway/manifest.toml
Labels: size-small

#6573 BetterShadows 1.6.0.0
  stable/BetterShadows/manifest.toml
Labels: size-small

#6559 XIVCombo v2.0.2.0
  stable/XIVCombo/manifest.toml
Labels: size-small

#6529 perchbird API13 plugins
  stable/DamageInfoPlugin/manifest.toml
  stable/Housemate/manifest.toml
  stable/PrefPro/manifest.toml
  stable/ResLogger2.Plugin/manifest.toml
  stable/orchestrion/manifest.toml
Labels: size-mid

#6467 Adventurer in Need 1.5.0.4
  stable/AdventurerInNeed/manifest.toml
Labels: size-small

#6466 Simple Map Tracker 1.0.3
  stable/SimpleMapTracker/manifest.toml
Labels: size-small

#6471 Honorific 1.6.0.1
  stable/Honorific/manifest.toml
Labels: size-small

#6568 DotPosition 1.0.0.2
  testing/live/DotPosition/manifest.toml
Labels: size-small

#6504 Pixel Perfect 7.3
  stable/PixelPerfect/manifest.toml
Labels: size-small

#6473 ExpandedSearchInfo 1.4.3
  stable/ExpandedSearchInfo/manifest.toml
Labels: size-small

#6463 [Testing] [API13] VanillaHotbarExtender 1.2.3
  testing/live/VanillaHotbarExtender/manifest.toml
Labels: size-small

#6482 Update plugins to API13
  stable/AutoBGM/manifest.toml
  stable/ClarityInChaos/manifest.toml
  stable/FastJobSwitcher/manifest.toml
  stable/MagitekStratagem/manifest.toml
  stable/Tilted/manifest.toml
Labels: size-small

#6540 [Testing/Live] QuestJournal 1.2.0.1
  testing/live/QuestJournal/manifest.toml
Labels: size-large

#6470 FPS Plugin 1.7.0.3
  stable/FPSPlugin/manifest.toml
Labels: size-small

#6521 Echoglossian v3.22.x
  stable/Echoglossian/manifest.toml
Labels: size-large

#6513 I Hate Caps Lock v0.0.1.0
  stable/IHateCapsLock/images/icon.png
  stable/IHateCapsLock/manifest.toml
Labels: move channel, size-large

#6585 SonarPlugin v0.7.3.0
  stable/SonarPlugin/manifest.toml
Labels: size-large

#6591 [Testing] Racingway v0.1.1.2
  testing/live/Racingway/manifest.toml
Labels: size-small

#6592 BigPlayerDebuffs 1.1.0.13
  stable/BigPlayerDebuffs/manifest.toml
Labels: size-small

#6596 Weatherman 2.4.1.4
  stable/Weatherman/manifest.toml
Labels: size-small

#6597 WDIGViewer v1.0.3.1
  stable/WDIGViewer/manifest.toml
Labels: size-small

#6602 Teleporter 2.0.2.8
  stable/TeleporterPlugin/manifest.toml
Labels: size-small

#6601 MonsterLootHunter 1.4.24.7
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#6484 Update EngageTimer
  stable/EngageTimer/manifest.toml
Labels: size-small

#6604 [Testing] Simple Tweaks 1.10.11.0
  testing/live/SimpleTweaksPlugin/manifest.toml
Labels: size-large

#6603 Absolute Roleplay [Stable] [Testing-Live]
  stable/AbsoluteRoleplay/manifest.toml
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-large

#6611 Tourist 1.13.0.0
  stable/Tourist/manifest.toml
  testing/live/Tourist/manifest.toml
Labels: size-small

#6614 ZodiacBuddy 1.13.0.0
  stable/ZodiacBuddy/manifest.toml
Labels: size-small

#6613 Coordinate Importer 1.2.0.4
  stable/CoordImporter/manifest.toml
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#6593 Item Use 1.0.1.0
  stable/ItemUse/manifest.toml
Labels: size-small

#6594 Say What? 1.0.2.7
  stable/WhatDidYouSay/manifest.toml
Labels: size-small

#6595 Distance 1.1.3.3
  stable/Distance/manifest.toml
Labels: size-small

#6617 BetterFriendList 0.1.2.3
  testing/live/BetterFriendList/manifest.toml
Labels: size-small

#6620 WhereAmIAgain 2.1.1.3
  stable/WhereAmIAgain/manifest.toml
Labels: size-small

#6623 [XivGearExport] 1.4.1.1
  stable/XivGearExport/manifest.toml
Labels: size-small

#6622 [Testing] rtyping 0.2.0.0
  testing/live/rtyping/images/icon.png
  testing/live/rtyping/manifest.toml
Labels: size-mid

#6619 Umbra 3.1.0
  stable/Umbra/manifest.toml
Labels: size-mid

#6621 [Testing] BisBuddy v0.1.5.2
  testing/live/BisBuddy/manifest.toml
Labels: size-large

#6624 Sightseeingway: API 13 Update
  stable/Sightseeingway/manifest.toml
Labels: size-small

#6626 [Testing] BisBuddy v0.1.5.3
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#6631 Globetrotter 1.2.15
  stable/Globetrotter/manifest.toml
Labels: size-small

#6628 Absolute Roleplay [Testing-Live] [Stable]
  stable/AbsoluteRoleplay/manifest.toml
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-small

#6627 [Testing] DynamicUIScaling v0.0.0.4
  testing/live/DynamicUIScaling/manifest.toml
Labels: size-small

#6598 AetherFM – Migrate to source-based plugin (API 13 compliance)
  testing/live/AetherFM/manifest.toml
Labels: size-mid

#6632 [Testing] BisBuddy v0.1.5.4
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#6634 Dalamud.LoadingImage 1.0.0.16 and Dalamud.FullscreenCutscenes 1.0.0.6
  stable/Dalamud.FullscreenCutscenes/Dalamud.FullscreenCutscenes.toml
  stable/Dalamud.LoadingImage/manifest.toml
Labels: size-small

#6639 [Teamcraft List Maker] Update for 7.3
  stable/TeamcraftListMaker/manifest.toml
Labels: size-small

#6640 [TwitchXIV] Update for 7.3
  stable/TwitchXIV/manifest.toml
Labels: size-small

#6642 WondrousTailsSolver 3.2.2.5
  stable/WondrousTailsSolver/manifest.toml
Labels: size-small

#6648 Fantasy Player 2.4.0.0
  stable/FantasyPlayer/manifest.toml
Labels: size-mid

#6652 [Testing] BisBuddy v0.1.5.5
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#6653 Map Party Assist v2.5.0.0
  stable/MapPartyAssist/manifest.toml
Labels: size-small

#6650 Tippy 1.13.0.0
  stable/Tippy/manifest.toml
Labels: size-large

#6656 NoTypeSay 1.0.1.0
  stable/NoTypeSay/manifest.toml
Labels: size-small

#6657 Update FFXIV RP Event Calendar to 1.0.1.7 for 7.3
  stable/FFXIVRPCalendarPlugin/manifest.toml
Labels: size-small

#6659 [DragoonMayCry] 7.3 update
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#6658 XivInstantMessenger, CashFlow and QuestAway - 7.3
  stable/CashFlow/manifest.toml
  stable/Messenger/manifest.toml
  stable/QuestAWAY/manifest.toml
Labels: size-large

#6660 [Testing] Altoholic v0.0.0.59
  testing/live/Altoholic/manifest.toml
Labels: size-small

#6661 [stable] WorkshopOptimizerPlugin 0.3.1.1
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-small

#6662 Avant-Garde v1.0.4
  stable/AvantGarde/manifest.toml
Labels: size-small

#6664 EmoteLog v1.1.5.0
  stable/EmoteLog/manifest.toml
Labels: size-small

#6665 Wholist + GoodFriend API13
  stable/GoodFriend/manifest.toml
  stable/Wholist/manifest.toml
Labels: size-mid

#6668 ChangeDeviceFix v2.0.8
  stable/DeviceChangeFix/manifest.toml
Labels: size-small

#6674 TPie release 1.12.0.0
  stable/TPie/manifest.toml
Labels: size-small

#6676 ActionTimeline release 1.7.0.0
  stable/ActionTimeline/manifest.toml
Labels: size-small

#6680 CharacterPanelRefined 1.8.4.1
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small

#6673 DelvCD release 1.4.0.0
  stable/DelvCD/manifest.toml
Labels: size-small

#6682 Browsingway 1.6.6.0
  stable/Browsingway/manifest.toml
Labels: size-small

#6669 Himbeertoni Raid Tool 1.9.1.1
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-large

#6641 PvP Tracker v2.6.0.0
  stable/PvpStats/manifest.toml
Labels: size-large

#6687 Umbra 3.1.1
  stable/Umbra/manifest.toml
Labels: size-small

#6688 AetherDraw v2.3.0.4
  stable/AetherDraw/manifest.toml
Labels: size-small

#6689 BetterFriendList to 0.1.3.0
  testing/live/BetterFriendList/manifest.toml
Labels: size-small

#6691 SortaKinda v2.1.1.5
  stable/SortaKinda/manifest.toml
Labels: size-small

#6690 Echoglossian v3.23.x
  stable/Echoglossian/manifest.toml
Labels: size-mid

#6692 HuntHelper Fungah IslandWorkshopSearch API13
  stable/Fungah/manifest.toml
  stable/HuntHelper/manifest.toml
  stable/IslandWorkshopSearch/manifest.toml
Labels: size-small

#6686 Aetherfm 1.2.0
  testing/live/AetherFM/manifest.toml
Labels: size-mid

#6694 ChatTwo 1.31.1
  stable/ChatTwo/manifest.toml
Labels: size-small

#6695 Clean Hunt Chat and EzFauxHollows update
  testing/live/CleanHuntChat/manifest.toml
  testing/live/FauxHollowsSolver/images/icon.png
  testing/live/FauxHollowsSolver/manifest.toml
Labels: move channel, size-mid

#6696 SoundSetter v1.12.1
  stable/SoundSetter/manifest.toml
Labels: size-small

#6697 Congratulations 1.4.1.0 and Tf2CriticalHitsPlugin 3.7.1.0
  stable/Congratulations/manifest.toml
  stable/Tf2CriticalHitsPlugin/manifest.toml
Labels: size-small

#6698 EnemyListDebuffs API13 Update
  stable/EnemyListDebuffs/manifest.toml
Labels: size-small

#6699 Sound Filter v1.5.1
  stable/SoundFilter/manifest.toml
Labels: size-small

#6705 AcquistionDate 1.0.1.0
  stable/AcquisitionDate/manifest.toml
Labels: size-small
