Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-09, with the labels that each got.

#6917 VanillaPlus v1.0.0.8
  stable/VanillaPlus/manifest.toml
Labels: size-small

#6918 VanillaPlus v1.0.0.9
  stable/VanillaPlus/manifest.toml
Labels: size-small

#6434 New plugin submission: BackseatDriver.
  testing/live/BackseatDriver/images/icon.png
  testing/live/BackseatDriver/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance

#6923 HUDUnlimited v1.1.2.4
  stable/HUDUnlimited/manifest.toml
Labels: size-small

#6922 VanillaPlus v1.0.0.11
  stable/VanillaPlus/manifest.toml
Labels: size-mid

#6927 GatherBuddy 3.8.3.0
  stable/GatherBuddy/manifest.toml
Labels: size-mid

#6931 [Testing] Gauge-O-Matic 0.8.2.1
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#6932 CrossUp 1.7.1.1
  stable/CrossUp/manifest.toml
Labels: size-small

#6934 SubmarineTracker 2.0.0.5
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#6906 New plugin submission: LazyGatherer
  testing/live/LazyGatherer/images/icon.png
  testing/live/LazyGatherer/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6448 New plugin BeastieBuddy v1.1.1.0
  testing/live/BeastieBuddy/images/icon.png
  testing/live/BeastieBuddy/images/image1.png
  testing/live/BeastieBuddy/images/image2.png
  testing/live/BeastieBuddy/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6935 EurekaLinker 1.5.9.4
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-large

#6939 SonarPlugin v0.7.3.4
  stable/SonarPlugin/manifest.toml
Labels: size-small

#6942 Allagan Market 1.2.0.3
  stable/AllaganMarket/manifest.toml
Labels: size-small

#6943 Tracky 1.6.2.2
  stable/TrackyTrack/manifest.toml
Labels: size-small

#6944 LazyGatherer 1.0.2
  testing/live/LazyGatherer/manifest.toml
Labels: size-small

#6946 VanillaPlus v1.0.0.13
  stable/VanillaPlus/manifest.toml
Labels: size-small

#6947 aetherbreakout v1.2.1.0
  testing/live/AetherBreakout/manifest.toml
Labels: size-small

#6948 Allagan Tools 1.13.1.4
  stable/InventoryTools/manifest.toml
Labels: size-small

#6950 WhichMount v1.3.7
  stable/WhichMount/manifest.toml
Labels: size-small

#6953 RezPls 1.5.2.0
  stable/RezPls/manifest.toml
Labels: size-small

#6952 [Testing/Live] QuestJournal v1.2.0.2
  testing/live/QuestJournal/manifest.toml
Labels: size-small

#6954 DamageInfoPlugin 2.4.1.4 -> 2.4.1.5
  stable/DamageInfoPlugin/manifest.toml
Labels: size-small

#6955 Update to version 7.3
  stable/Chatter/manifest.toml
Labels: size-small

#6959 DynamicUiScaling: 1.13.1.0
  stable/DynamicUIScaling/manifest.toml
  testing/live/DynamicUIScaling/manifest.toml
Labels: size-small

#6964 Update NoSol
  stable/NoSoliciting/manifest.toml
Labels: size-small

#6966 Promote ScoutHelper v1.10.1 to Stable
  stable/ScoutHelper/manifest.toml
Labels: size-small

#6967 VanillaPlus v1.0.1.0
  stable/VanillaPlus/manifest.toml
Labels: size-small

#6968 BeastieBuddy v1.2.0.0
  testing/live/BeastieBuddy/manifest.toml
Labels: size-large

#6972 GoodFriend v3.7.2.3
  stable/GoodFriend/manifest.toml
Labels: size-small

#6975 [Testing] CustomResolution v1.0.1.0
  testing/live/CustomResolution2782/images/icon.png
  testing/live/CustomResolution2782/manifest.toml
Labels: move channel, size-large

#6989 aetherdraw v2.3.0.5
  stable/AetherDraw/manifest.toml
Labels: size-small

#6993 SonarPlugin v0.7.3.6
  stable/SonarPlugin/manifest.toml
Labels: size-small

#6996 LazyGatherer v1.1.0
  testing/live/LazyGatherer/manifest.toml
Labels: size-small

#6992 Umbra 3.1.7
  stable/Umbra/manifest.toml
Labels: size-small

#6994 SonarPlugin v0.7.3.8
  stable/SonarPlugin/manifest.toml
Labels: size-small

#6999 Mappy v3.1.6.10
  stable/Mappy/manifest.toml
Labels: size-small

#7002 Update KingdomHeartsPlugins to 1.0.7.4
  stable/KingdomHeartsPlugin/manifest.toml
Labels: size-small

#7010 VanillaPlus v1.0.1.7
  stable/VanillaPlus/manifest.toml
Labels: size-small

#7011 TooltipNotes 1.7.1.0
  stable/TooltipNotes/manifest.toml
Labels: size-small

#7012 VanillaPlus v1.0.1.8
  stable/VanillaPlus/manifest.toml
Labels: size-small

#6459 Test TataruLink 0.0.0.2
  testing/live/TataruLink/images/icon.png
  testing/live/TataruLink/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6787 New plugin: Shanbells v1.2.0
  testing/live/Shanbells/images/icon.png
  testing/live/Shanbells/manifest.toml
Labels: new plugin, completed-code-review, size-small, completed-rules-compliance, completed-testing

#7015 Collections v1.0.2.9
  stable/Collections/manifest.toml
  testing/live/Collections/manifest.toml
Labels: size-mid

#7016 DelvUI release 2.5.1.1
  stable/DelvUI/manifest.toml
Labels: size-small

#7023 VanillaPlus v1.0.2.1
  stable/VanillaPlus/manifest.toml
Labels: size-small

#7026 VanillaPlus v1.0.2.2
  stable/VanillaPlus/manifest.toml
Labels: size-small

#7027 NeatNoter 2.7.4 (Test)
  testing/live/NeatNoter/manifest.toml
Labels: size-mid

#7025 StatusTimers 1.0.1.3
  stable/StatusTimers/manifest.toml
  testing/live/StatusTimers/manifest.toml
Labels: size-small

#7029 VanillaPlus v1.0.2.3
  stable/VanillaPlus/manifest.toml
Labels: size-small

#7032 VanillaPlus v1.0.2.4
  stable/VanillaPlus/manifest.toml
Labels: size-small

#7033 [Stable] QuestJournal v1.2.0.2
  stable/QuestJournal/manifest.toml
Labels: size-small

#7034 MacroMate 1.0.25.5
  stable/MacroMate/manifest.toml
Labels: size-mid

#7035 VanillaPlus v1.0.2.5
  stable/VanillaPlus/manifest.toml
Labels: size-small

#7038 VanillaPlus v1.0.2.6
  stable/VanillaPlus/manifest.toml
Labels: size-large

#7041 VanillaPlus v1.0.3.0
  stable/VanillaPlus/manifest.toml
Labels: size-small
