Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-03, with the labels that each got.

#5481 [Testing] Altoholic v0.0.0.35
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5483 ChatContext v0.0.1.3
  stable/ChatContext/manifest.toml
Labels: size-small

#5488 VenueManager 2.5.2
  stable/VenueManager/manifest.toml
Labels: size-small

#5484 [Testing] MogMogCheck v3.1.0
  testing/live/MogMogCheck/images/icon.png
  testing/live/MogMogCheck/manifest.toml
Labels: size-small

#5487 [Testing] AcquisitionDate 0.2.0.0
  testing/live/AcquisitionDate/manifest.toml
Labels: size-large

#5486 [Testing] BisBuddy v0.1.0.0
  testing/live/BisBuddy/manifest.toml
Labels: size-large

#5482 Wholist v1.9.0.0
  stable/Wholist/manifest.toml
Labels: size-small

#5489 [Testing] GlamourSpamRemover-1.2.4.0
  testing/live/GlamourSpamRemover/manifest.toml
Labels: size-small

#5491 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-large

#5492 Wholist v1.9.1.0
  stable/Wholist/manifest.toml
Labels: size-small

#5493 BisBuddy v0.1.0.1
  testing/live/BisBuddy/manifest.toml
Labels: size-small

#5494 [Testing] Altoholic v0.0.0.36
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5495 [Testing] MogMogCheck v3.2.0
  testing/live/MogMogCheck/manifest.toml
Labels: size-small

#5496 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-mid

#5497 Eventy 1.0.3.0
  stable/Eventy/manifest.toml
Labels: size-small

#5498 ChatTranslated v3.3.2
  stable/ChatTranslated/manifest.toml
Labels: size-small

#5499 MogMogCheck v3.2.0
  stable/MogMogCheck/images/icon.png
  stable/MogMogCheck/manifest.toml
Labels: move channel, size-small

#5501 MogMogCheck v3.2.2
  stable/MogMogCheck/manifest.toml
Labels: size-small

#5502 ChatTranslated v3.3.2.1
  stable/ChatTranslated/manifest.toml
Labels: size-small

#5504 MogMogCheck v3.2.3
  stable/MogMogCheck/manifest.toml
  testing/live/MogMogCheck/images/icon.png
  testing/live/MogMogCheck/manifest.toml
Labels: size-small

#5505 [Testing] GlamourSpamRemover-1.2.5.0
  testing/live/GlamourSpamRemover/manifest.toml
Labels: size-small

#5506 GlamourSpamRemover-1.2.5.0
  stable/GlamourSpamRemover/manifest.toml
Labels: size-small

#5507 PvP Tracker v2.3.0.2
  stable/PvpStats/manifest.toml
Labels: size-small

#5511 [Testing] Altoholic v0.0.0.37
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5513 Allagan Tools 1.11.1.3
  stable/InventoryTools/manifest.toml
Labels: size-mid

#5514 JobTitles 0.2.0.0
  stable/JobTitles/manifest.toml
Labels: size-large

#5516 Accountant 1.7.0.2
  stable/Accountant/manifest.toml
Labels: size-small

#5515 [Testing] BisBuddy v0.1.1.0
  testing/live/BisBuddy/manifest.toml
Labels: size-large

#5520 Eureka Helper v2.0.2.0
  stable/EurekaHelper/manifest.toml
Labels: size-small

#5519 [Testing] Altoholic v0.0.0.38
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#5518 [Testing] Racingway v0.0.5.6
  testing/live/Racingway/manifest.toml
Labels: size-mid

#5521 [Testing] Racingway v0.0.5.7
  testing/live/Racingway/manifest.toml
Labels: size-small

#5379 Add ArchipelagoXIV Client
  testing/live/ArchipelagoXIV/images/icon.png
  testing/live/ArchipelagoXIV/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5517 Absolute Roleplay [Testing]
  testing/live/AbsoluteRoleplay/images/bio.png
  testing/live/AbsoluteRoleplay/images/bookmarks.png
  testing/live/AbsoluteRoleplay/images/gallery.png
  testing/live/AbsoluteRoleplay/images/story.png
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-large

#5467 [Testing] Sightseeingway 0.0.1
  testing/live/Sightseeingway/images/icon.png
  testing/live/Sightseeingway/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5522 Pet Nicknames v2.3.0.12
  stable/PetRenamer/manifest.toml
Labels: size-small

#5383 [Testing]DutyPusher
  testing/live/DutyPusher/images/icon.png
  testing/live/DutyPusher/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5524 NeatNoter 2.7.1
  stable/NeatNoter/manifest.toml
  testing/live/NeatNoter/manifest.toml
Labels: size-small

#5525 [Testing] Racingway v0.0.5.8
  testing/live/Racingway/images/icon.png
  testing/live/Racingway/manifest.toml
Labels: size-small

#5526 Glamaholic 1.10.13
  stable/Glamaholic/manifest.toml
Labels: size-small

#5527 ChatTwo 1.29.20
  stable/ChatTwo/manifest.toml
Labels: size-small

#5510 [Testing] CustomResolution v0.3.0.0 (init)
  testing/live/CustomResolution2782/images/icon.png
  testing/live/CustomResolution2782/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5528 EngageTimer v2.4.2.0
  stable/EngageTimer/manifest.toml
Labels: size-small

#5530 TooltipNotes 1.5.1
  stable/TooltipNotes/manifest.toml
Labels: size-small

#5529 BisBuddy v0.1.1.0
  stable/BisBuddy/images/icon.png
  stable/BisBuddy/images/inventory.png
  stable/BisBuddy/images/itemtooltip.png
  stable/BisBuddy/images/marketboard.png
  stable/BisBuddy/images/materiamelding.png
  stable/BisBuddy/images/needgreed.png
  stable/BisBuddy/images/npcshopexchange.png
  stable/BisBuddy/manifest.toml
Labels: move channel, size-large

#5531 PvP Tracker v2.3.1.0
  stable/PvpStats/manifest.toml
Labels: size-small

#5533 [Testing] Racingway v0.0.6.0
  testing/live/Racingway/manifest.toml
Labels: size-small

#5534 PushyFinder 1.3.0.2
  stable/PushyFinder/manifest.toml
Labels: size-small

#5532 Allagan Tools 1.11.1.4
  stable/InventoryTools/manifest.toml
Labels: size-small

#5535 Razer Reader Stable Release
  stable/RazerReader/images/icon.png
  stable/RazerReader/manifest.toml
Labels: move channel, size-large

#5537 [Testing] Altoholic v0.0.0.39
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#5539 [Testing] Racingway v0.0.6.1
  testing/live/Racingway/manifest.toml
Labels: size-small

#5542 JobTitles 0.2.0.1
  stable/JobTitles/manifest.toml
Labels: size-small

#5541 Fader 2.7.0.0
  stable/FaderPlugin/manifest.toml
Labels: size-large

#5543 Tippy 1.12.0.0
  stable/Tippy/manifest.toml
Labels: size-large

#5548 Pet Nicknames v2.3.0.14
  stable/PetRenamer/manifest.toml
Labels: size-small

#5544 [Testing] Altoholic v0.0.0.40
  testing/live/Altoholic/manifest.toml
Labels: size-mid

#5549 Pet Nicknames v2.3.0.14
  stable/PetRenamer/manifest.toml
Labels: size-small

#5545 Weatherman 2.4.1.2
  stable/Weatherman/manifest.toml
Labels: size-large

#5550 BisBuddy v0.1.1.1
  stable/BisBuddy/manifest.toml
Labels: size-small

#5555 Update FCNameColor to 5.1.0.0
  stable/FCNameColor/manifest.toml
Labels: size-small

#5559 Stormtalons 1.1.0.6
  stable/Stormtalons/manifest.toml
Labels: size-small

#5560 UsedName v0.8.9.0
  stable/UsedName/manifest.toml
Labels: size-small

#5599 PingPlugin v2.8.1
  stable/PingPlugin/manifest.toml
Labels: size-small

#5597 ChatTwo 1.30.0
  stable/ChatTwo/manifest.toml
Labels: size-small

#5596 NamePlateDebuffs 1.1.0.5
  stable/NamePlateDebuffs/manifest.toml
Labels: size-small

#5595 ContactsTracker 1.0.3
  stable/ContactsTracker/manifest.toml
Labels: size-small

#5593 ShopItemRevealer [1.1.2]
  stable/ShopItemRevealer/manifest.toml
  testing/live/ShopItemRevealer/images/icon.png
  testing/live/ShopItemRevealer/manifest.toml
Labels: size-small

#5592 Emote log v1.1.4.0
  stable/EmoteLog/manifest.toml
Labels: size-small

#5591 CoordImporter v1.2.0.3
  stable/CoordImporter/manifest.toml
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#5573 [Testing] Racingway v0.0.6.3
  testing/live/Racingway/manifest.toml
Labels: size-small

#5575 Browsingway 1.6.4.0
  stable/Browsingway/manifest.toml
Labels: size-small

#5576 FlyTextFilter 4.3.0.1
  stable/FlyTextFilter/manifest.toml
Labels: size-small

#5577 SubmarineTracker 1.9.9.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5580 [Testing] CustomResolution v0.3.1.0
  testing/live/CustomResolution2782/manifest.toml
Labels: size-small

#5581 Tracky 1.5.8.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5583 Hybrid Camera 1.5.0.0 (API12)
  stable/HybridCamera/manifest.toml
Labels: size-small

#5584 Resizable HUD 1.4.0.0 (API12)
  stable/ResizableHUD/manifest.toml
Labels: size-small

#5585 Target Lines 1.8.0.0 (API12)
  stable/TargetLines/manifest.toml
Labels: size-small

#5586 AbilityAnts 1.0.0.4
  stable/AbilityAnts/manifest.toml
Labels: size-small

#5588 [Testing] Gauge-O-Matic 0.8.1.6 (API12)
  testing/live/GaugeOMatic/manifest.toml
Labels: size-small

#5589 Crossup 1.7.0.8 (API12)
  stable/CrossUp/manifest.toml
Labels: size-small

#5614 ChatTwo 1.30.1
  stable/ChatTwo/manifest.toml
Labels: size-small

#5607 WaymarkPresetPlugin 1.5.4.0
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#5613 Tracky 1.5.8.1
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5558 JobTitles 0.2.0.2
  stable/JobTitles/manifest.toml
Labels: size-small

#5612 Update manifest.toml
  stable/Doorbell/manifest.toml
Labels: size-small

#5611 [Graphics Config] Update for 7.2
  stable/GraphicsConfig/manifest.toml
Labels: size-small

#5610 [Random Class Selector] Updated for 7.2
  stable/RandomClassSelector/manifest.toml
Labels: size-small

#5609 [Teamcraft List Maker] Update for patch 7.2
  stable/TeamcraftListMaker/manifest.toml
Labels: size-small

#5608 [TwitchXIV] Update for 7.2
  stable/TwitchXIV/manifest.toml
Labels: size-small

#5606 [Testing] rtyping 0.1.0.6
  testing/live/rtyping/manifest.toml
Labels: size-small

#5605 LogogramHelper 0.0.3.4
  stable/LogogramHelper/manifest.toml
Labels: size-small

#5598 VanillaHotbarExtender 1.2.2
  testing/live/VanillaHotbarExtender/manifest.toml
Labels: size-small

#5622 SelfCare v0.2.2
  stable/SelfCare/manifest.toml
Labels: size-small

#5561 FPS Plugin 1.7.0.2
  stable/FPSPlugin/manifest.toml
Labels: size-small

#5562 Macro Chain 2.2.0.2
  stable/MacroChain/manifest.toml
Labels: size-small

#5563 Simple Map Tracker 1.0.2
  stable/SimpleMapTracker/manifest.toml
Labels: size-small

#5568 Adventurer in Need 1.5.0.3
  stable/AdventurerInNeed/manifest.toml
Labels: size-small

#5554 Update Dalamud.LoadingImage and Dalamud.FullscreenCutscenes to API12
  stable/Dalamud.FullscreenCutscenes/Dalamud.FullscreenCutscenes.toml
  stable/Dalamud.LoadingImage/manifest.toml
Labels: size-small

#5579 RemotePartyFinder 1.0.16
  stable/RemotePartyFinder/manifest.toml
Labels: size-mid

#5571 Update HighFpsPhysics Plugin for 7.2 and change ownership
  stable/HighFpsPhysicsPlugin/manifest.toml
Labels: size-mid

#5566 Plugin updates for 7.2
  stable/EnmityHp/manifest.toml
  stable/JustBackup/manifest.toml
  stable/Messenger/manifest.toml
  stable/Mini/manifest.toml
  stable/NotificationMaster/manifest.toml
  stable/QuestAWAY/manifest.toml
  stable/Weatherman/manifest.toml
Labels: size-small

#5564 Honorific 1.5.2.0
  stable/Honorific/manifest.toml
Labels: size-small

#5565 Redirect 1.2.5.0
  stable/Redirect/manifest.toml
Labels: size-small

#5552 XIVDeck 0.3.23
  stable/XIVDeck.FFXIVPlugin/manifest.toml
Labels: size-small

#5601 TPie release 1.11.0.0
  stable/TPie/manifest.toml
Labels: size-small

#5600 DelvCD release 1.3.0.0
  stable/DelvCD/manifest.toml
Labels: size-small

#5602 DelvUI release 2.4.0.0
  stable/DelvUI/manifest.toml
Labels: size-small

#5603 NOTED release 1.5.0.0
  stable/NOTED/manifest.toml
Labels: size-small

#5604 ActionTimeline release 1.6.0.0
  stable/ActionTimeline/manifest.toml
Labels: size-small

#5556 [EnemyListDebuffs] 7.2 Update
  stable/EnemyListDebuffs/manifest.toml
Labels: size-small

#5569 ExpandedSearchInfo 1.4.2
  stable/ExpandedSearchInfo/manifest.toml
Labels: size-small

#5615 XIVCombo v2.0.1.0
  stable/XIVCombo/manifest.toml
Labels: size-small

#5616 SubmarineTracker 1.9.9.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5617 Chat Bubbles v2.1.7.3
  stable/ChatBubbles/manifest.toml
Labels: size-small

#5618 BetterTargetingSystem v0.0.13
  testing/live/BetterTargetingSystem/manifest.toml
Labels: size-small

#5619 ReadyCheckHelper 1.0.8.0
  stable/ReadyCheckHelper/manifest.toml
Labels: size-small

#5620 Elden Ring v0.0.3.2
  stable/EldenRing/manifest.toml
Labels: size-small

#5623 XIVUncombo v1.0.1.0
  stable/XIVUncombo/manifest.toml
Labels: size-small

#5624 ItemSearch v1.10.2.0
  stable/ItemSearchPlugin/manifest.toml
Labels: size-large

#5625 SillyChat v1.7.1.1
  stable/SillyChat/manifest.toml
Labels: size-small

#5626 BetterPartyFinder 1.5.2
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#5627 MonsterDex 2.12.2
  stable/DeepDungeonDex/manifest.toml
Labels: size-small

#5666 FastJobSwitcher v2.2.0.0 - Upgrade to API12
  stable/FastJobSwitcher/manifest.toml
Labels: size-small

#5665 AutoBGM v1.3.0.0 - Upgrade to API12
  stable/AutoBGM/manifest.toml
Labels: size-small

#5664 Fader 2.7.1.0
  stable/FaderPlugin/manifest.toml
Labels: size-small

#5663 TiltedPlugin v4.2.0.0 - Upgrade to API12
  stable/Tilted/manifest.toml
  testing/live/Tilted/images/icon.png
  testing/live/Tilted/manifest.toml
Labels: size-small

#5662 Clarity In Chaos v2.2.0.0 - Entity highlight + Upgrade to API12
  stable/ClarityInChaos/manifest.toml
  testing/live/ClarityInChaos/images/icon.png
  testing/live/ClarityInChaos/manifest.toml
Labels: size-small

#5659 StackSellPrice 4.5.0
  stable/StackSellPrice/manifest.toml
Labels: size-small

#5668 SubmarineTracker 1.9.9.2
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5658 PriceCheck 2.7.3.0
  stable/PriceCheck/manifest.toml
Labels: size-small

#5656 beeg dinosaur eat window api bump
  stable/BeegWindow/manifest.toml
Labels: size-small

#5654 RezPls 1.5.0.0
  stable/RezPls/manifest.toml
Labels: size-small

#5653 EurekaLinker 1.5.3.0
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#5652 OpenerCreator 0.4.0
  stable/OpenerCreator/manifest.toml
Labels: size-small

#5651 Seated Sidekick Spectator v1.0.0
  stable/SeatedSidekickSpectator/images/icon.png
  stable/SeatedSidekickSpectator/manifest.toml
  testing/live/SeatedSidekickSpectator/manifest.toml
Labels: move channel, size-small

#5649 Combat Cursor Containment v1.0.6
  stable/CombatCursorContainment/manifest.toml
Labels: size-small

#5647 MBHistory 1.0.2.0
  stable/MBHistory/manifest.toml
Labels: size-small

#5646 Inspecto 0.0.0.3
  testing/live/Inspecto/manifest.toml
Labels: size-small

#5645 Hunty 1.3.3.0
  stable/Hunty/manifest.toml
Labels: size-small

#5644 Dialog Copy 1.2.2.0
  stable/TalkCopy/manifest.toml
Labels: size-small

#5643 Eventy 1.0.2.0
  stable/Eventy/manifest.toml
Labels: size-small

#5641 ChatAlerts 2.2.1.0
  stable/ChatAlerts/manifest.toml
Labels: size-small

#5640 Directional 0.0.3.0
  stable/Directional/manifest.toml
Labels: size-small

#5628 JobTitles but without fun
  stable/JobTitles/manifest.toml
Labels: size-small

#5638 DiademCalculator 1.1.2.0
  stable/DiademCalculator/manifest.toml
Labels: size-small

#5637 DeathRoll 1.5.4.0
  stable/DeathRoll/manifest.toml
Labels: size-small

#5629 BetterPlaytime 1.4.2.0
  stable/BetterPlaytime/manifest.toml
Labels: size-small

#5636 EurekaHelper v2.0.2.1
  stable/EurekaHelper/manifest.toml
Labels: size-small
