Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-01, with the labels that each got.

#5292 Bozja Buddy 1.1.6.4
  stable/BozjaBuddy/manifest.toml
Labels: size-small

#5297 [RetainerSales] fix error when opening unrelated selectstring addon
  testing/live/RetainerSales/manifest.toml
Labels: size-small

#5296 [Testing] AcquisitionDate 0.1.1.0
  testing/live/AcquisitionDate/manifest.toml
Labels: size-small

#5295 [Testing] Altoholic v0.0.0.30
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5294 AFKMute into stable repo from testing repo.
  stable/AFKMute/images/icon.png
  stable/AFKMute/manifest.toml
Labels: move channel, size-small

#5213 [Testing] Allagan Item Search 1.0.0.0
  testing/live/AllaganItemSearch/images/icon.png
  testing/live/AllaganItemSearch/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5299 EurekaHelper v2.0.1.2
  stable/EurekaHelper/manifest.toml
Labels: size-small

#5298 [Testing] ShopItemRevealer v1.0.2
  testing/live/ShopItemRevealer/manifest.toml
Labels: size-small

#5300 [Testing] PlayerTrack v3.4.13
  testing/live/PlayerTrack/manifest.toml
Labels: size-small

#5302 Umbra 2.3.8
  stable/Umbra/manifest.toml
Labels: size-small

#5301 Tracky 1.5.6.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5303 [Testing] Allagan Item Search 1.0.0.1
  testing/live/AllaganItemSearch/manifest.toml
Labels: size-small

#5304 RemotePartyFinder 1.0.15
  stable/RemotePartyFinder/manifest.toml
Labels: size-small

#5305 [DragoonMayCry] 1.2.4.1
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#5306 Umbra 2.3.9
  stable/Umbra/manifest.toml
Labels: size-small

#5310 Shop Item Revealer v1.0.2
  stable/ShopItemRevealer/images/icon.png
  stable/ShopItemRevealer/manifest.toml
Labels: move channel, size-small

#5309 EurekaLinker 1.5.2.1
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#5308 [Testing] CurrencySpender 1.0.4
  testing/live/CurrencySpender/manifest.toml
Labels: size-mid

#5217 [Testing] Add ContactsTracker
  testing/live/ContactsTracker/images/icon.png
  testing/live/ContactsTracker/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5317 BigNaelQuotes 0.0.5
  testing/live/BigNaelQuotes/manifest.toml
Labels: size-small

#5320 BetterPartyFinder 1.5.0
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#5319 CWLSLastSeenTool 1.1.3.0
  stable/CWLSLastSeenTool/manifest.toml
Labels: size-small

#5318 [Testing] ContactsTracker v0.1.0.2
  testing/live/ContactsTracker/manifest.toml
Labels: size-small

#5315 Directional 0.0.2
  stable/Directional/manifest.toml
Labels: size-small

#5314 SelfCare v0.2.1
  stable/SelfCare/manifest.toml
Labels: size-small

#5313 [Stable] NoSoliciting v3.1.2
  stable/NoSoliciting/manifest.toml
Labels: size-small

#5311 [Testing] PlayerTrack v3.4.14
  testing/live/PlayerTrack/manifest.toml
Labels: size-small

#5312 OpenerCreator 0.3.2
  stable/OpenerCreator/manifest.toml
Labels: size-mid

#5321 Himbeertoni Raid Tool 1.8.0.2
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-mid

#5293 XIVCombo v2.0.0.0
  stable/XIVCombo/manifest.toml
  testing/live/XIVCombo/images/icon.png
  testing/live/XIVCombo/manifest.toml
Labels: completed-code-review, move channel, size-large

#5323 [Testing] ContactsTracker v0.1.0.3
  testing/live/ContactsTracker/manifest.toml
Labels: size-small

#5324 XIVCombo 2.0.0.1
  testing/live/XIVCombo/manifest.toml
Labels: size-small

#5325 [Testing] Allagan Item Search 1.0.0.2
  testing/live/AllaganItemSearch/manifest.toml
Labels: size-small

#5326 XIVCombo v2.0.0.2
  testing/live/XIVCombo/manifest.toml
Labels: size-small

#5327 EngageTimer v2.4.1.2
  stable/EngageTimer/manifest.toml
Labels: size-small

#5328 Allagan Market 1.1.0.3
  stable/AllaganMarket/manifest.toml
Labels: size-small

#5329 Tracky 1.5.6.2
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5330 [stable] Update AFKMute to 1.0.0.4
  stable/AFKMute/manifest.toml
Labels: size-small

#5331 [Testing] ContactsTracker v0.2.0.0
  testing/live/ContactsTracker/manifest.toml
Labels: size-small

#5335 QuietDen - Moving plugin from testing to stable
  stable/QuietDen/images/icon.png
  stable/QuietDen/manifest.toml
Labels: move channel, size-small

#5334 XIVCombo v2.0.0.3
  testing/live/XIVCombo/manifest.toml
Labels: size-small

#5332 Pet Nicknames v2.3.0.9
  stable/PetRenamer/manifest.toml
Labels: size-small

#5333 [Testing] Acquisition Date 0.1.1.1
  testing/live/AcquisitionDate/manifest.toml
Labels: size-small

#5338 XIVCombo v2.0.0.4
  testing/live/XIVCombo/manifest.toml
Labels: size-small

#5337 CurrencySpender 1.0.5
  testing/live/CurrencySpender/manifest.toml
Labels: size-small

#5336 [RetainerSales] Leave testing
  stable/RetainerSales/images/icon.png
  stable/RetainerSales/manifest.toml
Labels: move channel, size-small

#5322 BigNaelQuotes testing -> [Stable]
  stable/BigNaelQuotes/images/icon.png
  stable/BigNaelQuotes/manifest.toml
Labels: move channel, size-small

#5340 [Testing] Acquisition Date 0.1.1.2
  testing/live/AcquisitionDate/manifest.toml
Labels: size-small

#5339 [Testing] BetterShadows 1.4.5
  syncfork.cmd
  testing/live/BetterShadows/manifest.toml
Labels: size-mid

#5341 CurrencySpender: Leave testing branch
  stable/CurrencySpender/images/icon.png
  stable/CurrencySpender/manifest.toml
Labels: move channel, size-small

#5342 Update EasyTranslate to version 4.1.0
  stable/EasyTranslate.DalamudPlugin/manifest.toml
Labels: size-small

#5343 Shop Item Revealer v1.1.0
  stable/ShopItemRevealer/manifest.toml
Labels: size-large

#5316 [Testing] Simple Map Tracker - New Plugin
  testing/live/SimpleMapTracker/images/icon.png
  testing/live/SimpleMapTracker/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5307 [Testing] Inspecto 0.0.0.1
  testing/live/Inspecto/images/icon.png
  testing/live/Inspecto/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5344 ChatContext v0.0.1.2
  stable/ChatContext/manifest.toml
Labels: size-small

#5346 Echoglossian v3.20.x released
  stable/Echoglossian/manifest.toml
Labels: size-mid

#5345 MOAction 4.4.2
  stable/MOAction/manifest.toml
Labels: size-large

#5348 Allagan Tools 1.11.0.10
  stable/InventoryTools/manifest.toml
Labels: size-large

#5350 Update Tidy Chat 2.0.13
  stable/TidyChat/manifest.toml
Labels: size-small

#5353 [Testing] ContactsTracker v0.2.0.1
  testing/live/ContactsTracker/manifest.toml
Labels: size-small

#5355 BetterPlaytime 1.4.1.1
  stable/BetterPlaytime/manifest.toml
Labels: size-mid

#5352 MBHistory 1.0.1.2
  stable/MBHistory/manifest.toml
Labels: size-small

#5351 Eventy 1.0.2.2
  stable/Eventy/manifest.toml
Labels: size-small

#5354 [moving to stable] XIVCombo v2.0.0.5
  stable/XIVCombo/manifest.toml
  testing/live/XIVCombo/images/icon.png
  testing/live/XIVCombo/manifest.toml
Labels: size-large

#5356 [Testing] AcquisitionDate 0.1.1.3
  testing/live/AcquisitionDate/manifest.toml
Labels: size-small

#5357 Eventy 1.0.2.3
  stable/Eventy/manifest.toml
Labels: size-small

#5358 Accountant 1.7.0.1
  stable/Accountant/manifest.toml
Labels: size-small

#5359 XIVCombo v2.0.0.6
  stable/XIVCombo/manifest.toml
Labels: size-small

#5361 XIVLogger 1.0.7.3
  stable/XIVLogger/manifest.toml
Labels: size-large

#5362 [Testing] PlayerTrack v3.4.15
  testing/live/PlayerTrack/manifest.toml
Labels: size-small

#5363 Shop Item Revealer v1.1.1
  stable/ShopItemRevealer/manifest.toml
Labels: size-large

#5364 Himbeertoni Raid Tool 1.8.0.3
  stable/HimbeertoniRaidTool/manifest.toml
Labels: size-small

#5365 [Stable] NextUIPlugin stable version 11.0.0.0
  stable/NextUIPlugin/manifest.toml
Labels: size-small

#5369 QoL Bar v2.3.3.3
  stable/QoLBar/manifest.toml
Labels: size-small

#5368 Collections v1.0.2.1 - Update for API 11
  stable/Collections/manifest.toml
  testing/live/Collections/manifest.toml
Labels: size-mid

#5371 Collections v1.0.2.2
  stable/Collections/manifest.toml
  testing/live/Collections/manifest.toml
Labels: size-small

#5372 PvP Tracker v2.2.1.0
  stable/PvpStats/manifest.toml
Labels: size-small

#5373 Simple Tweaks 1.10.6
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-large

#5374 PriceCheck 2.7.2.0
  stable/PriceCheck/manifest.toml
Labels: size-large

#5375 Fader 2.6.2.6
  stable/FaderPlugin/manifest.toml
Labels: size-large

#5376 Fader 2.6.2.7
  stable/FaderPlugin/manifest.toml
Labels: size-small

#5377 Title Edit v3.0.4.4
  stable/TitleEdit/manifest.toml
Labels: size-small

#5367 [Testing] RezoPlugin v1.0.0.1
  testing/live/RezoPlugin/images/icon.png
  testing/live/RezoPlugin/images/image1.png
  testing/live/RezoPlugin/images/image2.png
  testing/live/RezoPlugin/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5349 [testing/live] NowPlaying 1.0.0.0
  testing/live/NowPlaying/images/icon.png
  testing/live/NowPlaying/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5380 CurrencySpender 1.1.0
  stable/CurrencySpender/manifest.toml
Labels: size-large

#5385 MonsterLootHunter 1.2.24.7
  stable/MonsterLootHunter/manifest.toml
Labels: size-small

#5384 [Testing] Altoholic v0.0.0.31
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5382 Dalamud.RichPresence 2.0.6.5
  stable/Dalamud.RichPresence/manifest.toml
Labels: size-small

#5387 [stable] WorkshopOptimizerPlugin update to 0.3.0.1
  stable/WorkshopOptimizerPlugin/manifest.toml
Labels: size-small

#5389 [Testing] Altoholic v0.0.0.32
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5390 Honorific 1.5.1
  stable/Honorific/manifest.toml
Labels: size-small

#5392 Honorific 1.5.1.1
  stable/Honorific/manifest.toml
Labels: size-small

#5391 NoSoliciting v3.1.4.0
  stable/NoSoliciting/manifest.toml
Labels: size-small

#5393 Tracky 1.5.7.0
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5394 SubmarineTracker 1.9.6.0
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5395 [testing/live] NowPlaying 1.1.0.0
  testing/live/NowPlaying/manifest.toml
Labels: size-small

#5396 CurrencySpender 1.1.1
  stable/CurrencySpender/manifest.toml
Labels: size-small

#5397 Honorific 1.5.1.2
  stable/Honorific/manifest.toml
Labels: size-small

#5398 Simple Map Tracker to stable
  stable/SimpleMapTracker/images/icon.png
  stable/SimpleMapTracker/manifest.toml
Labels: move channel, size-small

#5399 JobTitles 0.1.0.0
  stable/JobTitles/images/icon.png
  stable/JobTitles/manifest.toml
  testing/live/JobTitles/manifest.toml
Labels: move channel, size-mid

#5400 WaymarkPresetPlugin 1.5.3.0
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-large

#5401 Umbra 2.3.10
  stable/Umbra/manifest.toml
Labels: size-small

#5404 JobTitles 0.1.1.0
  stable/JobTitles/manifest.toml
Labels: size-small

#5403 [testing/live] NowPlaying 1.2.0.0
  testing/live/NowPlaying/manifest.toml
Labels: size-small

#5406 [stable] NowPlaying 1.3.0.0
  stable/NowPlaying/images/icon.png
  stable/NowPlaying/manifest.toml
  testing/live/NowPlaying/manifest.toml
Labels: move channel, size-small

#5407 WaymarkPresetPlugin 1.5.3.1
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#5409 Wholist v1.8.2.0
  stable/Wholist/manifest.toml
Labels: size-small

#5408 WaymarkPresetPlugin 1.5.3.2
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small
