Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-02, with the labels that each got.

#5410 Simple Tweaks 1.10.7.0
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#5411 Simple Map Tracker 1.0.1
  stable/SimpleMapTracker/manifest.toml
Labels: size-small

#5413 Allagan Tools 1.11.0.11
  stable/InventoryTools/manifest.toml
Labels: size-large

#5415 DragoonMayCry 1.2.5.0
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#5419 [Testing] Altoholic v0.0.0.33
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5418 ChatTwo 1.29.17
  stable/ChatTwo/manifest.toml
Labels: size-small

#5417 WaymarkPresetPlugin 1.5.3.3
  stable/WaymarkPresetPlugin/manifest.toml
Labels: size-small

#5416 Allagan Tools 1.11.0.12
  stable/InventoryTools/manifest.toml
Labels: size-small

#5422 ChatTwo 1.29.18
  stable/ChatTwo/manifest.toml
Labels: size-small

#5378 Razer Reader Initial Testing Release
  testing/live/RazerReader/images/icon.png
  testing/live/RazerReader/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5423 [Testing] RezoPlugin v1.1.0.1
  testing/live/RezoPlugin/manifest.toml
Labels: size-small

#5424 SubmarineTracker 1.9.7.0
  stable/SubmarineTracker/manifest.toml
Labels: size-mid

#5426 NoSoliciting 3.1.5.0
  stable/NoSoliciting/manifest.toml
Labels: size-small

#5428 MacroRecorded 1.0.4.2
  stable/MacroRecorded/manifest.toml
Labels: size-small

#5429 [stable] NowPlaying 1.3.0.1
  stable/NowPlaying/manifest.toml
Labels: size-small

#5430 SubmarineTracker 1.9.7.1
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5431 SubmarineTracker 1.9.7.3
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#5433 [Testing] ContactsTracker v0.3.0.1
  testing/live/ContactsTracker/manifest.toml
Labels: size-small

#5434 VenueManager @2.5.1
  stable/VenueManager/manifest.toml
Labels: size-small

#5425 CurrencySpender 1.1.2
  stable/CurrencySpender/manifest.toml
Labels: size-mid

#5437 Adventurer in Need 1.5.0.2
  stable/AdventurerInNeed/manifest.toml
Labels: size-small

#5438 [Testing] Who's Talking 0.8.3.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#5436 PvpStats v2.3.0.0
  stable/PvpStats/manifest.toml
Labels: size-mid

#5386 PlayerTrack 3.5.0.0
  stable/PlayerTrack/manifest.toml
Labels: size-large

#5388 VFXEditor v1.9.1.5
  stable/VFXEditor/manifest.toml
Labels: size-large

#5427 Hunty 1.3.2.0
  stable/Hunty/manifest.toml
Labels: size-large

#5439 Dalamud.RichPresence 2.0.6.6
  stable/Dalamud.RichPresence/manifest.toml
Labels: size-small

#5412 Add NoTypeSay
  testing/live/NoTypeSay/images/icon.png
  testing/live/NoTypeSay/images/image1.png
  testing/live/NoTypeSay/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5442 PlayerTrack 3.5.0.1
  stable/PlayerTrack/manifest.toml
Labels: size-small

#5443 Hunty 1.3.2.1
  stable/Hunty/manifest.toml
Labels: size-small

#5444 Toastingway [1.2.0.0] update
  stable/ToastingwayPlugin/manifest.toml
Labels: size-small

#5441 SubmarineTracker 1.9.8.1
  stable/SubmarineTracker/manifest.toml
Labels: size-large

#5448 ContactsTracker v1.0.0 - To stable
  stable/ContactsTracker/images/icon.png
  stable/ContactsTracker/manifest.toml
Labels: move channel, size-small

#5449 PlayerTrack 3.5.0.2
  stable/PlayerTrack/manifest.toml
Labels: size-small

#5451 Tracky 1.5.7.1
  stable/TrackyTrack/manifest.toml
Labels: size-small

#5450 [Testing] TextToTalk v1.30.6
  testing/live/TextToTalk/manifest.toml
Labels: size-small

#5455 Wholist v1.8.2.1
  stable/Wholist/manifest.toml
Labels: size-small

#5453 Update AutoMountBgm (stable)
  stable/AutoMountBgm/manifest.toml
Labels: size-small

#5454 ContactsTracker v1.0.1
  stable/ContactsTracker/manifest.toml
Labels: size-small

#5456 [Testing] Altoholic v0.0.0.34
  testing/live/Altoholic/manifest.toml
Labels: size-small

#5457 CurrencyAlert v2.2.0.4
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#5462 CurrencyAlert v2.2.0.5
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#5466 CoordImporter v1.2.0.2
  stable/CoordImporter/manifest.toml
  testing/live/CoordImporter/manifest.toml
Labels: size-small

#5465 Pet Nicknames v2.3.0.10
  stable/PetRenamer/manifest.toml
Labels: size-small

#5464 Title Edit v3.0.4.8
  stable/TitleEdit/manifest.toml
Labels: size-mid

#5463 [Testing] Who's Talking 0.8.4.0
  testing/live/WhosTalking/manifest.toml
Labels: size-small

#5460 ContactsTracker v1.0.2.0
  stable/ContactsTracker/manifest.toml
Labels: size-mid

#5459 SonarPlugin v0.6.9.0
  stable/SonarPlugin/manifest.toml
Labels: size-large

#5468 JobTitles 0.1.2.0
  stable/JobTitles/manifest.toml
Labels: size-small

#5458 [Testing] MogMogCheck v3.0.1
  testing/live/MogMogCheck/images/icon.png
  testing/live/MogMogCheck/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5440 Submit Racingway plugin.
  testing/live/Racingway/images/icon.png
  testing/live/Racingway/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5381 [Testing]DoTCalculator 0.0.0.2
  testing/live/DotCalculator/images/icon.png
  testing/live/DotCalculator/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#5471 Allagan Tools 1.11.1.0
  stable/InventoryTools/manifest.toml
Labels: size-large

#5472 [Testing] Racingway v0.0.4.3
  testing/live/Racingway/manifest.toml
Labels: size-small

#5473 Allagan Tools 1.11.1.1
  stable/InventoryTools/manifest.toml
Labels: size-small

#5474 DragoonMayCry 1.2.6.0
  stable/DragoonMayCry/manifest.toml
Labels: size-small

#5478 JobTitles 0.1.2.1
  stable/JobTitles/manifest.toml
Labels: size-small

#5479 [Testing] MogMogCheck v3.0.3
  testing/live/MogMogCheck/manifest.toml
Labels: size-small

#5476 Allagan Tools 1.11.1.2
  stable/InventoryTools/manifest.toml
Labels: size-small
