Repository goatcorp/DalamudPluginsD17, pull requests merged in 2025-07, with the labels that each got.

#6255 add new plugin WDIGViewer
  testing/live/WDIGViewer/images/icon.png
  testing/live/WDIGViewer/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6339 BlackjackPlugin first time release
  testing/live/BlackjackPlugin/images/icon.png
  testing/live/BlackjackPlugin/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6346 [Testing] Altoholic v0.0.0.55
  testing/live/Altoholic/manifest.toml
Labels: size-small

#6349 PvPAnnouncer v1.1.0.0
  stable/PvPAnnouncer/manifest.toml
Labels: size-small

#6348 MogMogCheck v3.2.4
  stable/MogMogCheck/manifest.toml
Labels: size-small

#6352 [Testing] Altoholic v0.0.0.56
  testing/live/Altoholic/manifest.toml
Labels: size-small

#6351 Update AetherFM manifest for v1.1.0: HUD restyle, new features, and latest commit hash
  testing/live/AetherFM/manifest.toml
Labels: size-mid

#6354 FastWaymarksPlugin 1.3.1
  testing/live/FastWaymarksPlugin/manifest.toml
Labels: size-small

#6355 DelvUI release 2.4.0.2
  stable/DelvUI/manifest.toml
Labels: size-small

#6357 EurekaLinker 1.5.7.1
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6358 Namingway v1.1.18.0
  stable/Namingway/manifest.toml
Labels: size-small

#6356 [Testing] XIVInstantMessenger 1.5.0.6
  testing/live/Messenger/manifest.toml
Labels: size-large

#6360 PvPAnnouncer v1.2.0.0
  stable/PvPAnnouncer/manifest.toml
Labels: size-small

#6361 Wordsmith v 1.15.5
  stable/Wordsmith/manifest.toml
Labels: size-small

#6362 [Testing] XIVInstantMessenger 1.5.0.7
  testing/live/Messenger/manifest.toml
Labels: size-small

#6364 WhoDidThat v1.8.2.0
  stable/WhoDidThat/manifest.toml
Labels: size-small

#6367 Fix CategoryTags for PvPAnnouncer, WhoDidThat
  stable/PvPAnnouncer/manifest.toml
  stable/WhoDidThat/manifest.toml
Labels: size-small

#6369 Wikilinx Rightclicks v0.0.0.3
  stable/Wikilinx/manifest.toml
Labels: size-small

#6371 Allagan Tools 1.12.0.21
  stable/InventoryTools/manifest.toml
Labels: size-large

#6377 Sightseeingway 1.1.0.2
  stable/Sightseeingway/manifest.toml
Labels: size-small

#6374 ContactsTracker v1.0.5
  stable/ContactsTracker/manifest.toml
Labels: size-small

#6372 WhichMount 1.3.5
  stable/WhichMount/manifest.toml
Labels: size-small

#6376 WDIGViewer v1.0.3.0
  testing/live/WDIGViewer/manifest.toml
Labels: size-mid

#6379 [Testing] CustomResolution v0.4.2.0
  testing/live/CustomResolution2782/manifest.toml
Labels: size-large

#6378 PvPAnnouncer v1.2.1.0
  stable/PvPAnnouncer/manifest.toml
Labels: size-small

#6390 [Testing] Umbra 3.0.9
  testing/live/Umbra/manifest.toml
Labels: size-small

#6391 [Testing] Altoholic v0.0.0.57
  testing/live/Altoholic/manifest.toml
Labels: size-small

#6389 [Testing] XIVInstantMessenger 1.5.0.9
  testing/live/Messenger/manifest.toml
Labels: size-mid

#6395 [Stable] Quest Journal v1.1.4.0
  stable/QuestJournal/manifest.toml
Labels: size-small

#6388 CurrencyAlert v2.2.1.10
  testing/live/CurrencyAlert/manifest.toml
Labels: size-mid

#6394 Umbra 3.0.10
  stable/Umbra/manifest.toml
  testing/live/Umbra/images/icon.png
  testing/live/Umbra/manifest.toml
Labels: size-large

#6398 AetherDraw v2.2.2.0
  testing/live/AetherDraw/manifest.toml
Labels: size-small

#6402 CurrencyAlert v2.2.1.11
  testing/live/CurrencyAlert/manifest.toml
Labels: size-small

#6401 DailyDuty v5.3.1.8
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#6324 Allagan Tetris 1.0.0.0
  testing/live/AllaganTetris/images/icon.png
  testing/live/AllaganTetris/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6411 SubmarineTracker 1.9.9.9
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#6409 NoTankYou v7.2.2.1
  testing/live/NoTankYou/manifest.toml
Labels: size-large

#6344 [Testing] Photobooth initial release
  testing/live/Photobooth/images/icon.png
  testing/live/Photobooth/images/image1.png
  testing/live/Photobooth/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6414 DailyDuty v5.3.1.10
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#6417 CurrencyAlert v2.2.2.0
  stable/CurrencyAlert/manifest.toml
Labels: size-small

#6416 NoTankYou v7.2.2.2
  testing/live/NoTankYou/manifest.toml
Labels: size-small

#6421 TextToTalk v1.32.1
  stable/TextToTalk/manifest.toml
Labels: size-large

#6428 Chat Bubbles v2.1.8.0
  stable/ChatBubbles/manifest.toml
Labels: size-small

#6429 XIVCombo v2.0.1.1
  stable/XIVCombo/manifest.toml
Labels: size-small

#6432 SubmarineTracker 1.9.9.10
  stable/SubmarineTracker/manifest.toml
Labels: size-small

#6435 FatalFrame1.0.1.1
  stable/XivFatalFrame/manifest.toml
Labels: size-small

#6436 ChillFrames v3.1.1.4
  stable/ChillFrames/manifest.toml
Labels: size-small

#6437 EurekaLinker 1.5.8.1
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6410 AetherBreakout v1.2.0.1
  testing/live/AetherBreakout/images/icon.png
  testing/live/AetherBreakout/images/image1.png
  testing/live/AetherBreakout/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6380 New plugin submission: "MyPF"
  testing/live/MyPF/images/icon.png
  testing/live/MyPF/manifest.toml
Labels: new plugin, completed-code-review, size-large, completed-rules-compliance, completed-testing

#6338 SoundEffectMuter v1.0.0.0
  testing/live/SoundEffectMuter/images/icon.png
  testing/live/SoundEffectMuter/manifest.toml
Labels: new plugin, completed-code-review, size-mid, pending-testing, completed-rules-compliance

#6438 DailyDuty v5.3.1.11
  testing/live/DailyDuty/manifest.toml
Labels: size-small

#6439 TextToTalk v1.32.2
  stable/TextToTalk/manifest.toml
Labels: size-small

#6440 NoTankYou v7.2.2.4
  stable/NoTankYou/manifest.toml
Labels: size-small

#6443 WDIGViewer v1.0.3.0 testing to stable
  stable/WDIGViewer/images/icon.png
  stable/WDIGViewer/manifest.toml
Labels: move channel, size-large

#6447 DailyDuty v5.3.2.1
  stable/DailyDuty/manifest.toml
Labels: size-small

#6451 EurekaLinker 1.5.8.2
  stable/EurekaTrackerAutoPopper/manifest.toml
Labels: size-small

#6453 Pet Nicknames v2.4.1.1
  stable/PetRenamer/manifest.toml
Labels: size-mid

#6452 Absolute Roleplay [Stable] [Testing-Live]
  stable/AbsoluteRoleplay/manifest.toml
  testing/live/AbsoluteRoleplay/manifest.toml
Labels: size-small
